### ISSUE TITLE
Dependency issues when installing Picca

### ISSUE THREAD

**Issue by m-herbold** [igmhub/picca#1027]
There is a [depreciation error](https://numba.pydata.org/numba-doc/latest/reference/deprecation.html), no longer a warning, when running some Picca functions since np.int is no longer supported in new versions of numba. 
 
When pip installing picca to a conda environment, some packages (like numba) automatically install a newer version (e.g., 0.57), which causes errors, so you have to manually downgrade some of the packages (e.g., numba=0.55.1) to match the [requirements.txt](https://github.com/igmhub/picca/blob/master/requirements.txt) file.

**Comment by p-slash** [comment]
Hi Meagan, can you also provide the exact error output you encounter? It sounds like the error is numba does not support np.int within njit

**Comment by m-herbold** [comment]
Here is a test conda environment using "pip install picca." The versions for some of the packages are higher than those in the requirement.txt file.

![image](https://github.com/igmhub/picca/assets/134715487/cea6d41b-2839-4330-a3db-d75ee97661d9)


The main one that I have seen issues with is numba, namely the np.int that you mentioned. It causes issues with some of the code like "picca_cf.py," 

![image](https://github.com/igmhub/picca/assets/134715487/6ec4d230-3d0f-4be0-9cd9-224380509161)

**Comment by Waelthus** [comment]
From the error msg you seem to be using picca v6.1.0 which indeed has those issues. But we did have a fix in PR #1002 (part of v7.0.0 and later)...

The master branch is tested against numpy 1.24.4 and numba 0.57.1 at the moment (we don't always change the requirements.txt file, only if newer versions break the tests and break backwards compatibility this is really necessary), and the tests run fine with those.

A simple pip install picca should now pick up v7.0.1 from yesterday.

If you really need to run v6.1.0 you'll need to downgrade your numpy and numba to lower version numbers, e.g. the ones in requirements.txt

**Comment by iprafols** [comment]
We'll close the issue provisionally, but please re-open it and let us know if you're still seeing this problem in version 7.x
