### ISSUE TITLE
Compute only the most relevant metal matrices

### ISSUE THREAD

**Issue by andreufont** [igmhub/picca#1029]
When one computes the metal matrices for Lya x Lya with the 4 Silicon lines and with the CIV line, Picca will compute the 5 auto-metal matrices (like CIV x CIV), the 5 Lya x metal cross-metal matrices (like Lya x SiII), and 10 metal x metal cross-matrices (like SiII x CIV). 

Vega, however, ignores everything except the 4 Lya x Silicon lines cross-metal matrices, and the CIV auto-metal matrix. In other words, 75% of the matrices currently computed are not even used.

Metal matrices are right now the most expensive runs in the Y1 analysis, so it would be great if we could make them faster.

One option is to add a fast-metal option that if turned on will only compute the 5 metal matrices described above. 

@iprafols , @calumgordon , @andreicuceu , @cramirezpe

**Comment by calumgordon** [comment]
I've added a PR for the relevant_metals branch which adds an option to picca_metal_dmat that does exactly as you describe
