### ISSUE TITLE
Instabilities in the tests of old analysis routines (picca_deltas)

### ISSUE THREAD

**Issue by Waelthus** [igmhub/picca#1032]
It looks like something in the automatic testing is unstable again. Two runs performed after just version bumps failed, but re-running the tests makes those pass. I think this only happens since releasing the requirements on iminuit to allow newer versions (and thus allow running with python 3.11 or later which cannot use the old version we pinned before).

However, if I see this right the only failure is in test1_deltas, i.e. running the old picca_deltas routines. Maybe we should just retire old picca deltas, old fitter2 and the corresponding tests completely (they will always stay available in tagged releases until at least v7.2), now that delta_extraction has been successfully used for a year.

**Comment by iprafols** [comment]
let's retire the old picca deltas then

**Comment by Waelthus** [comment]
we retired old picca in version 8.0.0
