### ISSUE TITLE
Include redshift evolution in the computation of the distortion matrix

### ISSUE THREAD

**Issue by andreufont** [igmhub/picca#1078]
Following an email from Nico Busca, it would be interesting to modify the current calculation of the distortion matrix to account for the growth of the Lya fluctuations with redshift. 
<img width="1178" alt="Notes_DM_Busca" src="https://github.com/user-attachments/assets/6cac2de8-60b3-4bc6-a97e-64fc8b96fd7e">

**Comment by calumgordon** [comment]
This has been added in the latest tagged version (v9.6.1), so I'll close the issue.
