### ISSUE TITLE
install from hackDay

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#123]
- Give instruction of install
   - all print should be the same

**Comment by londumas** [comment]
reject is 1 by default

**Comment by ngbusca** [comment]
* agreed for instructions!

* We should replace all print statements by sys.stderr.write or sys.stdout.write depending on whether we want things to be printed immediately (stderr) or we can accept latence (stdout).

* we could set rej=0 by default, but with rej=1 the code finishes immediately and the user is forced to think about it, while with rej=0 the code takes infinity to run.

**Comment by ngbusca** [comment]
@londumas can we close this issue?

**Comment by londumas** [comment]
@ngbusca. Are all "print"  replaced by sys.stderr.write or sys.stdout.write ?
If not we can open a new issue

**Comment by londumas** [comment]
changed to https://github.com/igmhub/picca/issues/220
