### ISSUE TITLE
rename "bias_lya*(1+beta_lya)"

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#133]
The parenthesis of this parameter are painfull when sending a job with it in arguments.
We could rename this parameter to:
    * bias_lya_combined_beta_lya
    * bias_lya_1_beta_lya
    * (your idea here)

**Comment by andreufont** [comment]
my idea: bias_sum_lya

Assuming f ~ 1,  you have 
  beta = bias_eta / bias_delta 
and therefore
bias_delta * (1+beta) = bias_delta + bias_eta = bias_sum

**Comment by ngbusca** [comment]
I disagree. Just add \( and \) to your script.

**Comment by ngbusca** [comment]
I mean \\(

**Comment by londumas** [comment]
"\(" only work in interactif mode, not when sending a job

**Comment by ngbusca** [comment]
I don't know what you mean by "when sending a job". At the Utah cluster I don't have a problem with the metal names which have parenthesis as well.

**Comment by londumas** [comment]
In CEA I have. I use a command called clubatch, given by the package.
Anyway, what does the standard python say ? I will have a look.

**Comment by ngbusca** [comment]
Did you try escaping the ( with a slash?

**Comment by londumas** [comment]
We add to add ' and ' at the begining of the command and at the end.
For example (where clubatch is a command in CEA to send jobs):
`clubatch ' time echo "(hello)" '`

**Comment by ngbusca** [comment]
I think you mean:

> We **H**ad to add ' and ' at the beginning ;^)
