### ISSUE TITLE
installation runtime error

### ISSUE THREAD

**Issue by mblomqvist** [igmhub/picca#135]
Trying to install pyLya on a Macbook Pro laptop with OSX El Capitan, anaconda python 3.5 with a separate environment set up for python 2.7. All listed dependencies have been installed (numba 0.33.0 is included in anaconda) Using 'python setup.py install', the installation downloads and processes llvmlite 0.18.0 but stops with the runtime error:

RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config

**Comment by mblomqvist** [comment]
It seems that numba was included in anaconda for python 3.5 but not applicable to the separate python 2.7 environment. A simple 'conda install numba' installed it along with llvmlite. The pyLya installation now finishes without errors.

**Comment by mblomqvist** [comment]
The installation created the new directories build/, dist/ and py/pyLyA.egg-info/ which git labels as 'untracked files’. Additional dependencies scipy and configargparse had to be installed for the python 2.7 environment using 'conda install'.

**Comment by ngbusca** [comment]
anaconda installs scipy by default... maybe there's something colliding between your 2.7 and 3.5 installations. I'll add configargparse to the setup.py install to have it installed by default.

**Comment by mblomqvist** [comment]
Anaconda for python 3.5 is installed and includes some of the dependencies. Rather than installing Anaconda again for python 2.7, a separate environment for python 2.7 can be created following the instructions here

https://stackoverflow.com/questions/24405561/how-to-install-2-anacondas-python-2-7-and-3-4-on-mac-os-10-9

This scenario is probably quite common for modern Python users who work in python 3 but need the backwards compatibility.

**Comment by ngbusca** [comment]
I'm not sure that python 3.5 packages will work in python 2.7... I'm sure people might want to have several versions of python in their computers, but it's up to them to handle correctly the dependencies. picca is written for python 2.7...
