### ISSUE TITLE
buffer size in fastMC and chi2Scan

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#153]
The fastMC take a long time to run and the buffer size is too big.
Do we want to change the default duffer size ?
Do we want to have an option giving the buffer size ?

https://stackoverflow.com/questions/3167494/how-often-does-python-flush-to-a-file

**Comment by ngbusca** [comment]
I agree that you should write to disk right after each realization

**Comment by ngbusca** [comment]
Either change the buffer size or flush...

**Comment by londumas** [comment]
fixed in fix_issue_153
