### ISSUE TITLE
print statements mention "pyLyA"

### ISSUE THREAD

**Issue by mblomqvist** [igmhub/picca#166]
Several print statements in the code mention the former name "pyLyA". For example, in picca/py/picca/fitter/parameters.py:

print '  pyLyA::py::parameters.py::  No model file.'

**Comment by londumas** [comment]
@mblomqvist , thanks for the funding.
Could you do a grep and corect all of these ?

**Comment by londumas** [comment]
Let me take care of this

**Comment by londumas** [comment]
fixed in fix_issue_166
