### ISSUE TITLE
Bad rest-frame stack

### ISSUE THREAD

**Issue by ngbusca** [igmhub/picca#168]
The stack of CIV deltas in the quasar rest-frame is quite far from flat.

![image](https://user-images.githubusercontent.com/4727509/28205894-487bdfb8-6884-11e7-853c-9d467fdba9b6.png)

**Comment by ngbusca** [comment]
I found the problem. The weights in the calculation of the mean continuum in prep_del were wrong.

![image](https://user-images.githubusercontent.com/4727509/28206206-52fd2338-6885-11e7-8cde-e9bfe4992f80.png)

**Comment by ngbusca** [comment]
fixed in master

**Comment by londumas** [comment]
Hi Nicolas, what was wrong ?

**Comment by ngbusca** [comment]
@londumas you can fit diff to see the changes.

**Comment by ngbusca** [comment]
I mean

```
git diff
```
