### ISSUE TITLE
adding DLA is not verbose

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#171]
adding DLA doesn't give any information.
It would be nice to print some in order to see if everything goes well.

**Comment by ngbusca** [comment]
Do you mean log the fact that there's a DLA catalog?

**Comment by londumas** [comment]
no, I mean log something like:
"found a DLA in forest ...."

**Comment by londumas** [comment]
I am trying to reproduce the DR12 cross result and had a bug linked to using the DR12_dla_catalog instead of the DR14

**Comment by ngbusca** [comment]
sure, why not

**Comment by londumas** [comment]
And it didn't tell me no DLA found, or something of the kind

**Comment by ngbusca** [comment]
That's because the thing_ids in DR14 are different from those in DR12, so you won't find the DLAs

**Comment by ngbusca** [comment]
It's not a bug ;^)

**Comment by londumas** [comment]
I remeber that now.
I just wanted the code to say to me that no DLA were found

**Comment by ngbusca** [comment]
Ok, that's a more general thing. E.g., one could use DR14Q and DR12Q for the delta field, or the DR12 vac, etc. We should find a way to issue a warning when different vacs are used (it might be on purpose).

**Comment by ngbusca** [comment]
I meant DR14Q for the cross correlation and DR12Q for the delta field

**Comment by londumas** [comment]
In the DLA catalog, some objects have a negative ThingId. Did you know that ?
Example:
['-00000001', '57006-07868-0875', '9.64039', '+0.6804', '2.584', '0', '0', '-1', '2.3', '2.3021', '20.27', '0.617', '-3.67', '0.36', '0.324', '0.246', '0.262', '0.603', '1.161', '01', '0.00', '0.00', '0.81', '-1.00', '0.95', '-1.00', '1.29', '-1.00', '1.48', '-1.00', '1.26', '-1.00', '1.31', '-1.00', '1.14', '-1.00', '3.21', '-1.00', '1.08', '-1.00', '0.00', '-1.00', '0.00', '-1.00']

**Comment by ngbusca** [comment]
yes, that's life

**Comment by londumas** [comment]
I find 24 of them. Did Pasquier told you what they are ?

**Comment by ngbusca** [comment]
These are objects that have a spectrum (so you can decide whether there's a DLA or not) but that, for some reason, are lost after changes in the photometric extraction algorithms. So they "don't exist" anymore, so they don't have a RA, DEC.

**Comment by londumas** [comment]
They do have a RA and dec:
'9.64039', '+0.6804' and they have a plate, mjd, fiberId

**Comment by ngbusca** [comment]
They are probably "inherited" from a previous photometric extraction (or are they sdss objects?)

**Comment by londumas** [comment]
fixed in fix_issue_171
