### ISSUE TITLE
Stack of delta in rest frame is not zero

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#173]
When running the DR14 lya forest on the first 10,000 forests, the stack is really not
compatible with zero in rest frame. However it is very compatible with zero in observed wavelength.
The two following plot are before projection

```
--in-dir          Spectra_from_forest_Fusion/out_prod/pixs
--drq             DR14Q_v3_0.fits
--nspec 10000
```

![lya_forest_stack_rf](https://user-images.githubusercontent.com/3166436/28319185-7ac5f3fe-6bcd-11e7-9b69-e762aa25d469.png)

![lya_forest_stack_obs](https://user-images.githubusercontent.com/3166436/28319181-796c229e-6bcd-11e7-9126-58ee10c6eff9.png)

**Comment by ngbusca** [comment]
There must be something wrong with your calculation of the stack. This is what I get for DR12 (I'm checking for DR14, but it can't be very different).

![image](https://user-images.githubusercontent.com/4727509/28319758-149e54a2-6bcf-11e7-815d-844c36d7b083.png)

**Comment by londumas** [comment]
Here is what I do:

```

fi = glob.glob(in_dir+"/*.fits.gz")
data = {}
ndata = 0
for i,f in enumerate(fi):
	if i%1==0:
		sys.stderr.write("\rread {} of {} {}".format(i,len(fi),ndata))
	hdus = fitsio.FITS(f)
	dels = [delta.from_fitsio(h) for h in hdus[1:]]
	ndata+=len(dels)
	for d in dels:
		p = ndata%nproc
		if not p in data:
			data[p]=[]
		data[p].append(d)

	if not nspec is None:
            if ndata>nspec:break

## mean continuum
def mc(data):
    nmc = int((lmax_rest-lmin_rest)/dll)+1
    mcont = sp.zeros(nmc)
    wcont = sp.zeros(nmc)
    ll = lmin_rest + (sp.arange(nmc)+.5)*(lmax_rest-lmin_rest)/nmc
    for p in data:
        for d in data[p]:
            bins=((d.ll-lmin_rest-sp.log10(1+d.zqso))/(lmax_rest-lmin_rest)*nmc).astype(int)
            c = sp.bincount(bins,weights=d.de*d.we)
            mcont[:len(c)]+=c
            c = sp.bincount(bins,weights=d.we)
            wcont[:len(c)]+=c

    w=wcont>0
    mcont[w]/=wcont[w]
    mcont/=mcont.mean()

    return ll,mcont,wcont
```

**Comment by londumas** [comment]
@ngbusca  is that wrong ?

**Comment by ngbusca** [comment]
you are dividing by (almost) zero when you divide by mcont.mean()

**Comment by ngbusca** [comment]
Here's for DR14:

![image](https://user-images.githubusercontent.com/4727509/28320140-17a010fe-6bd0-11e7-92bf-5964d22408a4.png)

**Comment by londumas** [comment]
indeed, I copied the code without thinking.
Here is the new stack on the first 10,000 forests

![capture du 2017-07-18 15-49-07](https://user-images.githubusercontent.com/3166436/28320362-b2aa24b8-6bd0-11e7-9824-8444ef82e295.png)

**Comment by londumas** [comment]
Still incompatible with zero but way closer.
