### ISSUE TITLE
strange code indentations

### ISSUE THREAD

**Issue by mblomqvist** [igmhub/picca#174]
Some codes (for example cosmo.py) have strange indentations that mix tabs and spaces. Standard should be four spaces.

**Comment by londumas** [comment]
indeed, could you fix that with a simple ctrl+F or a grep ?

**Comment by ngbusca** [comment]
Unfortunately it's not that simple since there's a mixture of tabs and spaces...

**Comment by londumas** [comment]
grep -P '\t' py/picca/*

**Comment by ngbusca** [comment]
@londumas I don't think there's a simple solution, but if you think there's one, then it's all yours!

**Comment by londumas** [comment]
fixed in fix_issue_174
