### ISSUE TITLE
clone statment should have username in it

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#176]
To clone the repository, the best is to do:
```
 git clone https://<username>@github.com/igmhub/picca
```

**Comment by ngbusca** [comment]
This is not how github recommends to clone, see:
https://help.github.com/articles/cloning-a-repository/

**Comment by ngbusca** [comment]
Here's more info: https://help.github.com/articles/which-remote-url-should-i-use/

**Comment by londumas** [comment]
The first link you give is when cloning a repository you own.

**Comment by londumas** [comment]
If I do `https://github.com/igmhub/picca.git` then I will not be able to do `git push` since I am not 'igmhub' but 'londumas'

**Comment by ngbusca** [comment]
@londumas they use your own repo as an example, but it applies to anything. What's the problem with the current recomendation from the readme?

**Comment by ngbusca** [comment]
that is not true, when you push you will be asked for your username and password

**Comment by ngbusca** [comment]
igmhub is not a user

**Comment by londumas** [comment]
Indeed, this work.
I had a problem few days ago but it works now.
