### ISSUE TITLE
add fit parameter for at/ap ratio

### ISSUE THREAD

**Issue by mblomqvist** [igmhub/picca#178]
Add a new option in the fitter to fit for the ratio at/ap, i.e. the Alcock-Paczynski parameter (from BAO). It's a minor update, but a nice extra feature. The fit parameters would be ap and at/ap. Any suggestions for the parameter name?

**Comment by ngbusca** [comment]
This sounds like an aiso/1+epsilon rotation of the alphas (see https://arxiv.org/pdf/1206.6732.pdf) Why not change the current fit_aiso option to aiso and 1+epsilon. Then if we want to do the current aiso we just fix 1+epsilon.

**Comment by ngbusca** [comment]
It also economizes fitting options by recycling the current aiso

**Comment by mblomqvist** [comment]
Yes, that seems reasonable, with the downside being the slight confusion that the "isotropic" fit actually isn't unless a second parameter is fixed to unity.

**Comment by mblomqvist** [comment]
One more note: the mapping from 1+epsilon to F_AP = D_A / D_H is non-linear. Are there any practical consequences of that (e.g., connecting confidence levels with chi-squared differences)?

**Comment by ngbusca** [comment]
The model is already non-linear in the alphas, which means that we can't straight-fowardly connect confidence levels to delta-chi2. So whatever we do wee need to check with, e.g., the fast MC.

**Comment by ngbusca** [comment]
by the way, we can always call it 1+epsilon and define 1+epsilon = at/ap (or the inverse). I wouldn't necessarily take the cubic root.

**Comment by mblomqvist** [comment]
Yes, but the fastMC is run for 1+epsilon, not F_AP. Doesn't it make the post-processing to get F_AP a bit extra complicated?

**Comment by ngbusca** [comment]
I don't think so, you end up with a mapping dchi2 <==> probability. Then you plot dchi2 vs F_AP and get the intervals.

But you are right, you could also directly use F_AP instead of 1+epsilon. I would still do a 2-parameters shift of the peak using aiso (where the name would stem from the fact that it's an isotropic dilation for F_AP=1).

**Comment by mblomqvist** [comment]
Enhancement merged in master.
