### ISSUE TITLE
negative continua

### ISSUE THREAD

**Issue by ngbusca** [igmhub/picca#179]
negative continua don't currently have any special treatment. Should we:
1) continue ignoring this fact
2) force the continuum fit to give a positive continuum
3) reject objects with a negative continuum 

If 3), we should leave the possibility that an object rejected with a negative continuum in a given iteration is accepted in a subsequent iteration if the continuum gets positive.

**Comment by mblomqvist** [comment]
Do you mean that some or all pixels are negative? How many quasars are affected?

**Comment by ngbusca** [comment]
For the DR12 auto sample there are ~1500 forests where a continuum has at least one pixel where it's negative. Note that for Bautista et al. I used strategy 3) above, but it's not currently implemented in picca.

**Comment by mblomqvist** [comment]
Option 3) sounds reasonable. I discarded the bulk of such noisy spectra already in an earlier step of my analysis by requiring that the median S/N > 0.

**Comment by londumas** [comment]
I am in favour of nb3. In my own code I would remove all spectra if even one pixel of the continuum was negative.

**Comment by ngbusca** [comment]
@mblomqvist has a point in that a fourth option would be to do a preselection. This is a nice alternative since it decouples the data cuts from the continuum fitting.

@mblomqvist : after your s/n selection you never find negative continua (i.e. where at least a pixel is negative)?

**Comment by mblomqvist** [comment]
The S/N requirement doesn't eliminate all of them, unfortunately, so one still has to impose some cut after the continuum fitting step. I removed ~200 spectra by requiring that the median continuum > 0, and left the rest of them in the sample. Clearly, that may not be optimal.

**Comment by ngbusca** [comment]
I don't think we should allow negative continua in the sample since that would invert the delta field in those lines of sight. I'll implement option 3)

**Comment by mblomqvist** [comment]
Fixed in master.
