### ISSUE TITLE
DLA catalog format changed between DR12 and DR14

### ISSUE THREAD

**Issue by ngbusca** [igmhub/picca#181]
The columns with the absorption redshifts and column density changed between DR12 and DR14. These columns are currently hard-coded in picca. I'll change them in master to read the DR14 format, but we need a better long-term solution.

@mblomqvist @londumas @vserret

**Comment by ngbusca** [comment]
ideally we would have a fits file where we can just select using the name of the column. Should we write a parser from ascii to fits for the DLA catalog?

**Comment by mblomqvist** [comment]
Did they? I'm comparing the DLA ascii files for DR12 and DR14 (v2) and the z_abs and NHI columns haven't changed.

**Comment by ngbusca** [comment]
Hm... you are right... I was confused by the description it says that col6 is the absorption redshift while it's col10. 

Still, I'll push a fix which uses the line with the column names. This is safer and less "hardcoded"

**Comment by ngbusca** [comment]
This is now fixed in master
