### ISSUE TITLE
Different results with Mac and Linux for the computation of continuum 

### ISSUE THREAD

**Issue by Cyeche** [igmhub/picca#196]
I run do_deltas over 209 QSOs (plates 5400 and 5401) with MacOS and Linux. both are using anaconda and minuit 1.2. The results obtained for the continuum are significantly different, see below:

MacOS
zqso_min = 2.0
zqso_max = 4.28846153846
mode: spec
start               : nb object in cat = 267
and thid>0          : nb object in cat = 267
and ra!=dec         : nb object in cat = 267
and ra!=0.          : nb object in cat = 267
and dec!=0.         : nb object in cat = 267
and z>0.            : nb object in cat = 267
and z>zmin          : nb object in cat = 215
and z<zmax          : nb object in cat = 215
BAL_FLAG_VI not found

determining nside
nside = 4 -- mean #obj per pixel = 107
69 read from pix 64, 0 2 in 0.0551429821566 secs per spectrum
146 read from pix 80, 1 2 in 0.0648926166976 secs per spectrum
iteration:  0
done
1.15336441064 0.0677665770834 110.091659867 15718.0
1.17267825963 0.0773352199875 68.7153841527 22164.0
0.932121511047 0.110899488553 113.824156419 16372.0
0.910248057573 0.108549343579 54.6598958748 11513.0
0.883830907236 0.113704464933 122.335327441 9243.0
0.500000000386 0.138225236614 91.8879396395 7884.0
0.500002530275 0.156250846708 87.495399522 6007.0
1.49997890322 0.104481082518 39.5364910793 4165.0
0.504706807895 0.189742031521 8.37985957683 2461.0
0.500000004294 0.208236749977 28.8600646287 1374.0
iteration:  1
done
1.195999886 0.0500321016323 73.5889107771 16777.0
1.1333376836 0.0627647131671 77.5519849932 22237.0
1.00636145415 0.0750398505275 65.0928334564 16304.0
0.947256800147 0.0727746295095 73.3983483792 11322.0
0.907862047782 0.0862053969072 47.5417877049 9245.0
0.500000413997 0.11399906815 57.4513544161 7976.0
0.858920692481 0.10966702221 53.3057814551 6025.0
1.48937526665 0.0922679234376 22.8898572429 4142.0
0.500000000211 0.178713362116 13.416280279 2461.0
0.62885123965 0.180328153162 2.98810428874 1374.0
iteration:  2
done
1.1674105691 0.0483071687315 65.0253038892 16779.0
1.15987296599 0.0595267244137 65.1073080129 22236.0
0.992670019912 0.0726042397117 50.3624439471 16408.0
0.995709429377 0.0664159786451 36.3505272455 11472.0
0.872396830245 0.0827904792908 45.6172402572 9298.0
0.500000351947 0.111739400005 28.6906158552 7853.0
0.750776346121 0.110081986706 50.0575261198 5952.0
1.49995664046 0.0878117613609 31.3532945478 4088.0
0.500011813025 0.177210931111 4.78673305956 2461.0
0.500000068351 0.161592966105 13.6506940077 1374.0
iteration:  3
done
1.17631630566 0.0472240617622 72.2263348808 16810.0
1.17086854403 0.0587428018874 78.8350158842 22083.0
1.00736562618 0.0717430054087 41.0739037346 16300.0
1.03347496357 0.0637762942838 43.2778913623 11306.0
0.937570405836 0.0798008894721 50.8170265017 9215.0
0.500000017883 0.10733890804 26.66502874 7927.0
0.718943711244 0.110703947155 44.3015018499 5955.0
1.43166179273 0.0891875164608 39.701068036 4093.0
0.500000095502 0.171469228004 15.8036478227 2461.0
0.576118976703 0.164599290324 3.04259309241 1374.0
iteration:  4

Linux
zqso_min = 2.0
zqso_max = 4.28846153846
mode: spec
start               : nb object in cat = 267
and thid>0          : nb object in cat = 267
and ra!=dec         : nb object in cat = 267
and ra!=0.          : nb object in cat = 267
and dec!=0.         : nb object in cat = 267
and z>0.            : nb object in cat = 267
and z>zmin          : nb object in cat = 215
and z<zmax          : nb object in cat = 215
BAL_FLAG_VI not found

determining nside
nside = 4 -- mean #obj per pixel = 107
69 read from pix 64, 0 2 in 0.0462531697928 secs per spectrum
146 read from pix 80, 1 2 in 0.0510262119942 secs per spectrum
iteration:  0
done
1.15552210952 0.0675412200453 110.1276927 15718.0
1.17273143218 0.0773551852242 68.9110706092 22164.0
0.931124488499 0.111167616416 113.34802344 16372.0
0.910249681387 0.108549341956 54.6599434879 11513.0
0.883832279313 0.113704469798 122.337021075 9243.0
0.500000000386 0.138225236614 91.8879396395 7884.0
0.500002530275 0.156250846708 87.495399522 6007.0
1.49997890322 0.104481082518 39.5364910794 4165.0
0.504706807895 0.189742031521 8.37985957683 2461.0
0.500000004294 0.208236749977 28.8600646287 1374.0
iteration:  1
done
1.16611692409 0.0491318932291 79.216180531 16711.0
1.16301101246 0.0616924916498 68.5405082583 22136.0
0.970192293854 0.0819132648576 26.7561480942 16402.0
0.944492880276 0.0720078875438 78.702674229 11492.0
0.87746874811 0.0864692674603 63.1182531722 9347.0
0.500000041336 0.110381401605 52.3263485345 7954.0
0.784179635856 0.113645425439 46.0159515226 6030.0
1.46767872775 0.0911304071785 19.5753213028 4113.0
0.500000000044 0.174706116875 15.5900523381 2461.0
0.873342016634 0.176032031678 2.07191742245 1374.0
iteration:  2
done
1.16867559604 0.0468194585281 84.0773037092 16779.0
1.1514478489 0.0597158805759 91.2248741628 22311.0
1.0188341242 0.0714066507367 44.3021047181 16398.0
1.02533885336 0.0653036271328 36.4538289531 11477.0
0.906882430497 0.0817859793287 49.6710663632 9305.0
0.500000005631 0.108098943841 46.3646965958 7865.0
0.771473355381 0.108868300929 57.2996734145 5944.0
1.41314541215 0.0920209491461 20.2290742415 4092.0
0.50000005302 0.17323789554 11.4787464404 2461.0
0.55092003359 0.166182259157 5.96895239723 1374.0
iteration:  3
done
1.20330143597 0.0441468975546 61.9272228848 16760.0
1.15649099218 0.0592311903028 70.0250211335 22034.0
0.960394834911 0.0770389823171 29.2299694843 16299.0
1.00144299101 0.0661398690096 52.4077608833 11305.0
0.863785924332 0.0841278498969 56.4055888287 9215.0
0.500000001435 0.108509431154 32.207834058 7926.0
0.812253287494 0.105348757844 56.8560233828 5943.0
1.46591271736 0.0874770320633 20.5458783163 4093.0
0.500001016618 0.172499321072 8.11809687788 2461.0
1.4999998285 0.154271283578 1.25776632963 1374.0
iteration:  4

**Comment by ngbusca** [comment]
@Cyeche this should be fixed in branch linux_vs_mac, can you check?

**Comment by ngbusca** [comment]
@Cyeche see pull request #194

**Comment by Cyeche** [comment]
I check against the branch linux_vs_mac and I got exactly the same results for Mac and Linux. Is-it possible to mege the fix to our Dev_Pk1D branch?

Thanks, Christophe.

**Comment by ngbusca** [comment]
I've fixed the bug in master, thanks for reporting.
To get the changes into your branch do

'''
git checkout Dev_Pk1D
git merge master
'''

**Comment by ngbusca** [comment]
fixed and merged to master
