### ISSUE TITLE
Order of fit in do_deltas

### ISSUE THREAD

**Issue by Cyeche** [igmhub/picca#202]
The order of the continuum fit is not used in do_deltas (in io.read_data), I fixed it in Dev_Pk1D. Do not forget to propagate it at the time of the merging of the branches.

**Comment by londumas** [comment]
can you fix this @vserret ?

**Comment by mblomqvist** [comment]
Wasn't this fixed in #203?

**Comment by londumas** [comment]
@mblomqvist, doesn't seem to be since in /bin/do_deltas.py, "order" isn't used.

**Comment by mblomqvist** [comment]
Update #203 added the passing of order from do_deltas to io.read_data, which was missing before

**Comment by londumas** [comment]
You are right. It is in the very long line 161.
