### ISSUE TITLE
do_cf1d.py error

### ISSUE THREAD

**Issue by mblomqvist** [igmhub/picca#218]
The code do_cf1d.py stops with the error:
Traceback (most recent call last):
  File "picca/bin/do_cf1d.py", line 157, in <module>
    cfs = cfs.reshape(n1d,n1d)
ValueError: can only specify one unknown dimension

**Comment by londumas** [comment]
what is the dimension of n1d ?

**Comment by ngbusca** [comment]
Can you add enough info to reproduce this? If n1d =-1 you would get an error like this. It might be an inconsistency in the input parameters.

**Comment by mblomqvist** [comment]
Default values for lambda-min and dll, but lambda-max = 6840

**Comment by mblomqvist** [comment]
There is a bug in the code:
forest.lmax = sp.log10(args.lambda_min)
forest.lmin = sp.log10(args.lambda_max)

**Comment by londumas** [comment]
my fault apparently... sorry

**Comment by londumas** [comment]
let me fix that

**Comment by londumas** [comment]
fixed in https://github.com/igmhub/picca/pull/219.
Can you see if it is ok @mblomqvist  ?

**Comment by mblomqvist** [comment]
Rerunning it now.

**Comment by mblomqvist** [comment]
Runs smoothly and the result looks good.
![civ_corr1d](https://user-images.githubusercontent.com/2251656/32469541-8345e5ec-c353-11e7-901a-f23b40694a03.png)

**Comment by londumas** [comment]
fixed
