### ISSUE TITLE
replace "print"  by sys.stderr.write or sys.stdout.write or print()

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#220]
print has changed in Python3, should be replaced to either sys.stderr.write or sys.stdout.write or print()

**Comment by mblomqvist** [comment]
Can you elaborate on the problem? Python 2 is forward-compatible with the print parenthesis used in Python 3. Error reporting should be done with sys.stderr.write.

**Comment by londumas** [comment]
there are print without parenthesis, those are not forward-compatible

**Comment by mblomqvist** [comment]
I know, so that could be added instead of moving away from using print (when appropriate)

**Comment by londumas** [comment]
@mblomqvist, you are right.

**Comment by ngbusca** [comment]
I'm not too worried about compatibility with python3 (for now), but we could one day systematically do 
`
from __future__ import print_function
`
and use parenthesis. This is very very very *very* low priority

**Comment by londumas** [comment]
fixed in PR https://github.com/igmhub/picca/pull/278

**Comment by londumas** [comment]
fixed in PR https://github.com/igmhub/picca/pull/279
