### ISSUE TITLE
parser for spFrame and spCFrame files

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#239]
Because of `sp.unique` the "ll" array can have a different dimension as the other arrays in py/picca/data/__init__().
An example is with spFrame:
/uufs/chpc.utah.edu/common/home/sdss02/ebosswork/eboss/spectro/redux/v5_9_0//6825/spFrame-b2-00176029.fits.gz
and only with rebin=1.
I give here the data (bug.txt) and a code to reproduce the bug, this seems to be corrected by replacing `sp.unique(bins)` by `sp.arange(bins.max()+1`

[bug.txt](https://github.com/igmhub/picca/files/1475782/bug.txt)

```
import scipy as sp
import matplotlib.pyplot as plt

###
lambda_min = 3600.0
rebin = 1
###
lmin = sp.log10(lambda_min)
dll = rebin*1e-4

###
data = sp.loadtxt("bug.txt")
ll = data[:,0]
fl = data[:,2]
iv = data[:,3]

###
bins = ((ll-lmin)/dll+0.5).astype(int)

###
w    = (bins>=0)
ll   = ll[w]
fl   = fl[w]
iv   = iv[w]
bins = bins[w]
print ll.size, iv.size, fl.size

###
#ll = lmin + sp.arange(bins.max()+1)*dll
ll = lmin + sp.unique(bins)*dll
ll = ll[bins.min():]
civ = sp.bincount(bins,weights=iv)
civ = civ[bins.min():]
cfl = sp.bincount(bins,weights=iv*fl)
cfl = cfl[bins.min():]

w = (civ>0.)
cfl[w] /= civ[w]

iv = civ
fl = cfl

print ll.size, iv.size, fl.size
```

**Comment by londumas** [comment]
It also appears that the first `w=civ>0` is useless in:
```
        ll = forest.lmin + sp.arange(bins.max()+1)*forest.dll
        civ = sp.bincount(bins,weights=iv)
        w=civ>0
        civ=civ[bins.min():]
        cfl = sp.bincount(bins,weights=iv*fl)
        cfl = cfl[bins.min():]
        w=civ>0
        cfl[w]/=civ[w]
        iv = civ
        fl = cfl
```

**Comment by ngbusca** [comment]
@londumas this bug corresponds to the branch read_spframe? If yes, please feel free to change the code as you see fit, not much need of having a discussion if there are obvious problems.

Of course, I'm happy to discuss possible implementations of different features.

Funaly, note that the files you want to use are the spCFrame, which are the calibrated spectra, not the spFrames which are not calibrated in flux

**Comment by londumas** [comment]
@ngbusca, the bug is in py/picca/data/init()

**Comment by londumas** [comment]
I encontered using spcframe, but it isn't linked to spcframe

**Comment by ngbusca** [comment]
picca is not supposed to work on spFrames (yet!)

**Comment by ngbusca** [comment]
can you provide an example of this but with the standard input files? i.e. spec- or pix?

**Comment by londumas** [comment]
No I never encotered it before.
This arise I think from having pixels on uneven grids.
Do you have an idea of what to do ?
It is linked to `sp.unique(bins)` and my `sp.arange()` doesn't work in all cases.

**Comment by ngbusca** [comment]
if it ain't broken, don't fix it!

**Comment by londumas** [comment]
in the first post you have an example of some data

**Comment by ngbusca** [comment]
can you give the full command line that gives rise to this error?

**Comment by londumas** [comment]
`if it ain't broken, don't fix it!` it is broken for spframe and spcframe.
You need the update of the branch, I created a new one
Here is an example:
```
--in-dir          /uufs/chpc.utah.edu/common/home/sdss02/ebosswork/eboss/spectro/redux/v5_9_0/
--drq             /uufs/astro.utah.edu/common/home/u6011908/Data/Catalogs/DR14Q_v3_1.fits
--out-dir         /uufs/astro.utah.edu/common/home/u6011908/Run_programs/igmhub/picca/DR14_spframe/Delta_CIV/Delta/
--iter-out-prefix /uufs/astro.utah.edu/common/home/u6011908/Run_programs/igmhub/picca/DR14_spframe/Delta_CIV/Log/delta_attributes
--log             /uufs/astro.utah.edu/common/home/u6011908/Run_programs/igmhub/picca/DR14_spframe/Delta_CIV/Log/input.log
--mask-file       /uufs/astro.utah.edu/common/home/u6011908/Programs/igmhub/picca/etc/dr14-line-sky-mask.txt
--rebin 3
--mode spcframe
--lambda-min 3600.0
--lambda-max 7235.0
--lambda-rest-min 1410.0
--lambda-rest-max 1530.0
--nit 10
--bi-max 0.
```

**Comment by londumas** [comment]
you have the branch here https://github.com/igmhub/picca/tree/fix_issue_238

**Comment by londumas** [comment]
it isn't finished

**Comment by ngbusca** [comment]
This can't be a problem in the master branch, since it doesn't read spframes or spcframes. You seem to be reporting a problem with the read_spframe branch. Is this the case?

**Comment by londumas** [comment]
sory, you should have rebin=1

**Comment by londumas** [comment]
yes, it isn't a bug of the master

**Comment by ngbusca** [comment]
can you post the screen output, if it's not too long?

**Comment by londumas** [comment]
![capture d ecran de 2017-11-15 12-19-17](https://user-images.githubusercontent.com/3166436/32855547-3eb75a2a-c9ff-11e7-8623-4764999d34cc.png)

**Comment by ngbusca** [comment]
What we want is a parser for spFrame and spCFrame. If the code in this branch doesn't work, just write something else. It's simple in principle, you just need to resample the wavelength grid to a common grid and then coadd the different exposures...

**Comment by londumas** [comment]
> you just need to resample the wavelength grid to a common grid and then coadd the different exposures

Isn't already what data.py is doing ?

**Comment by ngbusca** [comment]
It doesn't seem to work, no?

**Comment by londumas** [comment]
inded, it doesn't. Do you have an idea why ? Your re-sampling in data.py should work.

**Comment by ngbusca** [comment]
Today I would write the resampling code as follows:

`
    ll = forest.lmin + sp.arange(bins.max()+1)*forest.dll
    fl = sp.zeros(bins.max()+1)
    iv = sp.zeros(bins.max()+1)
    civ = sp.bincount(bins,weights=iv)
    iv[:len(civ)]+=civ
    cfl = sp.bincount(bins,weights=iv*fl)
    fl[:len(cfl)] += cfl
    w=iv>0
    fl[w]/=civ[w]
`

**Comment by londumas** [comment]
ok, I will have a look.

**Comment by londumas** [comment]
the same as https://github.com/igmhub/picca/issues/238
