### ISSUE TITLE
Add nside info in do_delta

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#243]
It is useful to have the nside of the do_delta output files.
Where should we put it?
    - a master.fits or master.txt files
    - inside the do_delta.fits.gz output

**Comment by mblomqvist** [comment]
How about saving nside in the iteration output file? It summarises the attributes of the do_deltas analysis.

**Comment by londumas** [comment]
I think it is a good idea. @ngbusca, what do you think ?

**Comment by ngbusca** [comment]
Yep, it makes a lot of sense. For completeness we should also save the scheme (ring or nest)

**Comment by londumas** [comment]
@ngbusca, shouldn't we move "order" to this file also ? It makes more sens than have the same number written a lot of times.
