### ISSUE TITLE
from_image data import

### ISSUE THREAD

**Issue by jfarr03** [igmhub/picca#249]
In the file py/picca/data.py, I believe there are a small number of errors in the 'from_image' method. These are listed below:

1. "dec = h[3]["DEC"][:]*sp/180." should read "dec = h[3]["DEC"][:]*sp**.pi**/180."
2. "w = iv>0" should read "w = **ivar**>0"
3. The line "deltas.append(delta(thid[i], ... ,delt))" is missing the argument 'order', the final argument required for the "delta" class

Errors 1 and 2 have been corrected in a new branch named "from_image", and error 3 has been avoided by simply setting "order" to 1 (though this may not be a suitable long-term solution).

**Comment by ngbusca** [comment]
@jfarr03 thanks for catching this. Indeed, this is code that we haven't used to quite a while (maybe we never did), so I'm not surprised there are bugs. Regarding the order,  it is important if you want to calculate a distortion. As long as you run do_cf.py with the --no-project option, you won't need the order, so you can safely se it to 1.

**Comment by ngbusca** [comment]
@jfarr03 please open a PR so we can include your changes in the master branch.

**Comment by jfarr03** [comment]
Great, thanks for getting to this so quickly! I'm not currently able to push my local branch to github as it seems I don't have the correct permissions. I don't know if there is a simple way to change this at your end?

**Comment by ngbusca** [comment]
I sent you an invitation to join de repository. After accepting you should be able to push to your branch...

**Comment by jfarr03** [comment]
Thanks very much - I've now pushed my branch and have submitted a pull request

**Comment by londumas** [comment]
@ngbusca, do you think it is a good idea to have `order` be hardcoded ?
When do we use from_image ?

**Comment by ngbusca** [comment]
@londumas this are files derived from simulations that have the exact continuum, the order doesn't make sense.
