### ISSUE TITLE
removed info of delta in do_metal_xdmat

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#252]
https://github.com/igmhub/picca/blob/e8f1c07ff9e846bf3030af14d860c8f977bab47b/py/picca/xcf.py#L317

in `do_metal_xdmat` we use at multiple times the delta so we should remove only `neighs` and not the other attributes

**Comment by londumas** [comment]
The `Neighs` attributes is calculated only once, so we can't remove it.
@vserret, could you explain to me why do we give a list of metal to the code instead of running the code with different metals every time ?

**Comment by ngbusca** [comment]
@londumas we want to have all the matrices in the same output file no? In any case, this functionality was there in the beginning, I think we want that.

**Comment by vserret** [comment]
This would be better to have just one file at the end. Especially if you want to put it in the fitter.

**Comment by londumas** [comment]
@ngbusca, I never used the file, so I can't tell.
The solution is then to calculate neighs at every step of the loop over metals.

**Comment by londumas** [comment]
Could you do that @vserret ?

**Comment by ngbusca** [comment]
@londumas that's very slow. The best is to not remove the neighs attribute in this function.

**Comment by ngbusca** [comment]
@londumas please remove lines 317, 318 from this file.

**Comment by ngbusca** [comment]
@londumas since you made this change, can you take care of it? Also, please make sure that a similar bug wasn't introduced at other places.

**Comment by londumas** [comment]
> @londumas that's very slow. The best is to not remove the neighs attribute in this function.

If we do that then we put back the issue of filling the memory of the computer.

**Comment by londumas** [comment]
This issue should also be present in do_metal_dmat (ie for cf)
