### ISSUE TITLE
Remove useless data in forest1-forest2 cross-correlation

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#258]
In the forest1-forest2 cross-correlation, we don't remove data from a forest if too far from the last or first pixel of the other forest.
Here is an example with LyalyaxCIVciv, we can see that there are extra pixel that are too far from one another to go in the correlation function for r_paral in [-200,200]:
```
do_cf.py --out test.fits --in-dir ../DR14/Delta_LYA/Delta/ --in-dir2 ../DR14/Delta_CIV/Delta/ --rp-min -200.0 --lambda-abs 1215.67 --lambda-abs2 1550.77845 --nspec 1000
```

![lya-lya_civ-civ](https://user-images.githubusercontent.com/3166436/33447233-e9e331aa-d5bf-11e7-8dfc-4d81302d54fd.png)

Useful code to plot the distribution
```
    import matplotlib.pyplot as plt
    z_pix = sp.array([])
    for pix in cf.data:
        for d in cf.data[pix]:
            z_pix = sp.append(z_pix,d.z)
    plt.hist(z_pix,bins=100,histtype='step',linewidth=4,label="LYAlya")
    z_pix = sp.array([])
    for pix in cf.data2:
        for d in cf.data2[pix]:
            z_pix = sp.append(z_pix,d.z)
    plt.hist(z_pix,bins=100,histtype='step',linewidth=4,label="CIVciv")
    plt.grid()
    plt.xlabel("z")
    plt.ylabel("#")
    plt.legend(fontsize=20, numpoints=1,ncol=2, loc=1)
    plt.show()
```

**Comment by londumas** [comment]
This improvement concerns: `do_cf.py`, `do_dmat.py`, `do_metal_dmat.py`

**Comment by vserret** [comment]
I do not understand your point

**Comment by vserret** [comment]
If you want to avoid low z deltas, you just have to change the values of lambda-min during the computation of the deltas. 
But we can modify the cf.fill_neighs and include a z selection, I don't know if it is usefull.  
What do you think @ngbusca ?

**Comment by londumas** [comment]
@vserret, the point is that we are keeping pairs, that will not be in [rpmin,rpmax]. This take computing time. How much I don't know. We can have a faster code by removing these pairs. Maybe it is not worth it, maybe it is.

**Comment by vserret** [comment]
ok, I can try I see if it is faster

**Comment by londumas** [comment]
@vserret, can we remove this issue?
