### ISSUE TITLE
definition of angmax should be after removing delta

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#260]
In do_xcf.py, do_xMetalGrid.py, do_metal_xdmat.py, do_xdmat.py, the definition of angmax should be after removing delta too far from first or last pixel

**Comment by ngbusca** [comment]
do we gain anything? Is it really worth complicating the code for this?

**Comment by ngbusca** [comment]
The probability of introducing a bug is proportional to the number of lines. If we gain 0.1% I prefer not to do it.

**Comment by londumas** [comment]
Then let's define `angmax=2*sp.pi`, this will take one line, it is simple, less chance of bugs, but very long.

**Comment by ngbusca** [comment]
then you lose many many %, not 0.1%

**Comment by londumas** [comment]
fixed in https://github.com/igmhub/picca/pull/261
