### ISSUE TITLE
lambda_abs_name is not used

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#266]
https://github.com/igmhub/picca/blob/22c5b6e1f23b10cc32363e48be80aef1ff9ac787/bin/do_metal_xdmat.py#L57

What was the purpose of adding `lambda_abs_name`, shouldn't we have a `object_name`?

**Comment by ngbusca** [comment]
@londumas Yes, it's nonsense. It will be fixed in the fitter2 branch once review all the metal-matrix calculations.

**Comment by londumas** [comment]
fixed in PR https://github.com/igmhub/picca/pull/300

**Comment by londumas** [comment]
fixed in PR https://github.com/igmhub/picca/pull/299
