### ISSUE TITLE
doing auto-correlation with a line different than LYA is treated as a cross-correlation

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#270]
https://github.com/igmhub/picca/blob/509d00c0fe7ad79bac07cc75b6a6c5e62f1fe47e/bin/do_cf.py#L58
this line should have None as a default, as is --in-dir2

and:
```
    elif args.lambda_abs != args.lambda_abs2:   
```
should also look if `args.lambda_abs2` is `None`

**Comment by londumas** [comment]
this issue seems to be in all related "do_*" of forest-forest correlation

**Comment by ngbusca** [comment]
@londumas Thanks for catching this. While fixing this bug, I propose that we change the --lambda-abs from float to a string corresponding to the name of the absorption transition from constants.py. We should systematically do it in do_cf, do_dmat, do_met... etc.

**Comment by londumas** [comment]
@ngbusca, I agree.

**Comment by mblomqvist** [comment]
So then one has to add a line in constants.py when using a wavelength that isn't already defined?

**Comment by londumas** [comment]
@mblomqvist, yes. This seems reasonable.
What do you think?

**Comment by mblomqvist** [comment]
It requires that the user also can edit the code (or ask for it to be edited), but I guess the list in constants.py is already pretty extensive so there shouldn't be a real problem.

**Comment by ngbusca** [comment]
We can move this list to etc/... we should also add a CIV(eff) line with the average CIV lines.

**Comment by londumas** [comment]
related to PR https://github.com/igmhub/picca/pull/273
