### ISSUE TITLE
wrong rounding name

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#271]
https://github.com/igmhub/picca/blob/509d00c0fe7ad79bac07cc75b6a6c5e62f1fe47e/py/picca/constants.py#L58

**Comment by mblomqvist** [comment]
Yes, I've noticed this in my runs but didn't correct it, because I didn't want to rerun for thus reason alone.

**Comment by londumas** [comment]
yes. I agree with you.
The best is to correct this after the CIV publication.

Next time, could you write the issue when you spot a bug, and say: "let's not correct this before one month?"

**Comment by mblomqvist** [comment]
Sure, I can do that.

**Comment by londumas** [comment]
@mblomqvist, thanks

**Comment by londumas** [comment]
fixed in PR https://github.com/igmhub/picca/pull/283
