### ISSUE TITLE
covariance matrix can not be smoothed with pixels not measured

### ISSUE THREAD

**Issue by andreufont** [igmhub/picca#274]
If you use fine binning, or if you are using a test data set, it is possible that you do not cover all the bins in your measurement. 

When this happens, export.py is not be able to smooth your covariance matrix, and it crases. 

It would be nice to fix this so that it can deal with unmeasured bins.

**Comment by londumas** [comment]
fixed via PR https://github.com/igmhub/picca/pull/319
