### ISSUE TITLE
MgII absorption wavelengths written in constants.py are different from the ones given by NIST 

### ISSUE THREAD

**Issue by vserret** [igmhub/picca#280]
Lines found with NIST in vaccum : 2 796.352 and 2 803.530 
constants.py                                 : 2796.3511 and 2803.5324

**Comment by londumas** [comment]
I used lines from http://cdsads.u-strasbg.fr/cgi-bin/nph-iarticle_query?1991ApJS...77..119M&amp;data_type=PDF_HIGH&amp;whole_paper=YES&amp;type=PRINTER&amp;filetype=.pdf.
Maybe they are outdated.

Also I take all detected lines from these references:
https://arxiv.org/pdf/1309.6768.pdf
https://arxiv.org/pdf/astro-ph/0601279.pdf
https://arxiv.org/pdf/1610.02711.pdf

**Comment by ngbusca** [comment]
NIST values usually have a reference, can you check @vserret ?

**Comment by vserret** [comment]
primary data source for Mg lines : 
Wavelengths and Energy Level Classifications of Magnesium Spectra for All Stages of Ionization (Mg I through Mg XII),
    V. Kaufman and W. C. Martin, 
    J. Phys. Chem. Ref. Data 20, 83–152 (1991) 
    DOI:10.1063/1.555879

**Comment by londumas** [comment]
@vserret, what is the conclusion of this? I better not change anything

**Comment by londumas** [comment]
@vserret, can we close this issue?
