### ISSUE TITLE
sort lines

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#282]
https://github.com/igmhub/picca/blob/58bcfd7b2ee8c3fce204c26b1c23512129a531c7/py/picca/constants.py#L79

@ngbusca, could you place this line on top ?
I think it is best for the future that the lines are sorted.

**Comment by ngbusca** [comment]
@londumas good to know that someone is watching :^) I noticed that after I did the commit. Do you have an opinion on the name of the line? H-alpha? Ha?

**Comment by londumas** [comment]
I have no opinion on the name of the line.
Thank you.

**Comment by londumas** [comment]
fixed in PR https://github.com/igmhub/picca/pull/283
