### ISSUE TITLE
excess correlation for lambda1==lambda2

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#284]
The physical correlation between two pixels of the same forests or of different forests has a contribution from a non-physical correlation.
This non-physical correlation could be related to the sky. It still needs to be understood.
It is a function of theta: something like xi = theta^parameter

Here is the x(l1/l2,theta) correlation of the MgII_1 and MgII_2 forests. You can see the strong line at l1/l2==1.

![capture d ecran de 2018-01-05 22-43-50](https://user-images.githubusercontent.com/3166436/34701166-de9f7b20-f4a3-11e7-8b69-3ab138d36af7.png)

Here is the comparison between the Lya auto-correlation and the MgII_2 auto-correlation.

![capture d ecran de 2018-01-08 18-43-12](https://user-images.githubusercontent.com/3166436/34701167-dec03fe0-f4a3-11e7-82d6-c45ab7912860.png)

in the code, in def fast_cf(z1,r1,w1,d1,z2,r2,w2,d2,ang,same_half_plate):

The safe and conservative way is to remove all these pairs:
```
    if ang_correlation:
        w = (rp==1.)
        wd12[w] = 0.
        w12[w]  = 0.
    else:
        w = (rp==0.)
        wd12[w] = 0.
        w12[w]  = 0.
```

The more realistic way is to let the user decide, since for Lya it is small and could be estimated redward, or maybe moddeled.
```
    if remove_same_wave:
        if ang_correlation:
            w = (rp==1.)
            wd12[w] = 0.
            w12[w]  = 0.
        else:
            w = (rp==0.)
            wd12[w] = 0.
            w12[w]  = 0.
```

**Comment by ngbusca** [comment]
@londumas are you using coadds of multiple observations or the best observation?

**Comment by londumas** [comment]
@ngbusca, I use `/uufs/astro.utah.edu/common/home/u6011908/Data/Spectra/ForetFusion/Repeats/.

**Comment by londumas** [comment]
@ngbusca, I have noticed no difference when using spcframe.
A good test I could do would be to use skyfibers with a random  redshift for the fake "QSO". It would help see if it is the sky or something else. What do you think?

**Comment by ngbusca** [comment]
@londumas the spcframe option still coadds all the available observations. You want to make sure that you use only one plate per spectrum.

**Comment by ngbusca** [comment]
@londumas actually one plate-mjd combination per spectrum

**Comment by londumas** [comment]
@ngbusca, I use only one plate-mjd per QSO since I use DR14Q. However the spcframe option coadds the different exposures of the same plate-mjd.

**Comment by ngbusca** [comment]
@londumas it doesn't matter what DRQ you use, the --spcframe option will coadd all the available spCFrames regardless of the MJD. If you want to use only the best observation you have to add the option --best-obs to do_deltas.

**Comment by londumas** [comment]
Here is a comparison between the pix mode and the spcframe+bestObs+singleObs mode.
We can see that this large scale correlation of l1==l2 pixels is still there.

![capture d ecran de 2018-01-11 22-14-58](https://user-images.githubusercontent.com/3166436/34860752-ebf1d81a-f71c-11e7-9701-dcc797c4536d.png)

**Comment by ngbusca** [comment]
@londumas can you do this test on mocks? If would tell us if this correlation comes from the way we subtract the mean delta/mean continuum.

**Comment by londumas** [comment]
@ngbusca, it cannot be "subtract the mean delta/mean continuum" since it is present in the cross correlation of different forests. for exemple MgII_1 vs. MgII_2. It has to be something else.

**Comment by ngbusca** [comment]
@londumas I see, you are right. Do we see a similar excess in an auto-correlation? CIV (in CIV) auto might be a good test.

**Comment by londumas** [comment]
@ngbusca, we see this in MgII auto-correlation and in the MgII_1 vs MgII_2 cross-correlation.
So it must be in the CIV auto-correlation, but it must be less important.

**Comment by londumas** [comment]
@ngbusca, here is the cross-correlation between Lya and MgII_2:
![capture d ecran de 2018-01-13 03-04-53](https://user-images.githubusercontent.com/3166436/34905085-d141da5e-f80e-11e7-95c9-13f5ebbb2043.png)

**Comment by londumas** [comment]
@ngbusca, do you agree to add the option to remove the same lambda wavelength?
Or should we do something else? Do you want to have a deeper understanding of what is happening?

**Comment by ngbusca** [comment]
@londumas in these tests, is the binning in the correlation function the same as the deltas?

**Comment by londumas** [comment]
What do you mean by this? It is given by angle and l1/l2. The binning is not linked to delta binning

**Comment by ngbusca** [comment]
I want to know whether the bins in l1==l2 in your cf can get contributions from deltas with l1 != l2.

**Comment by ngbusca** [comment]
It would be good to do these plots with a binning that is exactly adapted to the delta-binning.

**Comment by londumas** [comment]
There are no contribution of l1!=l2 into the l1==l2 curve. I filler them out with the code in the first post

**Comment by ngbusca** [comment]
In this case, if we reject pairs with l1==l2 that would lead to an empty l1==l2 bin? What's the need for this cut then, can't you simply ignore the bin?

**Comment by londumas** [comment]
@ngbusca. I think I was not clear enough. I used the auto correlation of forests xi(l1/l2,Delta angle) to investigate the different issues with the auto-correlation of forests xi(rp,rt). Now that we know that there are spurious correlations between pairs at the same wavelength, we can add the option to remove these pairs so that the measured xi_ff for 0<=rp<4 doesn't have this contribution.
Would you accept such a PR?

**Comment by londumas** [comment]
fixed by adding an option to reject these pairs
