### ISSUE TITLE
Add option to ignore same_half_plate in do_cf

### ISSUE THREAD

**Issue by andreufont** [igmhub/picca#285]
The current code to measure auto-correlation function treats differently pixel pairs that are in the same half plate, i.e., the same set of 500 fibers in a SDSS plate that go into the same spectrograph. The reason is that these fibers have a common calibration and sky model, resulting in extra correlations (as discussed in Bautista et al. 2017). 

While this is a great feature for SDSS analyses (BOSS, eBOSS), it does not apply to all Lya analyses, in particular in DESI. The equivalent of the half-plate in DESI will be the "petal", a group of 500 fibers that will go into the same spectrograph. However, each Lya quasar in DESI will be observed 4 times, but each time it will be grouped into a different petal, and if we decided to work with coadded spectra we could ask whether two spectra have the "same-half-plate" or the "same-petal". 

In the context of DESI we will need to discuss what will be the best approach, and we could potentially decide that we want to use single exposures, but in any case it would be great to have an option in picca to *ignore* whether two spectra share the same-half-plate or the same-petal.

@jfarr03 and I could try to add this option, with some guidance from a picca developer.

**Comment by ngbusca** [comment]
We are facing the same problem en eBOSS (see PR #281), the notion of a half plate (or half petal) gets blurry when you coadd. I don't know what the best solution is, but I don't see how not doing any rejection solves anything or why you would like to use these pairs that you will never use in a realistic analysis. It would be great, though, to use a more generic definition of a half_plate such that it handles both (e)boss and desi, would that work for you?

I think the ultimate solution is to do the analysis using auto and cross correlations of all available exposures without any coaddition, but we are quite far from there.

**Comment by andreufont** [comment]
I don't have a clear answer for what is the best way to do this, and I agree that what you suggested would be really interesting to look at. But as you say, we are a bit far from there, and we need other solutions in the short term.

The reason why we need to do something about this is that when running picca on colore skewers, we do not have an equivalent for PLATE or FIBER, we just set them all to 0. But then it means that we do not measure correlations on very small separations, since they are always in the same half plate, and this makes everything painful. 

Alternatively we could add a hack in our picca delta files, where we set PLATE=MOCKID, so that all spectra have a different plate, and pairs are not excluded... but I think it would make sense also to have an option to ignore same-half-plate clause. 

For the long term, I believe the right way to look at this is that we would have a function "mask_pixel_pair", or similar, that would do different things depending on what is the survey that you are analyzing. If you are running with "survey==SDSS3" it would use same_half_plate, but if you are running on a different survey you might do something else.

PS: In DESI the key element is a petal, group of 500 fibers that go to the same spectrograph. There is no such thing as a half-petal.

**Comment by ngbusca** [comment]
As in PR #281 , I wouldn't like to implement a patch but an actual improvement (i.e. extending the rejection to something that works regardless of whether data is eboss or desi), and implement an option to ignore the rejection as part of that enhancement.

But it sounds like the quickest hack for you is to give each of your l.o.s. a different plate number, then you will keep all the pairs. Does that work?

**Comment by andreufont** [comment]
Yes, that is the hack that I suggested above, we can set PLATE=MOCKID.

We will do this, since implementing something better would require us to dig deep into picca. May be another day.

**Comment by ngbusca** [comment]
What would actually work is to use the combination camera-spectroid-exposureid which is the unit on which the calibration pipeline runs (both for eboss and desi). So instead of half_plate we need to keep track of the list individual camera-spectro-exposure that contributed to the corresponding coadd. I'll try to implement this change (and add the option to not do the rejection).

**Comment by londumas** [comment]
Fixed in PR https://github.com/igmhub/picca/pull/513
