### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#286]
In the light of many PR, we want standard tests to be run before merging.
The idea is to create fake data with given seed, maybe 10,000 forest would be enough.
Create a random DRQ, then random pixel.

**Comment by londumas** [comment]
Here is a code to generate random catalog and forest. What do you think of this ?

```
#
# Produce fake data for a full Lya-Lya and QSO-Lya study
#   Copy the range of PLATE, MJD, ... from SDSS DR14Q
#

import scipy as sp
import numpy.random
from scipy.interpolate import interp1d
import fitsio
import healpy

def produce_cat(path_DRQ,nObj):

    print("Create cat with number of object = ", nObj)

    ### Create random catalog
    ra    = (360.-0.)*numpy.random.random_sample(nObj) + 0.
    dec   = (90.+20.)*numpy.random.random_sample(nObj) - 20.
    plate = numpy.random.randint(266,   high=10001, size=nObj )
    mjd   = numpy.random.randint(51608, high=57521, size=nObj )
    fid   = numpy.random.randint(1,     high=1001,  size=nObj )
    thid  = sp.arange(1,nObj+1)
    zqso  = (5.8-1.7)*numpy.random.random_sample(nObj) + 1.7
   
    ### Save
    out = fitsio.FITS(path_DRQ,'rw',clobber=True)
    cols=[ra,dec,thid,plate,mjd,fid,zqso]
    names=['RA','DEC','THING_ID','PLATE','MJD','FIBERID','Z']
    out.write(cols,names=names)
    out.close()

    return
def produce_forest_in_pixel(path_PIX,path_DRQ,nside):

    ### Load DRQ
    vac = fitsio.FITS(path_DRQ)
    ra    = vac[1]["RA"][:]*sp.pi/180.
    dec   = vac[1]["DEC"][:]*sp.pi/180.
    thid  = vac[1]["THING_ID"][:]
    plate = vac[1]["PLATE"][:]
    mjd   = vac[1]["MJD"][:]
    fid   = vac[1]["FIBERID"][:]
    vac.close()

    ### Get Healpy pixels
    pixs  = healpy.ang2pix(nside, sp.pi/2.-dec, ra)

    ### Save master file
    path = path_PIX+"/master.fits"
    head = {}
    head['NSIDE'] = nside
    cols  = [thid,pixs,plate,mjd,fid]
    names = ['THING_ID','PIX','PLATE','MJD','FIBER']
    out = fitsio.FITS(path,'rw',clobber=True)
    out.write(cols,names=names,header=head,extname="MASTER TABLE")
    out.close()

    ### Log lambda grid
    logl_min  = 3.550
    logl_max  = 4.025
    logl_step = 1.e-4
    ll = sp.arange(logl_min, logl_max, logl_step)

    ###
    for p in sp.unique(pixs):

        ###
        p_thid = thid[(pixs==p)]
        p_fl   = numpy.random.normal(loc=1.0, scale=1., size=(ll.size,p_thid.size))
        p_iv   = numpy.random.lognormal(mean=2.0, sigma=1.0, size=(ll.size,p_thid.size))
        p_am   = sp.zeros((ll.size,p_thid.size)).astype(int)
        p_am[ numpy.random.random(size=(ll.size,p_thid.size))>0.90 ] = 1
        p_om   = sp.zeros((ll.size,p_thid.size)).astype(int)

        ###
        p_path = path_PIX+"/pix_"+str(p)+".fits"
        out = fitsio.FITS(p_path, 'rw', clobber=True)
        out.write(p_thid, header={}, extname="THING_ID_MAP")
        out.write(ll,     header={}, extname="LOGLAM_MAP")
        out.write(p_fl,   header={}, extname="FLUX")
        out.write(p_iv,   header={}, extname="IVAR")
        out.write(p_am,   header={}, extname="ANDMASK")
        out.write(p_om,   header={}, extname="ORMASK")
        out.close()

    return
```

**Comment by londumas** [comment]
@ngbusca, I fI understood the idea. We want to store the current results of do_cf, do_xcf preformed on the random in a folder. And for each merge request compare the new products to the old ones. Do we agree ? Where would you like these files to be stored ? /data/tests/ ?

**Comment by ngbusca** [comment]
@londumas yes, that's right. What is done in desihub? We could follow their model. Otherwise, I don't have a preference, data/tests is very good.

**Comment by londumas** [comment]
@ngbusca,In desisim, they put some stuff in py/desisim/test/data/. But I don't like mixing code with data. What do you think ?

**Comment by ngbusca** [comment]
It probably has to do with the automatic travis tests from github (but I don't know anything about it). Let's get something working, we can move it later if we need to.

**Comment by londumas** [comment]
fixed in PR https://github.com/igmhub/picca/pull/288

**Comment by londumas** [comment]
@ngbusca, is there a simple way to sort the data in do_cf, do_xcf, ... in order that the HEALPID are always in the same order?
For the moment, they arrive in the order of the end of the different process (I think).
Because of this the created correlations are presented differently. For one run first the healpix will be 10, for the other the first heaplix will be 2.
Is there an option in pool to coadd with an order?

**Comment by ngbusca** [comment]
pool.map(function, [arg list]) should return the result in the same order as [arg list], is it not the case?

**Comment by ngbusca** [comment]
The following code:

    from multiprocessing import Pool

    def Y(x):
        return x

    p=Pool()
    res1=p.map(Y, [1,2,3])
    res2=p.map(Y, [2,1,3])
    res3=p.map(Y, [1,3,2])

    print res1
    print res2
    print res3

returns:

    [1, 2, 3]
    [2, 1, 3]
    [1, 3, 2]
