### ISSUE TITLE
do_cf.py input from '.fits' files using '--from-image'

### ISSUE THREAD

**Issue by jfarr03** [igmhub/picca#289]
At the moment, it is only possible to use do_cf.py's '--from-image' option by specifying a directory or several directories. It would be useful to be able to specify one specific file, as often there are several '.fits' files in a directory, but only one is designed to be read by picca. Even more useful would be to specify multiple input files using wildcards, for example.

I have written a workaround which appears to enable the specifying of individual '.fits' files, which I can put into a pull request if you would like. 

Specifying multiple files can be done currently by putting the '--in-dir' argument into quote marks (so that the wildcards are expanded by glob.glob inside the script, rather than by the shell), though this seems a little unnatural, given that you would not have to do so normally.

**Comment by ngbusca** [comment]
We settled on this behaviour to avoid the limitation that some systems have on the length of the arguments (assuming an alternative where the user would list the input files). It might be unnecessary in the case of `--from-image`. 

I also find unnatural to use quotes and it also complicates sending scripts to batch systems (you'd need to escape the quotes). 

I propose to change the `--from-image` behaviour to specifying a list of files (the system would expand the wildcards), would that solve the problem? If yes, feel free to PR it.

**Comment by jfarr03** [comment]
That makes sense to me. In order to accept a list of arguments, the most logical method seems to be to use the " nargs='+' " option for the input directory. However that would result in args.in-dir being a list of strings (currently it just wants a single string), even if only one argument is provided. It would also change the behaviour when not using --from-image. 

It is fairly straightforward to work around this, by simply looping through the list of strings, and passing each item to the current process (using glob.glob), adding to the list of files each time. I think this should recreate exactly the same output as before - does it sound ok to you as a solution?

**Comment by londumas** [comment]
It will come a little bit out of nowhere, but I would be in favor of removing any options to read different type of files. I think that picca correlations should only read pixels files. Then it is the user responsibility to modify its own file format to be readable by picca. If picca adapts to every file format, it will grow too complicated.
However, if you find a nice way to read your files from py/picca/io.py, why not.

**Comment by ngbusca** [comment]
@jfarr03 I would prefer something that doesn't require touching the behaviour of --in-dir. What I would do, instead, is to change the --from-image option such that it accepts arguments instead of it being a flag (I use nargs="*", but "+" is fine with me), and override the argument of --in-dir if --from-image is present.

**Comment by ngbusca** [comment]
@jfarr03 I'm aware that my solution means setting --in-dir to dummy is --from-image is present, but let's worry about that later.

**Comment by andreufont** [comment]
@jfarr03 @ngbusca @londumas - a little bit of background: during the SLAC meeting we switched to a new format of storing the Lya skewers to be used by desisim, that has one file for each (rather small) HEALPix pixel. This file, called something like transmission-NSIDE-PIX.fits, would be in a folder called PIX, and that folder itself in a folder called PIX%100. For instance, you could have:
lya_skewers/v2.0.0/3/344/transmission-16-344.fits.
A part from these "transmission" files, that contain an array with 0 < F < 1, it is also convenient to have other files associated with the same simulation. For instance, we might want to have skewers storing only the density field, or delta_flux, or delta_flux without RSD... and we decided to store these in the same folder structure. 
Now, it is really convenient to be able to run picca on the delta_flux (or delta_density) files, using the --from-image option. But this means that now we want to run picca on multiple files that are sitting on different directories. 
Your suggestions above sound good, I just wanted to make sure you understood the motivation.
