### ISSUE TITLE
Tests failing on mac

### ISSUE THREAD

**Issue by ngbusca** [igmhub/picca#293]
As @Cyeche reported and I confirmed on my mac, automatic tests fail on some systems. @londumas do you have a mac to test on?

**Comment by londumas** [comment]
@ngbusca, I don't have access to a Mac. Could you tell me where does the unitest fail and what is the message?

**Comment by Cyeche** [comment]
For instance the output is:
python py/picca/test/test_cor.py






('Create cat with number of object = ', 1000)




 zqso_min = 2.0
 zqso_max = 4.28846153846
mode: pix
 start               : nb object in cat = 1000
 and thid>0          : nb object in cat = 1000
 and ra!=dec         : nb object in cat = 1000
 and ra!=0.          : nb object in cat = 1000
 and dec!=0.         : nb object in cat = 1000
 and z>0.            : nb object in cat = 1000
 and z>zmin          : nb object in cat = 1000
 and z<zmax          : nb object in cat = 1000
BAL_FLAG_VI not found

1 read from pix 272, 0 5 in 0.00101917392605 secs per spectrum
301 read from pix 304, 1 5 in 0.000559130899007 secs per spectrum
267 read from pix 336, 2 5 in 0.000510669252933 secs per spectrum
165 read from pix 337, 3 5 in 0.000451439231131 secs per spectrum
266 read from pix 368, 4 5 in 0.000499885694718 secs per spectrum
iteration:  0
done
0.815695993164 0.0989021805454 1.8004819023e-06 8.05823451938 7593.0 0.0985444787416 0.0619217617756 0.035626768484
0.916326183 0.0723145382359 3.68288205117e-06 6.58388517592 9198.0 0.126334034647 0.084597318835 0.018223826086
0.785955554977 0.10953456182 2.03890866089e-06 3.6604757507 9903.0 0.0565824059134 0.065916948348 0.029603890645
0.899605159919 0.0754616252642 7.39226676371e-07 8.14188630289 9631.0 0.0902843451965 0.0323936850666 1.98490126054e-07
0.731187389116 0.128979262993 2.60541837978e-06 16.2214726789 9723.0 0.0924890628001 0.0841448960645 0.02316902501
0.817018182848 0.102310696411 1.84551380324e-06 7.54967041131 9849.0 0.0763387472198 0.0600364311693 0.0317529769161
0.787719718626 0.116397849419 2.38008380244e-06 8.9508958438 10263.0 0.0509047671931 0.0721474033818 0.0264835174322
0.89521175294 0.0747804463126 7.8225524583e-07 17.9206502408 10847.0 0.0825651603936 0.0293604525736 1.98641858157e-07
0.855074157 0.0988230595056 1.50659393982e-06 2.20707924033 10880.0 0.0807155954739 0.057165847444 0.0311238505552
0.835615459598 0.0872669723259 1.29801026458e-06 14.5498797945 10424.0 0.101287568231 0.0430032272216 0.0424209208825
0.668025102233 0.168181311215 4.81540705402e-06 5.84818838349 11093.0 0.108229595939 0.0800407391241 0.0174257117212
0.972841953012 0.0466133993685 5.825206491e-07 3.89205677157 11601.0 0.0743363362656 0.0269436751762 1.97642741368e-07
0.937789193511 0.061445592569 1.99945732841e-08 12.0248093055 11234.0 0.0718710010966 0.0260585273599 1.05715277891e-07
0.886492388464 0.0785329019826 6.08243764435e-07 8.14172066054 11197.0 0.0784238518174 0.0282074232703 1.97825703822e-07
0.80617112002 0.106570272146 1.89050150806e-06 6.93592762486 9671.0 0.0538619431762 0.0726142722451 0.0300189532334
0.873728950382 0.0907093263653 1.54296270157e-06 16.7749403937 7777.0 0.128433883329 0.0572943298791 0.0459102464983
0.811257066552 0.102050056486 1.55538456367e-06 4.92623823674 6390.0 0.0692557857933 0.0887589909549 0.0365002350463
0.817468176287 0.101940354161 1.18824960907e-06 4.41178186439 4641.0 0.157847653299 0.0602574010508 0.00482051735193
1.0 0.1 1e-07 0.0 2845.0 0.0 0.0 0.0
1.0 0.1 1e-07 0.0 1186.0 0.0 0.0 0.0
iteration:  1
done
0.86437439181 0.0705538755633 6.96816740885e-07 6.45643107753 7593.0 0.0971085095563 0.0305588903082 1.98313684182e-07
0.96828438094 0.0481502506699 7.69817316597e-07 6.26285258519 9198.0 0.0816684060358 0.0278236587742 0.00168836431793
0.805791843992 0.0915898263167 1.23971260106e-06 2.20047692272 9903.0 0.0843320765028 0.0500505756132 0.0262455435829
0.903305120418 0.0652061439657 6.10333298054e-08 7.89474456551 9631.0 0.0805357349074 0.0262928443058 1.08466300233e-07
0.759723841676 0.109288057254 1.96717307365e-06 11.1323702768 9723.0 0.0568717082781 0.0628116197803 0.0247804103062
0.836530204559 0.0866470124967 1.22455798226e-06 10.9765243151 9849.0 0.104545998188 0.0405816603656 0.0338197407803
0.790025353187 0.106202068775 1.88635274527e-06 3.85457028867 10263.0 0.0531185829934 0.0596528260792 0.0234125824858
0.98009002777 0.0407391068219 3.47258962706e-07 14.6124955147 10847.0 0.0802319084032 0.0256608346921 1.93748341456e-07
0.901591663032 0.0745891962855 1.61245732084e-07 1.69815376653 10880.0 0.0786348385331 0.0254283087857 1.72162145147e-07
0.88506971176 0.0621001225221 3.10403452401e-07 15.4796927802 10424.0 0.0756991007085 0.0247149030044 1.92243305673e-07
0.618028528345 0.167509491332 4.49196111331e-06 9.31906297807 11093.0 0.110690059105 0.0728115320624 0.0136866574468
1.09165861212 0.000103406642148 2.46482869177e-06 10.4356321121 11601.0 0.0333770666503 0.0627412603008 0.00289868211885
0.966161478305 0.0461495348568 6.64222816274e-07 10.3615241992 11234.0 0.0735216500716 0.027322334923 0.00260542699992
0.928910964641 0.0570026831989 4.97408647523e-08 4.52428126139 11197.0 0.0767819166364 0.0248016926624 9.6774225737e-08
0.771269287825 0.106558043779 1.82984394483e-06 9.73327941935 9671.0 0.0488745186337 0.0652361716845 0.0239935311579
0.972182372016 9.97588689455e-07 0.0162337409488 7.4348807103 7777.0 0.0575370722164 0.0686775063845 0.00600053612177
0.896286040391 0.0653750152606 1.72018153969e-07 5.25970410852 6390.0 0.118463468716 0.0382586194056 1.75356953263e-07
0.901549913512 0.0678348462582 1.58121315519e-12 1.50144662611 4641.0 0.133341876992 0.0436476305647 0.000216896188061
0.907040014061 0.0759017295139 1.52942406416e-07 2.31320142835e-09 2845.0 0.700867385949 0.17109961424 0.0141614236559
1.0 0.1 1e-07 0.0 1186.0 0.0 0.0 0.0
iteration:  2
done
0.897990444639 0.0590199233577 2.2259519615e-07 5.60508867756 7593.0 0.0978851295458 0.0305815872015 1.85119287302e-07
0.990450672117 0.0408335513208 1.11111936427e-06 6.55408087594 9198.0 0.082564600842 0.029347881964 0.0024222183595
0.818969917241 0.0868375112742 1.06951511203e-06 2.65228811841 9903.0 0.0998107432734 0.0442451470562 0.0288873216848
0.907017715613 0.0635753049504 1.06133135431e-08 9.10486619922 9631.0 0.0799649278376 0.0259581766576 1.14027302037e-07
0.794630393949 0.0959631413292 1.35799500549e-06 9.39337399365 9723.0 0.0634152415574 0.0595374153268 0.0253171839504
0.849987485122 0.0821475827302 9.81387570281e-07 10.5465785756 9849.0 0.079863518614 0.0260263200543 1.99112685943e-07
0.794946300493 0.104782643836 1.69263407883e-06 4.18206301358 10263.0 0.0537307801233 0.0677817912921 0.0201982173726
0.988709796892 0.0378515644925 4.72311333403e-07 14.777808022 10847.0 0.0793996718008 0.0252226073121 1.96508218867e-07
0.916199812465 0.0692982341697 9.54481911249e-08 1.55509540716 10880.0 0.0787223507922 0.025334266956 1.38129431116e-07
0.931606511973 0.0469326082782 2.14580741595e-07 8.64882556365 10424.0 0.0753840438056 0.0243723488062 1.84000038525e-07
0.606871431912 0.170022358391 4.6381582887e-06 13.6530529763 11093.0 0.109883440533 0.0724578931042 0.0136160886875
1.08724145939 2.86102203978e-07 2.1310161124e-06 17.4974984218 11601.0 0.0210810612482 0.00935168854611 0.00150943064625
0.954313640035 0.0504176138737 4.43406767415e-07 8.16753474581 11234.0 0.0699964686525 0.0227402057644 1.96067805891e-07
0.958290701387 0.0474663766115 4.72131178887e-07 3.6910039768 11197.0 0.076221338672 0.0244493262374 1.96505715346e-07
0.772580685297 0.104323706027 1.82676402682e-06 15.8910348629 9671.0 0.0604561105472 0.0600167908212 0.025319788385
0.877216497661 0.080275769514 8.59997925492e-07 7.03922895666 7777.0 0.100497411561 0.0331383618106 1.98862847373e-07
0.899916156746 0.0636631492067 2.28041325145e-07 6.92196900432 6390.0 0.118454345823 0.0381478343334 1.85813886254e-07
0.922645456851 0.0605721229573 2.48604132199e-07 2.56734897718 4641.0 0.131702886902 0.0429238330758 0.000636590303631
0.909788956873 0.0765232259006 1.51320076636e-07 1.66877657313e-09 2845.0 0.700985993856 0.169756459031 0.0156373602213
1.0 0.1 1e-07 0.0 1186.0 0.0 0.0 0.0
iteration:  3
done
0.908997854285 0.0557107804952 5.9869851929e-08 4.93480084031 7593.0 0.0975186284238 0.0304066854584 1.07310713614e-07
0.994648780021 0.0394606202703 1.14527900423e-06 8.29962759837 9198.0 0.0835559540421 0.0302339501444 0.00270124741554
0.813180495803 0.0887623163659 1.12232463944e-06 3.88582516312 9903.0 0.0930678751946 0.0470548004976 0.0272298092236
0.914279448799 0.0613376977474 1.98357763125e-09 9.13408599127 9631.0 0.0802276666975 0.0260169975728 1.21803299395e-07
0.812351392418 0.0898727778115 1.08121034157e-06 12.1212645593 9723.0 0.0682306437213 0.054300584814 0.024345287926
0.861133637334 0.0781259840012 8.25439350285e-07 10.2556651968 9849.0 0.0797168917352 0.0259508141296 1.98771935118e-07
0.788864304026 0.106714460761 1.75528541758e-06 4.12450382847 10263.0 0.0519120431344 0.0674626225984 0.0204676003938
0.996623055185 0.0350764883243 5.76389035722e-07 14.5071508335 10847.0 0.07949931857 0.0252400396227 1.97595628479e-07
0.923740299378 0.0664678794078 7.43931669694e-09 4.08345245553 10880.0 0.0784358526405 0.0252175983832 1.16873690728e-07
0.936095504827 0.0449819914719 2.9977218658e-07 7.43043251869 10424.0 0.0751607112712 0.0242741247245 1.91702097745e-07
0.618148696359 0.166630270503 4.51140776381e-06 12.7329315466 11093.0 0.108916382085 0.0725014890007 0.0137653227417
1.08902128292 2.67549113364e-08 2.41526143416e-06 15.2766534251 11601.0 0.0254320384507 0.0181051393363 0.00210350670309
0.954343968621 0.0503351465292 4.6582123707e-07 6.33773269041 11234.0 0.0950216947256 0.038891453336 0.0292480808632
0.962084343139 0.0462157149986 5.10439252124e-07 4.13350791738 11197.0 0.076146045553 0.024401034773 1.96981532301e-07
0.772343679708 0.105029697038 1.84128728279e-06 14.3609834063 9671.0 0.0569318252037 0.0612790854863 0.0249755053728
0.874391525181 0.0817148411835 9.10666399984e-07 6.62896392822 7777.0 0.109680602713 0.0357508100491 1.98978714157e-07
0.88015901923 0.0693285628931 1.74551333485e-07 7.51689507665 6390.0 0.117524409241 0.0379598207954 1.76036420321e-07
0.962462043469 0.0454491612176 8.62397949465e-07 2.71850914545 4641.0 0.131504707921 0.0437859939594 0.00225318223288
0.917393240144 0.0782662491494 1.46820536503e-07 7.16940719187e-10 2845.0 0.704352996202 0.170284139214 0.0201438623144
1.0 0.1 1e-07 0.0 1186.0 0.0 0.0 0.0
iteration:  4
done
F
======================================================================
FAIL: test_cor (__main__.TestCor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "py/picca/test/test_cor.py", line 35, in test_cor
    self.send_delta()
  File "py/picca/test/test_cor.py", line 216, in send_delta
    self.compare_fits(path1,path2)
  File "py/picca/test/test_cor.py", line 194, in compare_fits
    self.assertFalse((d_m!=d_b).any())
AssertionError: True is not false

----------------------------------------------------------------------
Ran 1 test in 9.275s

**Comment by ngbusca** [comment]
In my mac it fails at a different place:

WARNING: do_deltas.py: Header key is stack, arrays are not exactly equal, ussing allclose
F
======================================================================
FAIL: test_cor (__main__.TestCor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "py/picca/test/test_cor.py", line 35, in test_cor
    self.send_delta()
  File "py/picca/test/test_cor.py", line 228, in send_delta
    self.compare_fits(path1,path2,"do_deltas.py")
  File "py/picca/test/test_cor.py", line 206, in compare_fits
    self.assertTrue(allclose,"{}: Header key is {}, maximum relative difference is {}".format(nameRun,k,diff.max()))
AssertionError: do_deltas.py: Header key is stack, maximum relative difference is 7.59933149899e-09

----------------------------------------------------------------------
Ran 1 test in 24.182s

FAILED (failures=1)

**Comment by londumas** [comment]
Could you both give me the output of:
```
ipython
import numpy.random
numpy.random.seed(1)
numpy.random.rand(10)
```

I get on two linux:
```
array([  4.17022005e-01,   7.20324493e-01,   1.14374817e-04,
         3.02332573e-01,   1.46755891e-01,   9.23385948e-02,
         1.86260211e-01,   3.45560727e-01,   3.96767474e-01,
         5.38816734e-01])
```

**Comment by Cyeche** [comment]
[  4.17022005e-01   7.20324493e-01   1.14374817e-04   3.02332573e-01
   1.46755891e-01   9.23385948e-02   1.86260211e-01   3.45560727e-01
   3.96767474e-01   5.38816734e-01]

**Comment by londumas** [comment]
@Cyeche, you have a previous version of the unittest, it would be nice to be uptodate with master.
@ngbusca, could you change the limit in `allclose` and see if that would be enough to make it work?

**Comment by ngbusca** [comment]
array([  4.17022005e-01,   7.20324493e-01,   1.14374817e-04,
         3.02332573e-01,   1.46755891e-01,   9.23385948e-02,
         1.86260211e-01,   3.45560727e-01,   3.96767474e-01,
         5.38816734e-01])

**Comment by Cyeche** [comment]
I’m using the master branch….

**Comment by ngbusca** [comment]
@Cyeche but did you do `git pull` on the master branch?

**Comment by londumas** [comment]
@Cyeche, could you do:
```
git checkout master
git pull
python py/picca/test/test_cor.py
```

**Comment by Cyeche** [comment]
YES I DID 
git pull
Already up-to-date.

**Comment by Cyeche** [comment]
Now  I have the same message as Nicolas

WARNING: do_deltas.py: Header key is stack, arrays are not exactly equal, ussing allclose
F
======================================================================
FAIL: test_cor (__main__.TestCor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "py/picca/test/test_cor.py", line 35, in test_cor
    self.send_delta()
  File "py/picca/test/test_cor.py", line 228, in send_delta
    self.compare_fits(path1,path2,"do_deltas.py")
  File "py/picca/test/test_cor.py", line 206, in compare_fits
    self.assertTrue(allclose,"{}: Header key is {}, maximum relative difference is {}".format(nameRun,k,diff.max()))
AssertionError: do_deltas.py: Header key is stack, maximum relative difference is 7.59933149899e-09

**Comment by ngbusca** [comment]
@Cyeche then your master was not up-to-date?

**Comment by Cyeche** [comment]
Not sure, I restart from scratch

**Comment by ngbusca** [comment]
@londumas if I use the default values of allclose instead of the ones you set, the tests pass. Any reason to make the comparison stronger? (for reference, desispec uses the defauls allclose values). 

Should I commit these changes to master?

**Comment by londumas** [comment]
@ngbusca, the only reason I had was to make it the closest possible.
I am ok with leaving the default values. You can change this.

**Comment by ngbusca** [comment]
@londumas it could also be related to the fact that we set nprocs to 4 but my computer doesn't have 4 procs. We should also try running the tests with nproc = 1 (but we'd need to generate new reference files). Could you create a new branch with new reference files generated with nproc = 1 instead? If it's too slow, feel free to reduce the number of quasars.

**Comment by londumas** [comment]
@ngbusca, This is really a possibility comparing 3 procs to 4 procs produces these 1e-9 differences.
I am going to see if it is not too slow

**Comment by londumas** [comment]
@ngbusca, now tests run on 1 proc. Please merge PR https://github.com/igmhub/picca/pull/294, and test again with mac.

**Comment by londumas** [comment]
@ngbusca and @Cyeche , what is the status with the updated master?

**Comment by julienguy** [comment]
Hi, I find python syntax errors in the fitter code in master (simply try do_fit) .

**Comment by londumas** [comment]
@julienguy, what is the error and what version of Python do you use?

**Comment by julienguy** [comment]
I see many errors. I am using python 3.6.4.
I am fixing this in a branch, starting from master and will open a PR

**Comment by londumas** [comment]
@julienguy, don't loose too much time on do_fit. In a week it will be replaced by fitter.
But if you have time, why not.

**Comment by londumas** [comment]
replaced by fitter2

**Comment by ngbusca** [comment]
Thanks @julienguy . An extra parenthesis appeared in l. 125 for Chi2.py... wow, when did that happen !! After fixing it I don't see any other errors, but I haven't tested systematically...

TODO: (@londumas ) we need a unitest for the fitters as well...

**Comment by londumas** [comment]
@ngbusca, does the unitest works on mac now?
@ngbusca, I don't think we should test do_fit. We are now only going to use fitter2. What do you think ?

**Comment by ngbusca** [comment]
@londumas no, nproc=1 didn't fix it. So I've restored the default settings for allclose. It's now merged in master

For the fitters unitest, ok, we can only do it for fitter2

**Comment by londumas** [comment]
@ngbusca, with the default for allclose, does it work now?

**Comment by ngbusca** [comment]
@londumas yes. It's already merged in master

**Comment by ngbusca** [comment]
Fixed in master
