### ISSUE TITLE
setup picca environment variables

### ISSUE THREAD

**Issue by ngbusca** [igmhub/picca#314]
It would be great to have the prefix of the model file to be independent of the .ini file. We could set this up with a picca environment variable (e.g. PICCA_BASE). @londumas what do you think? We should do it such that if PICCA_BASE is not defined, then we get the current behavior.

**Comment by londumas** [comment]
do you mean that `PICCA_BASE=$PICCA/py/picca/fitter2/models/PlanckDR12/PlanckDR12.fits`.
At least something like that?

**Comment by ngbusca** [comment]
I think what you call PICCA is what I call PICCA_BASE...

**Comment by londumas** [comment]
> It would be great to have the prefix of the model file to be independent of the .ini file.

@ngbusca, I don't understand what this mean.

**Comment by londumas** [comment]
fixed in PR https://github.com/igmhub/picca/pull/313
