### ISSUE TITLE
Add broadbands to fitter2

### ISSUE THREAD

**Issue by ngbusca** [igmhub/picca#321]
I'm willing to implement this unless someone else is working on it, @londumas ?

**Comment by londumas** [comment]
ok, cool. @ngbusca, I am not working on this.

**Comment by mblomqvist** [comment]
Any news about this issue?

**Comment by ngbusca** [comment]
Yes, sorry, on my plate...

**Comment by londumas** [comment]
@ngbusca, this seems to have been fixed. Am-I right?

**Comment by ngbusca** [comment]
implemented in master
