### ISSUE TITLE
do_deltas breaks when coadding observations

### ISSUE THREAD

**Issue by ngbusca** [igmhub/picca#325]
The new fields `diff` and `reso` are not updated when coadding observations via the function `__add__`.  For coadditions, the resulting delta field might have a different number of pixels than the initial delta field, which generates an inconsistency between the number of pixels in `diff/reso` and the rest `ll` etc.

@Cyeche we need your input to solve this problem: how should we coadd the diff and reso fields for an object with multiple spectra?

**Comment by Cyeche** [comment]
This new feature is in preparation of DESI spectra or for coadding several observation of BOSS/eBOSS. For the latter wisp should be coaxed as in SDSS pipeline, for diff you can use the function in Prep_Pk1D.

**Comment by londumas** [comment]
@Waelthus could you have a look at this issue and see if it is fixed?

**Comment by londumas** [comment]
Fixed in https://github.com/igmhub/picca/pull/540.
