### ISSUE TITLE
unitests for fitter2

### ISSUE THREAD

**Issue by ngbusca** [igmhub/picca#327]
@londumas any ideas what would be the best way to implement this?

**Comment by londumas** [comment]
@ngbusca, yes. Why not simply do a combined fit with metals with one bias_lya and one bias_qso and one SiIII\(1207\). Then compare the h5pt output.
I can take care of this if you want.

**Comment by londumas** [comment]
@ngbusca, doing a combined fit on `cf`, `xcf`, `cf_cross` works very well.
The only small issue is that some of the bins of the distortion matrix are empty.
We could set the rejection to lower and rerun `dmat`, `dmat_cross` and `xdmat` so that at least all bins of the matrix have been filled.
What do you think?

**Comment by londumas** [comment]
@ngbusca, the other small issue is that because we only have 1000 forests the covariance matrix is not positive definite.
This is only an issue for fastMC

**Comment by ngbusca** [comment]
I don't think we need a realistic distorsion matrix, we could just use the identity. I'm surprised that the covarinace is not positive definite, for the tests we go out to 60Mpc/h(?) so there are many less bins to calculate.

**Comment by londumas** [comment]
@ngbusca, I think it is noce to give the fit the distortion matrix calculated in the unittest. It allows to test the export script.
For the covariance matrix it can be linked also to the fact that the forests distributed on a small patch of the sky

**Comment by londumas** [comment]
@ngbusca, could you give me an exemple of running fast MC ? I could add it to the unit tests

**Comment by ngbusca** [comment]
@londumas to run a fast mc you can add:

    [fast mc]
    niterations = 1

to your `chi2.ini` file. I agree that it's better to use the output of the export.py script, but we need to keep the running time for each test under  ~a minute.
