### ISSUE TITLE
fitter2 cuts bins according to the mean rp,rt grid and not to the center

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#328]
In fitter, we were cutting bins according to the` rp, rt, r, mu` value at the center of the grid. not at the mean.
This allows to always have the same number of bins even if some data sets have different `rp, rt` grids.
Do we want to put back this way of cutting?
If yes, we should keed track of `'NT', 'NP', 'RTMAX', 'RPMIN', 'RPMAX'` in `export.py` and get the center of the grid from these parameters in `py/picca/fitter2/data.py`

**Comment by ngbusca** [comment]
I think the fix for this is quite simple, instead of doing, e.g., rmin=10 we could do rmin=9 or 9.5. Then we don't need to change anything in the code.

**Comment by londumas** [comment]
@ngbusca, I would prefer the code to be based on the center of the grid. We did it for the previous papers.

**Comment by ngbusca** [comment]
@londumas well, we did it in the previous papers just because we didn't realize at the time that we could have just change a little bit rmin.

**Comment by mblomqvist** [comment]
But then, formally, we would need to quote different rmin (e.g. 10 and 9.5) for different fits in the papers.

**Comment by ngbusca** [comment]
Yes, we would need a slightly lower rmin sich that it's equivalent to the previous fits.

**Comment by londumas** [comment]
@ngbusca, why don't you want to do it as we did in DR12 papers? We would just have to change `export.py` and `fitter2/data.py`.

**Comment by ngbusca** [comment]
Because I think that it really makes more sense to cut on the mean pixel separation than the pixel. Also it means we don't need to change anything in the code

**Comment by londumas** [comment]
@ngbusca and @mblomqvist, the thing I don't like about "a slightly lower rmin" is that how to decide the value of this lower rmin? `0.1`, `1.0`? We would have to tune this parameter.
Cutting on the center of the grid is better, there are no parameter to tune.
Currently with my MgII fit I have some correlations that have `3179` bins, other that have `3180` bins.

However if you really don't like cutting center of the grid I can take care of finding the "slightly lower rmin".

**Comment by mblomqvist** [comment]
I came across a fit where I had 3179 bins instead of 3180 bins, but the missing bin was at "slightly larger rmax" instead.

**Comment by londumas** [comment]
I made a PR (https://github.com/igmhub/picca/pull/374) to give an idea of what I have in mind when I was talking of cutting on center of the bins. This PR gives the same behavior as in fitter.

As @ngbusca, pointed it out to me the issue arises from cutting `rmin=10` when our bin size is `4` and so the bin center are `2, 6, 10, ...`. If we were cutting at `8` the issue would not arise with a bin size of `4`. However, if we change the bin size then we would recover the same problem.

I like the fact of using the center of grid because it allows us not to worry about this issue and leave the code always behave the same way for slightly different correlations. In the past we have introduced this way of cutting because the data and the mocks had different number of fitted bins (in Bautista et al paper), which is not very pleasing to the eye in a paper. Also since we are loosing the bin at low seperation, it can change a lot the strength of the signal.

What do you think @mblomqvist, @ngbusca?

**Comment by mblomqvist** [comment]
@londumas I have a mild preference for your suggestion. As I mentioned before, included bins also depend on rmax.

**Comment by ngbusca** [comment]
Ok guys, you win ;^)

**Comment by londumas** [comment]
@ngbusca, thank you @ngbusca. You will get a large bear next time we see.
