### ISSUE TITLE
syntax error for export.py

### ISSUE THREAD

**Issue by mblomqvist** [igmhub/picca#330]
export.py stops with "SyntaxError: future feature print_funcion is not defined". Run in anaconda python 2.7 environment.

**Comment by londumas** [comment]
@mblomqvist, corrected in PR https://github.com/igmhub/picca/pull/329

**Comment by mblomqvist** [comment]
OK, great.

**Comment by ngbusca** [comment]
@londumas we don't test this in the unitests?

**Comment by ngbusca** [comment]
Thanks @londumas for the fix and @mblomqvist for reporting it. Fixed in master
