### ISSUE TITLE
Missing cross-correlation models in fitter2

### ISSUE THREAD

**Issue by mblomqvist** [igmhub/picca#332]
Fitter2 does not support models for HCD, UV and combinations with veto_lorentz/gaus for the cross-correlation. In r-space, the QSO radiation model is not functioning properly.

**Comment by ngbusca** [comment]
@mblomqvist thanks for the reminder. I'll work on the hcds and uv. 

Can you expand on how the radiation model is not working properly?

**Comment by mblomqvist** [comment]
There is a QSO radiation model, but it 1) takes the wrong arguments 2) uses rp without being passed this argument 3) doesn't apply the drp shift in the actual model 4) asserts LYA even though the absorption tracer could be something else.

**Comment by ngbusca** [comment]
@mblomqvist feel free to PR a fix

**Comment by ngbusca** [comment]
@mblomqvist can we close this issue? Are there pieces still missing?

**Comment by mblomqvist** [comment]
We can close this specific issue now.
