### ISSUE TITLE
Naming inconsistency in fitter2

### ISSUE THREAD

**Issue by mblomqvist** [igmhub/picca#333]
Fitter2 uses 'hcd' and 'lls' in different functions. The former name is preferred.

There is also a mild preference to change sigmaNL_per to SigmaNL_per to reflect the Greek notation difference.

**Comment by ngbusca** [comment]
@mblomqvist well... Greeks will have to get used to it ;^)

**Comment by mblomqvist** [comment]
@ngbusca OK
