### ISSUE TITLE
Add Gaussian prior to fitter2

### ISSUE THREAD

**Issue by mblomqvist** [igmhub/picca#338]
Fitter2 does not support the option to add Gaussian priors on fit parameters.

**Comment by londumas** [comment]
@mblomqvist, when implementing this we need also need to keep track of the parameters in the output.
Maybe the simplest way to add Gaussian priors is to do something similar as the implementation of `chi2 scan`.

**Comment by ngbusca** [comment]
@londumas I don't understand what you mean by 

> we need also need to keep track of the parameters in the output.

**Comment by londumas** [comment]
@ngbusca, I mean that we need to add storing sigma_gaussian and mean_gaussian in the output of fitter2. It is different from https://github.com/igmhub/picca/issues/337 where the code will do it by itself, because the change consists in adding a regular parameter. Do you understand?

**Comment by ngbusca** [comment]
do you mean that we would need to store the parameters of the priors? I'd agree with that.

**Comment by londumas** [comment]
@ngbusca, yes. That what I mean.
