### ISSUE TITLE
Correlation with itself in cross-correlation

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#339]
In cross-correlations we attempt to reject correlations with itself using `THING_ID`.
The issue is that not all object have this attribute.
For example the galaxy catalogs don't have this info.
The issue is that some objects in the galaxy catalog are also in the quasar catalog.
We need to remove correlations between a forest and its emitter.
A simple solution is a comparison of both ra, both dec and both z.

**Comment by ngbusca** [comment]
@londumas how do they know that they don't have repeated objects in their sample?

**Comment by londumas** [comment]
@ngbusca, I don't understand the question.

**Comment by ngbusca** [comment]
@londumas never mind, can't you use spAll as a catalog for the objects? I thought that was the parent catalog for all clustering analyses. They reject some objects when they fall in low completeness regions, but for your cross-correlation with MgII you don't need care about that. Besides, I think picca accepts both spAll or DRQ formats.

**Comment by londumas** [comment]
Even inside DR14Q there seems to be repeated objects:

https://dr14.sdss.org/optical/spectrum/view?plate=6171&mjd=56311&fiberid=694
https://dr14.sdss.org/optical/spectrum/view?plate=7593&mjd=56958&fiberid=423

https://dr14.sdss.org/optical/spectrum/view?plate=7593&mjd=56958&fiberid=423
https://dr14.sdss.org/optical/spectrum/view?plate=6171&mjd=56311&fiberid=694

https://dr14.sdss.org/optical/spectrum/view?plate=6277&mjd=56273&fiberid=517
https://dr14.sdss.org/optical/spectrum/view?plate=7135&mjd=56564&fiberid=960

https://dr14.sdss.org/optical/spectrum/view?plate=7135&mjd=56564&fiberid=960
https://dr14.sdss.org/optical/spectrum/view?plate=6277&mjd=56273&fiberid=517

https://dr14.sdss.org/optical/spectrum/view?plate=7663&mjd=57328&fiberid=402
https://dr14.sdss.org/optical/spectrum/view?plate=7593&mjd=56958&fiberid=902

https://dr14.sdss.org/optical/spectrum/view?plate=7593&mjd=56958&fiberid=902
https://dr14.sdss.org/optical/spectrum/view?plate=7663&mjd=57328&fiberid=402

**Comment by londumas** [comment]
@ngbusca, I just talk with some DR15Q people.
It is known that there are repeated QSOs in DR14Q catalog. They are planning to remove multiple observations in DR15Q.

**Comment by ngbusca** [comment]
do they have different THING_ID?

**Comment by londumas** [comment]
@ngbusca, yes

**Comment by mblomqvist** [comment]
DR14Q is supposed to be organised by object, defined by the best observation. @londumas so several mistakes have been found?

**Comment by londumas** [comment]
@mblomqvist, yes. Apparently this issue of DR14Q is known to the DR15Q team. I found them also.
I am currently producing a DR14Q where I will to remove any second occurrence of:
```
 w   = |RA1-RA2|<0.01
 w &= |DEC1-DEC2|<0.01
 w &= |Z1-Z2|<0.01
```
I will see how many objects fall in this category.

**Comment by ngbusca** [comment]
@londumas this is not fine enough! You should check for angle < 1 arcsec

**Comment by mblomqvist** [comment]
@londumas out of curiosity, have you looked at what the fields N_SPEC and *_DUPLICATE in the catalog say for these objects?

**Comment by londumas** [comment]
@ngbusca, I agree. However with the diff_z condition it removes a lot of fake coincidences.
Also I prefer to be safe than not.
@mblomqvist, I have not. What do you have in mind?

**Comment by mblomqvist** [comment]
@londumas I was just curious whether they have N_SPEC=0 (i.e. claiming no duplicate spectra available for the object) or if they reference each other in *_DUPLICATE.

**Comment by ngbusca** [comment]
@londumas So are there repeated THING_IDs in DR14Q? If yes, then it's trivial to find these objects, no?

**Comment by londumas** [comment]
@ngbusca, There are no repeated THING_IDs in DR14Q, neither repeated TARGETIDs (redrock definition).
We really have to proceed to a 3d sphere matching.

**Comment by ngbusca** [comment]
So they have different THING_ID? How do you know they are the same object?

**Comment by ngbusca** [comment]
For example, for the first pair, you can see in the photometry that they are two different quasars that are very close: [http://skyserver.sdss.org/dr14/en/tools/chart/navi.aspx?ra=1.78016532079232&dec=21.1870203268623&scale=0.2](url)

**Comment by ngbusca** [comment]
Same thing for the second pair.

**Comment by londumas** [comment]
> So they have different THING_ID?

Yes
>How do you know they are the same object?

Because they really look the same and because the DR15Q team confirmed me they exist in DR14Q.
However they think there is only a small fraction.

**Comment by ngbusca** [comment]
Just look at the photometry, there are really two nearby quasars.

**Comment by ngbusca** [comment]
For the second example, the fluxes from each object are different by almost a factor of two, not very similar ;^)

**Comment by londumas** [comment]
@ngbusca, I am sure that the list I gave is not good enough because I was too liberal with my selection.
What is sure is that in galaxies cat, there are DR14Q objects (even from PLATE,MJD,FIBERID matching).
For duplicates in DR14Q, let me find a pair that would prove me wrong or right.

**Comment by ngbusca** [comment]
Sure! But the only.way is to check that the angle is less than an arcsec. 

⁣Sent from BlueMail ​

**Comment by londumas** [comment]
@ngbusca and @mblomqvist, indeed in DR14Q there was no pairs at less than 1 arcsec.
However there where in the galaxy catalog and between the galaxy and the quasar catalog.
