### ISSUE TITLE
minor issues with desi_from_ztarget_to_drq and desi_from_truth_to_drq

### ISSUE THREAD

**Issue by ngbusca** [igmhub/picca#347]
The function desi_from_ztarget_to_drq doesn't work. Indeed, the ztarget from redrock doesn't have RA DEC information. Like desi_from_truth_to_drq this function should input the targets.fits file as well.

There's another issue with the way these functions are implemented (specially desi_from_truth_to_drq): it is assumed that columns in target.fits and truth.fits are aligned (of course this won't work when inputing a zbest file). @londumas can you fix that and change the logic such that a dictionary is used to "align" truth/zbest and target.fits?

**Comment by londumas** [comment]
@ngbusca, could you give me the path to the truth and zbest files you use on Nersc to test this?

**Comment by ngbusca** [comment]
I'm using 

    /global/projecta/projectdirs/desi/datachallenge/dc17b/targets/truth.fits

and 

    /global/projecta/projectdirs/desi/datachallenge/dc17b/spectro/redux/dc17b/spectra-64/0/0/zbest-64-0.fits

**Comment by londumas** [comment]
@ngbusca, ok to fix comparing a dictionary for `desi_from_truth_to_drq`.
However why don't you use `/global/projecta/projectdirs/desi/datachallenge/dc17b/spectro/redux/dc17b/ztarget-dc17b.fits` for `desi_from_ztarget_to_drq`

**Comment by ngbusca** [comment]
I didn't know this file existed! I'll take a look

**Comment by londumas** [comment]
Here is the catalog and path that should be used:
```
from picca import utils
path_truth = "/global/projecta/projectdirs/desi/datachallenge/dc17b/targets/truth.fits"
path_targets = "/global/projecta/projectdirs/desi/datachallenge/dc17b/targets/targets.fits"
path_drq       = "test.fits.gz"
utils.desi_from_truth_to_drq(path_truth,path_targets,path_drq)
```

**Comment by londumas** [comment]
fixed in https://github.com/igmhub/picca/pull/348
