### ISSUE TITLE
Possible overflow of float

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#349]
For all my measurements `export.py` gives me a positive definite covariance matrix except for my GALAXYxMGII correlation.
This correlation has a lot of pairs, way more than the others.
One possible reason could be that the code in `export.py` or `py/picca/utils.cov` or in `py/picca/utils.smooth_cov` has some overflow of floats.
The problem could also be in `do_xcf.py`.
The problem could also be totally different.
I have tried to change nside from 16 to 32 and it had no effects.

**Comment by ngbusca** [comment]
Do you have your cf at nersc? I can take a look too...

**Comment by londumas** [comment]
@ngbusca, thank you very much.
It is in
`/global/homes/h/hdumasde/Run_programs/igmhub/picca/For_nicolas/xcf_forest1_MGII2_line1_MGII_obj1_LRGandCMASS.fits.gz`

**Comment by londumas** [comment]
I have looked at some aspects and found no problem:
    - If I take only the diagonal, the matrix is positive definite.
    - The smoothed correlation matrix is not positive definite.
    - It is not because some bins are empty (I tested), it is not because some healpix pixels are totally empty (tested also).

**Comment by londumas** [comment]
Here is the distribution of the non-diagonal terms of the smoothed covariance-matrix for different measured correlations.
Different things could be happening:
    - bug in `export.py`
    - non-vanishing correlation for each sub-sample
    - too many pairs with the same delta_MgII
![capture d ecran de 2018-03-01 14-45-30](https://user-images.githubusercontent.com/3166436/36871343-35e833ac-1d5f-11e8-98ea-83460a92fd0c.png)

**Comment by londumas** [comment]
Here is the same distribution but for the off-diagonal elements of the un-smoothed correlation matrix:

![capture d ecran de 2018-03-01 14-57-38](https://user-images.githubusercontent.com/3166436/36871950-fe677fe4-1d60-11e8-812a-a9aaaa3521aa.png)

**Comment by londumas** [comment]
Looks like it is linked to few sub-sampling, when the correlation matrix has large non-diagonal elements.
