### ISSUE TITLE
Unittest failure

### ISSUE THREAD

**Issue by mblomqvist** [igmhub/picca#351]
The unittest was run in python 2.7 on a topic branch that is up-to-date with master and only has a minor change in fitter2, but stops with the failure
```
======================================================================
FAIL: test_cor (__main__.TestCor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_cor.py", line 74, in test_cor
    self.send_xcf_angl()
  File "test_cor.py", line 612, in send_xcf_angl
    self.compare_fits(path1,path2,"do_xcf_angl.py")
  File "test_cor.py", line 243, in compare_fits
    self.assertTrue(allclose,"{}: Header key is {}, maximum relative difference is {}".format(nameRun,k,diff.max()))
AssertionError: do_xcf_angl.py: Header key is DA, maximum relative difference is 0.00279007921419
```

**Comment by londumas** [comment]
could you do the same test on master?

**Comment by mblomqvist** [comment]
Same failure on master. There are warnings for every code of the type
WARNING: do_xcf_angl.py: Header key is RP, arrays are not exactly equal, using allclose

**Comment by londumas** [comment]
@mblomqvist, what happens if you comment the test of `do_xcf_angl.py`?

**Comment by ngbusca** [comment]
@mblomqvist were the tests passing on your system before?

**Comment by mblomqvist** [comment]
This is the first time I'm running it on my system

**Comment by londumas** [comment]
@mblomqvist, It can be a difference of generation of random numbers.

**Comment by ngbusca** [comment]
@mblomqvist can you confirm that all your package versions correspond to what's listed in the requirements.txt file?

**Comment by mblomqvist** [comment]
I commented out
self.compare_fits(path1,path2,"do_xcf_angl.py")
but the unittest stopped at send_metal_xdmat with a segmentation fault: 11

**Comment by ngbusca** [comment]
@londumas it's possible but a bit unlikely. The tests pass at nersc on python 3, at Utah on python 2, on my mac and on the linux console of travis...

**Comment by ngbusca** [comment]
@mblomqvist that segfault seems like a separate problem...

**Comment by mblomqvist** [comment]
The numbered requirements are scipy 0.17.0 and iminut 1.2 and my laptop fulfils both

**Comment by ngbusca** [comment]
@mblomqvist then your master is not up-to-date:

scipy==0.19.1
numpy==1.13.1
iminuit==1.2
healpy==1.11
fitsio==0.9.11
numba==0.35.0
h5py==2.6.0
future
setuptools==27.2.0

**Comment by mblomqvist** [comment]
Requirements are listed here https://github.com/igmhub/picca

**Comment by ngbusca** [comment]
No, they are listed in the requirements.txt file

**Comment by mblomqvist** [comment]
requirements:

python 2.7
scipy 0.17.0 or later
iminuit 1.2 or later
fitsio
healpy
numba
multiprocessing
configargparse
h5py

**Comment by mblomqvist** [comment]
Then somebody should update README asap or remove it entirely. The current information is misleading.

**Comment by ngbusca** [comment]
@mblomqvist that's a separate issue. Please make sure your packages correspond to the requiremets.txt file and report whether that fixes the unittests.

**Comment by mblomqvist** [comment]
I haven't run python setup.py install because I have picca/py in my PYTHONPATH instead. Does this make a difference?

**Comment by ngbusca** [comment]
No, it shouldn't make a difference. You can always try a PR, what counts is that tests pass on travis.

**Comment by ngbusca** [comment]
by the way, to keep track of this, can you please give the details of the system where you encounter this problem. I'll see if I can reproduce it on my end.

**Comment by mblomqvist** [comment]
The failure was encountered on a MacBook Pro laptop OSX El Capitan 10.11.6 using anaconda python 2.7 environment

**Comment by ngbusca** [comment]
@mblomqvist what's the python version? (X=? in 2.7.X)

**Comment by mblomqvist** [comment]
2.7.13

**Comment by mblomqvist** [comment]
Can I continue development without the unittest for now?

**Comment by londumas** [comment]
@mblomqvist, yes no problem. The unittest are on gitHub now. They are automatic.

**Comment by ngbusca** [comment]
@londumas why is this tagged as a bug?

**Comment by londumas** [comment]
@ngbusca, yes it is a bug, unittest should work everywhere.

**Comment by ngbusca** [comment]
@londumas it should, but we haven't determined why it doesn't, so we can't say it's a bug

**Comment by londumas** [comment]
"accused is innocent until proven guilty" or "accused is guilty until proven innocent" ?
You choose. For code issues I prefer the second.

**Comment by ngbusca** [comment]
A bug is a very specific kind of problem, it means there is a mistake in the code. We haven't determined that.

**Comment by londumas** [comment]
Is this new label better?

**Comment by ngbusca** [comment]
Yes!! Much much better, thank you thank you :^)

**Comment by londumas** [comment]
@mblomqvist, could you send the test on your computer and put here the output of the `self.test_requirements()` method?

**Comment by mblomqvist** [comment]
Run in python3, I get
test_cor.py:312: ResourceWarning: unclosed file <_io.TextIOWrapper name='/Users/mblomqvist/Source/picca/py/picca/../../requirements.txt' mode='r' encoding='UTF-8'>
  for l in open(path,'r'):
WARNING: The local version of healpy: 1.11.0 is different from the required version: 1.11

and the unittest stops with
======================================================================
FAIL: test_cor (__main__.TestCor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_cor.py", line 77, in test_cor
    self.send_xcf_angl()
  File "test_cor.py", line 643, in send_xcf_angl
    self.compare_fits(path1,path2,"do_xcf_angl.py")
  File "test_cor.py", line 250, in compare_fits
    self.assertTrue(allclose,"{}: Header key is {}, maximum relative difference is {}".format(nameRun,k,diff.max()))
AssertionError: False is not true : do_xcf_angl.py: Header key is DA, maximum relative difference is 0.0015988314782741818

**Comment by mblomqvist** [comment]
I ran the unittest in my home directory on the local cluster and it finished without any major issues (only some warnings along the way). It uses python 3.6.3, so I created a python 3.6.4 environment on my laptop to see whether 3.5.4 could be the issue, but the unittest still stopped with the same error as reported above.

**Comment by londumas** [comment]
@mblomqvist, could you retry this on the latest master. It would be nice to close this issue if possible.

**Comment by ngbusca** [comment]
@mblomqvist @londumas go ahead whenever the branch is ready to be merged. I'll restructure things on a later branch as soon as I have time...

**Comment by mblomqvist** [comment]
@ngbusca I think you answered in the wrong thread, but I understand what you mean

**Comment by londumas** [comment]
@mblomqvist, Could you test another time and give the output?
It works for us on a lot of different machines.

**Comment by londumas** [comment]
Closed because no news of this and nobody can reproduce this except one person.
