### ISSUE TITLE
ap, at is applied to the full shape of metals

### ISSUE THREAD

**Issue by ngbusca** [igmhub/picca#353]
Inadvertidly, it seems that the alphas are applied to the full shape of the metal correlation function (there's currently no peak-broadband decomposition for the metal contamination).

**Comment by mblomqvist** [comment]
Good to know. That might explain why I've been getting slightly different results compared to fitter1.

**Comment by londumas** [comment]
@ngbusca, are you sure what you say is true? `py/picca/fitter2/data.py` seems perfect.
The problem might only be in `py/picca/fitter2/chi2.py`

**Comment by ngbusca** [comment]
Well, there isn't an explicit broadand-peak decomposition as there is for the main signal, so yes, I'm sure (which doesn't mean I'm not wrong). I don't know what you mean by perfect.

**Comment by mblomqvist** [comment]
@ngbusca The decomposition is done in the chi2 function of data.py so that should affect the main and metal signals equally, no?

**Comment by ngbusca** [comment]
Yes you are both right, it's correctly implemented. Sorry for the noise!
