### ISSUE TITLE
redshift of parameters for combined fit

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#367]
Currently in `fitter2` there is a `zref` for each input correlation.
- it would be nice to put the input `zref` in the h5py file so the user knows at what redshift the parameters are give.
- At what redshift are the parameters given in the case of two input correlations with different `zref` ? maybe we should move `zref` from the config file to the `chi2` file. Or have this parameters unique in some way.

**Comment by mblomqvist** [comment]
I suggested some time ago that zref should be read from the input power spectrum header. We have not followed up on that yet.

**Comment by ngbusca** [comment]
The way I see it (it might not be what's implemented), the bias, beta, etc. should be given at the redshift of the measurement (call it zeff). We need to read the zref of the fiducial P(k) to know by how much we need to rescale it to zeff (but that's trivial). For parameters that are shared and need to be converted from zeff(measurement 1) to zeff(measurement 2) an assumption on the z evolution of that parameter is required.

**Comment by ngbusca** [comment]
I agree with @londumas that we should propagate the zeff's to the output file.

**Comment by londumas** [comment]
@ngbusca, do you mean that currently the result parameters are given at `zeff`, the redshift of the input power-spectrum?

**Comment by mblomqvist** [comment]
Let's start by agreeing on the names: zref = reference redshift of the fiducial P(k), zeff = effective redshift of the measurement. Currently, fitter2 has no input for zeff (as far as I know).

**Comment by londumas** [comment]
Here is how I see things:
- there should be a zeff (~<z_bins>) for each measure
- there should be a zoutput at which the parameters are given. It could be 0 or zeff if there is only one measure.
- zref (from P(k)) shouldn't be a parameter since it is given in the P(k) file. In the future it could also be exactly zoutput by reading P(k) from a grid in redshift. @mblomqvist, would it be hard to produce such a fits file: P(k,z) for z in [0,10] with dz=0.01 for example?

**Comment by ngbusca** [comment]
@londumas we don't need to generate `P(k)` at different `z`, all we need is the growth factor.

**Comment by ngbusca** [comment]
Here's a plot with the ratio of P(k) at z=2 and P(k) z = 1. Once correcting for the growth rate, the differences are smaller than 0.3%, and only at the largest scales.

![image](https://user-images.githubusercontent.com/4727509/37453746-f7d344c8-2838-11e8-9422-2c03ff5fef0f.png)
