### ISSUE TITLE
Apply Codacy recomendation

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#369]
@ngbusca added picca to a Codacy check.
Let's apply step by step the different recomendation from https://app.codacy.com/app/ngbusca/picca/issues/index

**Comment by londumas** [comment]
It seems that the code in `py/picca/wick.py` is already present in `py/picca/cf.py`.
What is the reason we have the `py/picca/wick.py` file?

**Comment by ngbusca** [comment]
it's a different module doing a different thing. I would remove the duplicated code from cf.py

**Comment by ngbusca** [comment]
@londumas Is this PR work in progress to slowly apply all coadacy recommendations or is it ready?

**Comment by londumas** [comment]
After merging PR https://github.com/igmhub/picca/pull/404, there will only least trivial Codacy recommendations. Some are false: for example the remaining unused imports, or invocation of non-callable.
Some are not very important: example error exception, enumerate builtin, ...
For some it might be important: example unused variable

**Comment by londumas** [comment]
@Cyeche, Codacy says that in `from ROOT import TCanvas, TH1D, TFile, TTree, TProfile2D, TProfile` you don't use `TCanvas` (Unused TCanvas imported from ROOT in bin/do_Pk1D.py). Is it true?

**Comment by londumas** [comment]
@Cyeche, could you have a look at three lines in https://app.codacy.com/app/ngbusca/picca/issues/index about unused variables in `py/picca/Pk1D.py` in patern. Please tell me is it is normal or a bug.
