### ISSUE TITLE
Store cosmological parameters in fiducial P(k) file

### ISSUE THREAD

**Issue by mblomqvist** [igmhub/picca#372]
It would be useful to store the cosmological parameters used for CAMB in the header of the fiducial P(k) fits file. In particular, the value of 'Om' is of key importance.

It is, however, not clear which parameters we want to store. The CAMB ini files are rather long and already available in the 'models' directory, so it seems like overkill to duplicate everything. Would it be enough to store a subset of the parameters? Furthermore, there are derived parameters (e.g. 'rdrag' and 'sigma8') that could be convenient to have readily available.

One more point: parameter names are sometimes different between CAMB and the python version (e.g. 'helium_fraction' and 'YHe'). Names are limited to 8 characters in the header.

**Comment by ngbusca** [comment]
@mblomqvist I agree with all of the above. As you propose, let's keep only those parameters that we need to pass forward to the fitter, and add those that is convenient to have available at analysis time (I don't think YHe is one of them...).

**Comment by mblomqvist** [comment]
'Om' and 'OL' (or 'Ok') will be used by the fitter. 'H0', 'rdrag' and 'sigma8' could be convenient. Please add to the wish list.

**Comment by londumas** [comment]
fixed in store_cosmo_parameters
