### ISSUE TITLE
Om and OL parameters for growth_factor_de

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#375]
Currently when using `growth_factor_de`, the user has to specify `Om` and `OL` as parameters.
It would make more sense to have these parameters read from the power-spectrum and passed in a similar way as `zref`.
If we do such a thing then we could define:
```
self.growth_function = partial(getattr(xi, dic_init['model']['growth function']),
zref = self.zref, Om=Om, OL=OL)
```
What do you think @ngbusca and @mblomqvist?

**Comment by ngbusca** [comment]
@londumas I agree that that's the way it should be implemented...

**Comment by mblomqvist** [comment]
@londumas I agree too

**Comment by londumas** [comment]
Who volunteers to take care of this?

**Comment by mblomqvist** [comment]
@londumas Can't you add it quickly in PR #371 ?

**Comment by londumas** [comment]
@mblomqvist, I can. @ngbusca, are you ok with me adding this correction to the PR 371?

**Comment by ngbusca** [comment]
@londumas sure!

**Comment by mblomqvist** [comment]
Can we close this issue?
