### ISSUE TITLE
Binning effect  

### ISSUE THREAD

**Issue by vserret** [igmhub/picca#376]
For the fit of the cf, the G(k) term of equation (21) (Bautista, 2017) is composed by the product of square of sinc but the Fourier transform of the rectangle function is just sinc. 
Should we erase the squares ?

**Comment by ngbusca** [comment]
I agree with @vserret . @londumas @mblomqvist any objections?

**Comment by londumas** [comment]
Do you mean that the last paragraph of page 11/22 of Bautista et al (https://arxiv.org/pdf/1702.00176.pdf) is wrong?
Could you give the math and the relevant assumptions?

**Comment by vserret** [comment]
The Fourier transform of the rectangle function is sinc and since we are binning on the cf and not on the deltas, so I think we should not have the squares.

**Comment by mblomqvist** [comment]
OK, that sounds reasonable. Was there a reason for using the square in previous analyses? Also, I noticed that fitter1 divided the argument with pi - why?

**Comment by mblomqvist** [comment]
I might have answered my own question: the division by pi is probably because we used the scipy version of sinc.

**Comment by ngbusca** [comment]
@mblomqvist The square is a heritage of the initial implementation which was relative to a smoothing of the delta field. I guess the transition to smoothing the correlation function was done without enough thought. The `pi` has to do with the definition of the `sinc` function of scipy.

**Comment by mblomqvist** [comment]
@ngbusca thanks, yes I recall that the smoothing was initially for the delta field binning. Then it's clear that we should adopt @vserret's suggestion.

**Comment by ngbusca** [comment]
Reworking the full expression, it's actually a bit more complicated than just removing the square. It seems to me that the transverse smoothing effect on `P(k)` can be treated exactly. I'll assign this issue to myself.

**Comment by ngbusca** [comment]
![20180327_123440](https://user-images.githubusercontent.com/4727509/37962483-860e0ea4-31bb-11e8-9faa-d8de42d4424c.jpg)

**Comment by ngbusca** [comment]
Here's my calculation. I'm a bit puzzled that the transverse `sinc` is exact, but I don't see the error...

**Comment by ngbusca** [comment]
In the expressions above there are missing factors of `exp(i k_p r_p)` and `exp(i k_t r_t)`
