### ISSUE TITLE
better name for tracer type

### ISSUE THREAD

**Issue by ngbusca** [igmhub/picca#380]
This issue is to brainstorm possible better names for the `tracer-type` (currently `discrete` for galaxy-like tracers and `continuous` for forest-type tracers).

@mblomqvist proposed `forest` for the latter. I'd personally like a name that makes no reference to the physics involved in whatever we are trying to correlate.

**Comment by mblomqvist** [comment]
Is "skewer" better?

**Comment by londumas** [comment]
`continuous` and `discrete` are used for the moment and do the job very well.
