### ISSUE TITLE
do_co.py is very long

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#391]
The `do_co.py` computation is quite long.
Is there a way to improve the computation time?
@ngbusca, what are the tools you used to asse the computation time performance?

**Comment by ngbusca** [comment]
when you run at NERSC, do you set 

    export MKL_NUM_THREADS=1

either in your environment or your batch script?

Otherwise, I use the `cProfile` which outputs how much time is spent in every function.

**Comment by londumas** [comment]
```
```

**Comment by londumas** [comment]
There is also https://github.com/manodeep/Corrfunc

**Comment by londumas** [comment]
CUTE takes roughly the same time.
