### ISSUE TITLE
Metals in object-forest cross-correlation fits

### ISSUE THREAD

**Issue by mblomqvist** [igmhub/picca#394]
The code data.py checks for metals both 'in tracer1' and 'in tracer2' since a recent update, but object-forest cross-correlations (e.g. QSO-Lya) only have one of the two. Hence, the fit stops with an error during initialisation.

**Comment by londumas** [comment]
It works with the following code.
This way is nice because then we say there is nothing in tracer1.
```
in tracer1 = 
in tracer2 = SiIII(1207)
```

**Comment by londumas** [comment]
This is the current behavior in unittest

**Comment by mblomqvist** [comment]
@londumas thanks for the info, I hadn't considered that. I guess that's a good solution.

**Comment by ngbusca** [comment]
This is a counter intuitive behavior and shoild be fixed.

**Comment by londumas** [comment]
@mblomqvist, could you post the error message?

**Comment by mblomqvist** [comment]
Traceback (most recent call last):
  File "/picca/bin/fitter2", line 7, in <module>
    dic_init = parser.parse_chi2(sys.argv[1])
  File "/picca/py/picca/fitter2/parser.py", line 47, in parse_chi2
    dic_init['data sets']['data'] = [data.data(parse_data(os.path.expandvars(d),zeff,dic_init['fiducial'])) for d in cp.get('data sets','ini files').split()]
  File "/picca/py/picca/fitter2/parser.py", line 47, in <listcomp>
    dic_init['data sets']['data'] = [data.data(parse_data(os.path.expandvars(d),zeff,dic_init['fiducial'])) for d in cp.get('data sets','ini files').split()]
  File "/picca/py/picca/fitter2/data.py", line 142, in __init__
    for m in dic_init['metals']['in tracer1']:
KeyError: 'in tracer1'
