### ISSUE TITLE
z_abs can be higher than z_qso in do_metal_dmat

### ISSUE THREAD

**Issue by vserret** [igmhub/picca#399]
In the computation of do_metal_dmat, we should do a cut in z_qso to avoid to consider pixels with z_abs > z_qso

**Comment by londumas** [comment]
@vserret, could you explain the issue?

**Comment by vserret** [comment]
Let's consider a metal which is localised in the lya forest, for example SiII(1190)(<1200\AA)
When you compute the metal dmat, you will use all the absorption in the Lya forest even the ones in the range [1190,1200] then you compute zabs = lambda_obs/lambda_abs -1 you may have zabs > zqso. 
eg : 
zqso = 3. 
lambda_abs = 1190 = 4790 
lambda_obs = (1+3)*1195 
zabs = 3.02 > zqso 

This effect is very small in the  case of the lya metals but if you want to consider a metal which located in the middle of the forest, this could be a problem. 

![wdm3](https://user-images.githubusercontent.com/22152801/39081192-28e33e44-453d-11e8-9036-4c2bd2b8bd4b.png)

You can see on the image the weights of the metal dmat for correlations LYAxSi. You see than if the wl of the absorber is in the lya forest, wdm is smaller since you are considering less pairs. Again, this effect is very small in this case.

**Comment by londumas** [comment]
@ngbusca, is this fixed?
