### ISSUE TITLE
bug in metal_dmat computation

### ISSUE THREAD

**Issue by vserret** [igmhub/picca#401]
In cf.py : 
l.375 c = sp.bincount(bBam[wAB],weights=rt_abs1_abs2[wAB]*w12[wAB]*zwe21[wAB])
should be 
l.375 c = sp.bincount(bBam[wAB],weights=rt_abs2_abs1[wAB]*w12[wAB]*zwe21[wAB])

**Comment by londumas** [comment]
@ngbusca, is this fixed?

**Comment by ngbusca** [comment]
yes in PR #399
