### ISSUE TITLE
pk.pk_NL is not applied to metals

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#405]
in `py/picca/fitter2/data.py` the non-linear broadening of the BAO peak, `self.pk *= pk.pk_NL`, is not applied to metals. I though it should.
https://arxiv.org/pdf/1504.06656.pdf

**Comment by ngbusca** [comment]
Yes, I agree.

**Comment by londumas** [comment]
Corrected in https://github.com/igmhub/picca/pull/406
