### ISSUE TITLE
`drp` and `sigma_velo` should depend on object

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#415]
`drp` and `sigma_velo` should have a `_<tracer>` prefix. Indeed there are no reason they should be the same for galaxies and quasars for example.
It is very simple to implement. However at some point do we want `fitter2` to adapt to all our
needs? We can simply change locally some aspects for the necessity of a study or a paper and not push these changes to the master. What do you think @ngbusca, @mblomqvist?
```
    res = 1.
    if tracer1['type'] == 'discrete':
        res *= sp.exp( -0.25*(kp*kwargs['sigma_velo_gauss_'+tracer1['name']])**2)
    if tracer2['type'] == 'discrete':
        res *= sp.exp( -0.25*(kp*kwargs['sigma_velo_gauss_'+tracer2['name']])**2)
    return res
```

**Comment by ngbusca** [comment]
@londumas I think you are right that we should have those parameters depend on the tracer. Do you want to PR it?

**Comment by londumas** [comment]
@ngbusca, yes I will take care of this.

**Comment by londumas** [comment]
Fixed
