### ISSUE TITLE
simpler way to find a quasar in do_deltas output

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#423]
Currently there are no maps giving the HDU index for each THING_ID.
It is easy to know in which file the quasar is, from nside in log file and its RA and DEC.
However inside a delta file, we can't know which HDU.
We could have a mapping of HDU index vs. THING_ID in the HDU0.
Curently, we have to loop over all HDU index and thest for the THING_ID

**Comment by ngbusca** [comment]
In fact, we could simply add as extension name the THING_ID. Then you get the hdu directly as h['{}'.format(thing_id)].

**Comment by londumas** [comment]
Very good idea, I didn't think of that. Do you want me to take care of that?
By the way, I ran into this small issue because I looked at some spectra in CoLoRe mocks,
see the two columns of the sixth raw of the first column of plots:
https://desi.lbl.gov/trac/wiki/LymanAlphaWG/Picca_on_CoLoRe.

**Comment by ngbusca** [comment]
Sure! you just need to add the `extname` keyword when writing the delta files in do_deltas....

**Comment by londumas** [comment]
Yes, I already did that in redrock.
Let me do a PR.

**Comment by londumas** [comment]
fixed in PR https://github.com/igmhub/picca/pull/424
