### ISSUE TITLE
desi_convert_transmission_to_delta_files indir is fragile

### ISSUE THREAD

**Issue by ngbusca** [igmhub/picca#432]
When setting the indir argumnet to `transmission*` the code doesn't do anything, since it expects an explicit `.fits` (or `.fits.gz`) at the end. This is a bit counter-intuitive.

We need to find a better signature (e.g. having a keyword `indir` or `infiles` would make it clearer I think).... what do you think @londumas ?

We also need a script that will do the conversion from the command line.

**Comment by londumas** [comment]
I took the same logic as the `from-image`, this is why `transmission*` doesn't work. We can change the logic, I don't care. Why would you need a script that will do the conversion from the command line? Anyone can create such a simple script using subprocess. Do you want us to have one in picca/bin/?
I can create such a script in 5 minutes.

**Comment by ngbusca** [comment]
> I took the same logic as the from-image, this is why transmission* doesn't work. We can change the logic, I don't care.

Yes, I know... and I think the logic is a bit strange there too. I'll take care of it, don't worry

> Anyone can create such a simple script using subprocess. Do you want us to have one in picca/bin/?
I can create such a script in 5 minutes.

Of course! But without a script you have to remember how to call the function, etc. etc. With a script you can always run it with no arguments to get the help... 

But all this is totally secondary, I opened an issue so we don't forget.

**Comment by londumas** [comment]
@ngbusca, I just created two scripts to convert desi data and simulations, I put them into
picca/tutorials/desi/:
https://github.com/igmhub/picca/pull/433

What do you think about doing two scripts:
- one that runs the data, from catalog to delta, to correlations, to fit
- one that runs the simulations
With such scripts it would simplify our work a lot.

**Comment by ngbusca** [comment]
@londumas no really... the signature to call `desi_convert_transmission_to_delta_files` is very strange: the `in-dir` option doesn't support using the desi standard organization of sub-directories. So the user has to guess that he needs to pass the list of files. But that doesn't work either, he has to remember to finish the list of files by `.fits` or `.fits.gz` *and* enclose that between quotes. It's not very clean. 

This is what we should do at some point:

* `--in-dir` this should work if the user gives the path to the `spectra-16` directory (including `spectra-16`
* add an option `--in-files` with the explicit list of transmission files so the user can use command line expansion if he wants to

what do you think?

**Comment by londumas** [comment]
@ngbusca, I think the best is for you to take care of changing this. It would take you 5 minutes to get what you want. Agreed?

**Comment by ngbusca** [comment]
@londumas sure, I'll take care of it!

**Comment by londumas** [comment]
Curently we produce transmission files with:
```
<path_to_picca>/picca/tutorials/desi/do_convert_transmission.py
--object-cat Catalog/zcat_desi_drq.fits
--in-dir "/project/projectdirs/desi/mocks/lya_forest/london/v1.1/*/*/"
--out-dir /global/cscratch1/sd/hdumasde/igmhub/picca/CoLoRe_mocks/v2.1.1__redone__700000/Delta_trans/Delta/
--nspec 100000
```
what would you prefer @ngbusca?

**Comment by ngbusca** [comment]
what would make more sense to me would be to have:
* a `--in-dir` option which points to the full `.../spectra-16` path and uses the desi convention for the subsequent subdirectories
* a `--in-files` option for a list of the transmission files

The code should exit if both the `--in-dir` and `--in-files` options are given

**Comment by londumas** [comment]
fixed in https://github.com/igmhub/picca/pull/437
