### ISSUE TITLE
Should `cos>=1.` be treated as an error?

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#436]
https://github.com/igmhub/picca/blob/beb820697f6160266a6538a49e99eed561dece1e/py/picca/data.py#L36

Currently when we get `cos>=1.`, we set the angle to `theta = 0`.
But this is not totally correct, should we treat `cos>=1.` as an error? Should we add more precision to
`xcart`, `ycart`, `zcart` ?

**Comment by ngbusca** [comment]
@londumas I think we should use something more robust like `atan2` instead of `acos` to avoid this problem.

**Comment by londumas** [comment]
also we can run a more precise calculation for pairs with `cos>=1.`.
At least we should send a `WARNING`.

**Comment by ngbusca** [comment]
at small ddec et dra, the most reliable computation of the space angle is `ang = sqrt(ddec**2 + sin(dec)**2*dra**2)`. We could do that where `ddec` and `dra` are smaller than some threshold value like `1e-5`.

**Comment by londumas** [comment]
Do you mean `ang = sqrt(ddec**2 + cos(dec)**2*dra**2)`? At least that is what you gave me in your email: `ang_small=sp.sqrt((q2.dec-q1.dec)**2+sin(pi/2-q1.dec)**2*(q1.ra-q2.ra)**2)`

**Comment by ngbusca** [comment]
@londumas Yes, indeeed!! Sorry...
