### ISSUE TITLE
Save random seed in fitter2

### ISSUE THREAD

**Issue by mblomqvist** [igmhub/picca#438]
It would be good to save the fast MC random seed (and niterations) in fitter2 for reproducibility.

**Comment by londumas** [comment]
it is set by zero if not given and if it is given, then we know it.
Do you want to store it still?

**Comment by mblomqvist** [comment]
We store parameter limits in scans, and prior limits in fits, so it makes sense to also store the seed for fast MC

**Comment by londumas** [comment]
ok, go-ahead then

**Comment by londumas** [comment]
fixed in "save seed and niterations for fast MC"
