### ISSUE TITLE
Redundant random seed in DLA correction

### ISSUE THREAD

**Issue by mblomqvist** [igmhub/picca#455]
When correcting for DLAs in do_deltas.py, there is an instance of "sp.random.seed(0)" that appears to be redundant.

**Comment by londumas** [comment]
Could you site the line?

**Comment by mblomqvist** [comment]
Line 256 of do_deltas. I can remove it in my latest PR if you want.

**Comment by londumas** [comment]
Why do you think it is redundant? The seed is not set in `py/picca/dla.py`.

**Comment by mblomqvist** [comment]
Ah, OK. I didn't trace it all the way. Sorry about the noise.
