### ISSUE TITLE
Problems using picca on Cori (NERSC)

### ISSUE THREAD

**Issue by andreufont** [igmhub/picca#456]
Do you have instructionsf for installing and using picca on Cori? I tried to follow the instructions online, and found the following problem at running 

python setup.py install --user

It started the installation for a while, but ended with:

/tmp/easy_install-NlhNwO/h5py-2.8.0/h5py/api_compat.h:26:31: fatal error: numpy/arrayobject.h: No such file or directory
 #include "numpy/arrayobject.h"
                               ^
compilation terminated.
error: Setup script exited with error: command 'gcc' failed with exit status 1

**Comment by ngbusca** [comment]
This is a perfect question to kick off the picca users mailing list!!
