### ISSUE TITLE
HCD bias evolution

### ISSUE THREAD

**Issue by mblomqvist** [igmhub/picca#463]
Currently in fitter2, the HCD contribution to the correlation function is evaluated together with the main tracer before scaling with the tracer redshift-evolution factors. This assumes that the HCD bias has the same evolution. It simplifies the computation, but it should be considered whether to move away from this assumption.

**Comment by mblomqvist** [comment]
Note that the maximum variation of the redshift across the data bins is typically <0.1, so the evolution factor varies only by a few per cent.

**Comment by londumas** [comment]
@mblomqvist, are you planing on working on this, or can we close?

**Comment by iprafols** [comment]
@andreicuceu maybe this is something that Vega still does? If so, maybe we can transfer the issue? Otherwise I'd say we close it

**Comment by andreicuceu** [comment]
Yes, we still do this, so we should transfer the issue. I was planning to mention this exact thing at today's meeting haha, so quite a coincidence.
