### ISSUE TITLE
NL correction bug in fitter2

### ISSUE THREAD

**Issue by mblomqvist** [igmhub/picca#468]
Fitter2 has a bug in the NL correction model of Arinyo et al. The model depends on P(k), which is not correctly passed to the function. There are three problems:
1. the quantity "pk" is not defined in the function.
2. P(k) should be evolved by the growth factor from zref to zeff.
3. the function argument "pk_lin" could be either the SB or peak component, but the NL correction should not have this decoupling.

A solution is to define a new function argument to pass P(k) at initialisation using partial.

**Comment by ngbusca** [comment]
@mblomqvist thanks for catching this and working out a fix. Does it require changes in the `.ini` config files for the fitter?

**Comment by mblomqvist** [comment]
@ngbusca No, the ini files are unchanged. PR #469 is ready for merging.

**Comment by mblomqvist** [comment]
Fixed in #469
