### ISSUE TITLE
read_from_spplate assumes that all observation have same fiberid

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#475]
https://github.com/igmhub/picca/blob/550dda84f2702578e783ebf24b3b20acd859de84/py/picca/io.py#L514

when reading `read_from_spplate` using all available observation, there are two errors:
- each observation don't have the same fiberid, when the code assumes it does.
The solution is to read photoPosPlate and get the proper fiberid
- we then use all observation, even if it is marked as bad.
One solution would be to add reading the platequality.txt and read it only if plate is good.

@mblomqvist, @vserret, @solenechabanier, do you use all observation or only the best ones?

Here is all observation before:

![before_bug_fiberid](https://user-images.githubusercontent.com/3166436/46366938-9597f700-c639-11e8-95c3-e6f4195f5c82.png)

Here are all observation after the bug is fixed:

![after_bug_fiberid](https://user-images.githubusercontent.com/3166436/46366941-97fa5100-c639-11e8-87ae-29241c809825.png)

**Comment by mblomqvist** [comment]
@londumas I run analysis on pix files, not internal coadding in picca for spPlates.

**Comment by londumas** [comment]
@mblomqvist or @slosar, could you have a look if ForetFusion is not also doing this mistake

**Comment by ngbusca** [comment]
@londumas you are right, it's a bug! Thanks for reporting. Is there a reason for using spPhotoPlate instead of spAll?

**Comment by ngbusca** [comment]
When I wrote the code I assumed that a plate would have the same plugin for different mjds which is obviously false...

**Comment by londumas** [comment]
They have nothing in common.
spPhotoPlate is similar to spPlate: one per observation. It gives the mapping THING_ID -> Fiber_ID
spAll is a catalog of only "good" observation

@ngbusca, how would you like us to proceed not to use bad plates? Is reading the "platequality.txt" file sound good?

**Comment by londumas** [comment]
@slosar, it seems to be correctly done here.
https://github.com/igmhub/ForetFusion/blob/20cff1851ff424a7d1106c1128c583887213dbb3/ffusion/automatic.py#L69
Do you confirm?

**Comment by ngbusca** [comment]
@londumas @mblomqvist ForetFusion doesn't run into this problem because it uses the reobservation plate,mjd,fid info from DR14Q.

**Comment by londumas** [comment]
Fixed.
