### ISSUE TITLE
Integer division Issue with Python 3 in do_Pk1D

### ISSUE THREAD

**Issue by philippedavid** [igmhub/picca#477]
https://github.com/igmhub/picca/blob/550dda84f2702578e783ebf24b3b20acd859de84/bin/do_Pk1D.py#L204

This line isn't functioning correctly in when do_Pk1D is used with Python 3 as the "/" operator no longer performs integer division if inputs are integers. 

`nb_part_max = (len(d.ll)-first_pixel)/nb_pixel_min`

should be replaced with

`nb_part_max = (len(d.ll)-first_pixel)//nb_pixel_min`

since we want to split the forest into n parts.

**Comment by londumas** [comment]
@philippedavid, could you do a simple PR to fix this?
