### ISSUE TITLE
\overline{F} missing in weight definition

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#48]
In pyLyA/py/pylya/data.py,

the definition of the weight in "def from_forest(cls,f,st,var_lss,eta):"
at lines:

```
iv = f.iv/eta(f.ll)
we = iv * f.co * * 2/(iv * f.co * * 2 * var_lss(f.ll)+1)
```

The f.st(), i.e. the mean transmitted flux fraction seems to be forgotten.

**Comment by londumas** [comment]
same in :  pyLyA/py/pylya/prep_del.py

**Comment by ngbusca** [comment]
Indeed, I'll fix it. Note though that st=1 to better than 1%.

**Comment by londumas** [comment]
Yes it is true.

**Comment by londumas** [comment]
Or actually, it is no more than 4%, as in the plot of 
https://github.com/igmhub/pyLyA/issues/18

**Comment by londumas** [comment]
@ngbusca could you take care of that ?

**Comment by londumas** [comment]
can have a similar effect as issue_168.
Could you fix it @ngbusca  ?

**Comment by ngbusca** [comment]
I agree we need to fix this, but this can't have an effect like issue_168. Here we are just being slightly suboptimal by using weights ~1% wrong. #168 was due to using inconsistent weights, which is quite different.

**Comment by londumas** [comment]
In py/picca/data.py::  from_forest, we should have:
`
iv = f.iv/eta(f.ll)*f.co**2 *st(f.ll))**2

we = iv/(iv*var_lss(f.ll)+1
`

**Comment by ngbusca** [comment]
The iv here is the inverse variance, so I'm reluctant to change that line. It only needs to be corrected by eta.

We should have:
```
iv = iv/eta(f.ll)
mst = st(f.ll)
co = f.co
we = iv*(co*mst)**2/(iv*(co*mst)**2*var_lss(f.ll)+1)
```

**Comment by londumas** [comment]
Agreed.
However, do you think it is the only place where we should apply a change ?
I really would like the code to be bug (even small) free and tested before putting the paper on arXiv.
How could we test if everything is correct ?

**Comment by londumas** [comment]
fixed in https://github.com/igmhub/picca/tree/fix_issue_48

**Comment by londumas** [comment]
fixed
