### ISSUE TITLE
observation should be used only if ZWARN in [0,4]

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#483]
https://github.com/igmhub/picca/blob/19918da811edc1e119cec94e3e1a709f884241fa/py/picca/io.py#L514

Currently we use all observation on good plate.
We should use all observation on good plate with ZWARNING in [0, 2^2, 2^3, 2^4, 2^5, 2^6, ].
The other ZWARNING are very bad. We can also choose to play it safe and use only ZWARNING==0.
@ngbusca, what do you think?

https://www.sdss.org/dr14/algorithms/bitmasks/#ZWARNING

**Comment by ngbusca** [comment]
It's an interesting question. Are there spectra with "catastrophic" ZWARNING that end up in DRQ? 

I wouldn't require ZWARNING==0 since that significantly reduces the completeness of the QSO sample (see e.g. the QuasarNET paper).

**Comment by londumas** [comment]
Yes, I agree let's require ZWARNING to be `[0, 2^2, 2^3, 2^4, 2^5, 2^6, ]`.
What we really don't what is UNPLUGGED, BAD_TARGET, LITTLE_COVERAGE, ...

**Comment by londumas** [comment]
I am preparing a PR

**Comment by londumas** [comment]
Using
```
        for zwarnbit in [0,1,7,8,9]:
            w &= (zwarn_spall&2**zwarnbit)==0
```
we go from 286,211 spectra to 285,123 spectra for Lya forests.

**Comment by ngbusca** [comment]
Could you post a few examples of spectra with "catastrophic" zwarn that are obviously bad spectra?

**Comment by londumas** [comment]
I think it is safe to remove these spectra and it will have no consequences on the measurement.

All objects with BAD_TARGET look like normal quasar, but we can't trust their asymmetry: only 456 observations.

All objects with UNPLUGGED, look like the following: few pixels but with small errors, only 599 observations.

![example](https://user-images.githubusercontent.com/3166436/46771523-2b262d00-ccb1-11e8-9455-91c21ae6ba1e.png)

**Comment by ngbusca** [comment]
I think you mean "astrometry" right? I agree, let's remove them.

**Comment by londumas** [comment]
Yes, I meant astrometry. Firefox correction made me change it.

**Comment by londumas** [comment]
fixed.
