### ISSUE TITLE
coadd z bins

### ISSUE THREAD

**Issue by ngbusca** [igmhub/picca#486]
The current output files from do_cf and do_dmat don't keep the subsamples for some of the fields (e.g. rp, rt, z, dm). This means that when we split the measurement in redshift bins, we can't recombine them into a larger redsfhift bin. 

I propose to change the output to keep the subsample splits for all those fields that are currently missing. What do you think @londumas ?

**Comment by ngbusca** [comment]
The same goes for do_dmat, etc.

**Comment by londumas** [comment]
@ngbusca, we can actually since we have the weight, WE, field. This is enough to recombine rp, rt, z, dm. No?

**Comment by ngbusca** [comment]
Yes, I think you are right. Let me think about it, if it works I'll PR code to coadd the redshift bins.

**Comment by londumas** [comment]
I use that do have a stack for my MgII paper:https://github.com/igmhub/picca/blob/master/tutorials/export_stacked_correlation.py

**Comment by londumas** [comment]
@ngbusca, is that fixed?

**Comment by ngbusca** [comment]
implemented in master
