### ISSUE TITLE
convergence criterion

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#49]
In Bautista el al. we say:

> The procedure is stopped
> after ten iterations, at which point a stability of ∼10^-4 is reached for C and F.

maybe the code could get this difference between the different iterations, or maybe 
the result of C, F, sigma, eta for each iteration.

**Comment by londumas** [comment]
But I doubt that the difference is a good criterion,
I would think that the variance of the difference would be a better test.

**Comment by Waelthus** [comment]
the individual iterations are stored now, so one can compute whatever is needed
