### ISSUE TITLE
Add option in picca_nersc_submit to run over full sky

### ISSUE THREAD

**Issue by andreufont** [igmhub/picca#491]
In order to track down the BAO discrepancy in london/v4.0/quick-2.0/ I generated a new run of quickquasars that uses the full sky (not just 14k sq.deg.) and it uses all quasars (no downsampling of 40%). You can find the run here: /project/projectdirs/desi/mocks/lya_forest/picca/london/v4.0.0/quick-2.1

This means that the dataset is roughly a factor of 7 larger, and that the standard timings in the script are too short. How should we handle this? An option that scales up the time by a given factor? I guess some code will have different scaling than others... Options?

**Comment by ngbusca** [comment]
There are two discussions here that we should split:
 1. feature request: add a tuning of the requested runtime (up and down) to picca_nersc_submit
 2. science: what tests should we run to understand the BAO shift in some of the mocks

1. Is easy to implement, give me a few days
2. Are you entertaining the hypothesis that we saw a three sigma statistical fluctuation? Do we really need to go full sky, burn many CPU hours and wait for many days to exclude something that's already quite unlikely (0.3%)?

**Comment by andreufont** [comment]
I agree on the first distinction. 

I do not agree about the worry about CPU hours. Those are extremely cheap tests, and they might tell us a lot. We are not sure what's going on (specially after the email from Julien saying that the stack from 10 realisations gives the right BAO), so I think we should try multiple approachs to try to understand what's going on.

So yes, given that we have skewers for all sky, 100 / sq.deg., when debuggin the code doesn't make much sense to add a lot of instrumental noise on top and use only 14% of them!

**Comment by londumas** [comment]
@andreufont, I don't think we need to change anything in `picca_nersc_submit`.
The user can easily change manually through a Unix `sed` the computing time.
Would you agree?
Ok to close this issue?

**Comment by andreufont** [comment]
Go ahead!
