### ISSUE TITLE
iminuit v 1.2.0 is *really* required

### ISSUE THREAD

**Issue by ngbusca** [igmhub/picca#492]
The latest version of iminuit (1.3.3) is currently the default installation for conda and pip. Unfortunately, our code is not currently compatible with this latest version. The problem is that the object returned by iminuit.migrad() accept new keys in 1.3.3 (which we use to pass the "SB" variable). While we find a better solution, users should stick to 1.2.0

**Comment by alxogm** [comment]
Hello @ngbusca  I'm trying to compile picca on NERSC (for a student) and I got an error, that I think could be related to this issue. Any idea on how to fix this? 

(I installed picca in my account last week and did not faced this problem) 
Thanks

##############

After running 
python setup.py install we got 

Installed /global/u2/r/rodcn25/.conda/envs/picca_plots/lib/python3.7/site-packages/picca-0.9-py3.7.egg
Processing dependencies for picca==0.9
Searching for iminuit
Reading https://pypi.org/simple/iminuit/
Downloading https://files.pythonhosted.org/packages/c6/e9/1001b530827dd5b460b5404201e598b4cd5da6ff7bc90631c88d903723cb/iminuit-1.3.3.tar.gz#sha256=3235c7e540b278eb55ff851c2a8b299e825db6c770ba15c80140d2fd270ca4ba
Best match: iminuit 1.3.3
Processing iminuit-1.3.3.tar.gz
Writing /tmp/easy_install-h95f9soh/iminuit-1.3.3/setup.cfg
Running iminuit-1.3.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-h95f9soh/iminuit-1.3.3/egg-dist-tmp-trc3u23_
/global/homes/r/rodcn25/.conda/envs/picca_plots/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'test_requires'
  warnings.warn(msg)
warning: no files found matching '*.py' under directory 'tutorial'
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
In file included from /tmp/easy_install-h95f9soh/iminuit-1.3.3/iminuit/PythonFCN.h:9:0,
                 from /tmp/easy_install-h95f9soh/iminuit-1.3.3/iminuit/_libiminuit.cpp:655:
/tmp/easy_install-h95f9soh/iminuit-1.3.3/iminuit/PythonCaller.h:10:10: fatal error: numpy/arrayobject.h: No such file or directory
 #include "numpy/arrayobject.h"
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: Setup script exited with error: command 'gcc' failed with exit status 1

**Comment by ngbusca** [comment]
@alxogm thanks for reporting this. The error you got is different from the one that triggered the issue, and the problem seems to be during the installation of iminuit. I'm surprised that it tried to install iminuit 1.3.3 while the `requirements.txt` file specifies 1.2. I'll look into it.

**Comment by londumas** [comment]
Fixed in PR https://github.com/igmhub/picca/pull/526 by updating to newest release of iminuit

**Comment by matthewfeickert** [comment]
@alxogm @ngbusca Sorry to add discussion (that isn't _directly_ related) to an Issue that is a few months old, but I was wondering if you had any advice RE: dealing with issues similar to @alxogm's. Specifically, https://gist.github.com/matthewfeickert/284cbddc4a60aca2dcda29c354189b35 (in which the above error also shows up).

If not, I won't draw out this Issue, but I thought I'd go ahead and ask.

**Comment by ngbusca** [comment]
@matthewfeickert you seem to be encountering yet a different issue: the original post was related to a change in the type of object the minimization function in iminuit was returning. @alxogm issue seems related to the version of numpy. I'd say yours looks like a problem with your installation of cython. Are you able to install older version of iminuit?

**Comment by matthewfeickert** [comment]
> @matthewfeickert you seem to be encountering yet a different issue: the original post was related to a change in the type of object the minimization function in iminuit was returning.

Sorry for not being more clear. I had just meant that in my Gist if you run the code you will encounter

```
iminuit/PythonCaller.h:10:10: fatal error: numpy/arrayobject.h: No such file or directory
 #include "numpy/arrayobject.h"
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: Setup script exited with error: command 'gcc' failed with exit status 1
```

but I think this is actually due to `iminuit` not properly installing its own dependencies (here `numpy`) and so if I install both `cython` and `numpy` before this goes away.

> I'd say yours looks like a problem with your installation of cython. Are you able to install older version of iminuit?

Excellent question! I hadn't thought to try, but the answer is no (in my Docker image used in the Gist). If I run a modified Gist example (to use `iminuit` `v1.2.0` like in this Issue)

```
#!/usr/bin/env bash

cat /etc/os-release
gcc --version

pip3 install --user --upgrade pip setuptools wheel
pip3 install --user cython numpy
pip3 install --user 'iminuit==1.2'
pip3 install --user pytest

python3 -c "import iminuit; iminuit.test()"
```

then when trying to run it the following still pops up when running the `import iminuit`

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/docker/.local/lib/python3.6/site-packages/iminuit/__init__.py", line 27, in <module>
    from iminuit._libiminuit import *
ImportError: /home/docker/.local/lib/python3.6/site-packages/iminuit/_libiminuit.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTVN10__cxxabiv117__class_type_infoE
```

**Comment by matthewfeickert** [comment]
@alxogm @ngbusca [The issue has been resolved](https://github.com/matthewfeickert/Docker-Python3-Ubuntu/pull/3). In short, there was a conflict of C++ compilers given configuration flag choices at CPython build time. Thanks for your help!
