### ISSUE TITLE
path to P(k)

### ISSUE THREAD

**Issue by mblomqvist** [igmhub/picca#495]
A recent update to picca modified the path specification to load the linear matter power spectrum, e.g. PlanckDR12.fits. What was the benefit of this modification? How does one load a P(k) file that is not in picca?

**Comment by ngbusca** [comment]
In the current incarnation you need to specify e.g. PlanckDR12/PlanckDR12.fits. You can use any other `P(k)` as long as you copy it to the `fitter2/models` (or you use the right `../../../` path). This change was motivated by the `picca_nersc_submit` script which required a non-user dependent path to the model .fits file
