### ISSUE TITLE
Fitter2 does not converge for some parameters with model-xi = cached_xi_kaiser

### ISSUE THREAD

**Issue by julienguy** [igmhub/picca#503]
Not sure if this behavior is expected or not: 

 - The (fitter2) fit does not converge when letting free the par/per binsize and/or Sigma_NL parameters.
 with ```model-xi = cached_xi_kaiser``` in the ini file.

- The fit converges correctly with ```model-xi = xi```.

**Comment by ngbusca** [comment]
This is "normal" in the sense that floating sigma_NL and the binsize are considered "beyond" the kaiser model. At some point that should be extended to automatically cache parameters of any model.
