### ISSUE TITLE
THING_ID is not reliable

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#507]
The same object in different catalogs can have different THING_ID.
For example between DR12Q and DR14Q.
The DRQ catalog team suggest using `OBJID`.

**Comment by ngbusca** [comment]
I'm for moving from THING_ID to something better, but this change needs to be done in the lookout for DESI.

**Comment by iprafols** [comment]
In the newer versions we are using SPECID as a unique identifier inside of picca
