### ISSUE TITLE
switch to .ini files to drive scripts

### ISSUE THREAD

**Issue by ngbusca** [igmhub/picca#508]
Scripts have so many input options that a typical command line call requires several lines. That makes it hard to log and/or share input files with other uses. A solution would be to use the `configparser` (`ConfigParser` in python 2.7) package and use `.ini` files, like `fitter2` does.

**Comment by londumas** [comment]
@ngbusca, I really like the current behavior where we either use command lines or use
```
do_deltas.py `more cmd.ini`
```
where we put all commands into the cmd.ini file.
Then I can send you my cmd.ini file, and I can also easily store the commands.
Why would you like to change this?
