### ISSUE TITLE
remove rejection of same wavelength pairs

### ISSUE THREAD

**Issue by ngbusca** [igmhub/picca#509]
As noted by @julienguy , the rejection of same-plate same-wavelength pairs doesn't totally remove the problem of correlated sky-residuals (since the continuum mixes them to all pixels in the resulting delta-field). To better handle this issue, we should try leaving same-plate same-wavelength pairs in and add a pre-distorsion pure rt broadband to the model. This approach also simplifies many questions related to what to do with reobservations in eboss and what to do in desi.

**Comment by londumas** [comment]
@julienguy and @ngbusca,
I actually looked at what signal is there out of the `lambda_1==lambda_2 (theta)`, and I can't see any. It is compatible with zero.
I am preparing some slides for the meeting.
Basically, the current scheme doesn't even reject all of them because we are stacking all observations but using the PLATE id of the best one to remove same_half_plate.
The solution is either to:
- remove all pairs with lambda_1==lambda_2
- use the flux left of the MgII emission line and the flux right of the MgII emission line to see the shape of the effect, and model it accordingly in fitter2.

**Comment by londumas** [comment]
@ngbusca,
>if you have not detected an excess correlation at l1 != l2 it doesn't mean it's not there.

of course.

>You put an upper limit on the effect at the ~10^-1

No something more like 10^-5. The y axis is multiplied by 10^4, like in the auto DR12 paper. 

I agree with modelling the effect, instead of removing the pairs. It is way better for the coadds.

**Comment by londumas** [comment]
@ngbusca and @julienguy, also this study as to be redone using DR12Q, because DR14Q might have enough catastrophic failure to add a spurious correlation at l1!=l2.
Currently I detect some, very week correlation that could be because of catastrophic failures.

**Comment by londumas** [comment]
@julienguy and @ngbusca,

Here I show the significance of the auto and cross correlation: xi/sigma,
where sigma is computed from sub-sampling.
You can see that only `l1==l2`, is affected at more than 5 sigma level.
This shows that a simple model of a power-law will do the trick: "1 or 2 parameters describing the extra correlation at rp=0"`, as @julienguy said.

auto-correlation of "left of MgII emission line: [260,276] nm"
![auto_mgii11__2d](https://user-images.githubusercontent.com/3166436/49533512-6e99b380-f87c-11e8-8cd5-6724e3dc706a.png)

auto-correlation of "right of MgII emission line: [290,312] nm"
![auto_calib__2d](https://user-images.githubusercontent.com/3166436/49533511-6e99b380-f87c-11e8-8db3-4615ff8b7ac0.png)

cross-correlation
![cross_calib_mgii11__2d](https://user-images.githubusercontent.com/3166436/49533514-6f324a00-f87c-11e8-9971-38a2f5400c9f.png)

**Comment by ngbusca** [comment]
@londumas yes, it should be a *pre-distorsion* polynome (or power-law) on
rt and zero everywhere except at rp==0.

**Comment by londumas** [comment]
Fixed
