### ISSUE TITLE
contribution of bins to the measured parameter

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#525]
The idea is to add @vserret code into `utils.py`. This code allows to compute which bins contribute to the measurement of a given parameter.

**Comment by londumas** [comment]
@vserret, do you have any idea of the time scale on that? Could we have it for DR16?

**Comment by vserret** [comment]
I try to do it before the end of the week

**Comment by londumas** [comment]
Fixed in PR https://github.com/igmhub/picca/pull/601
