### ISSUE TITLE
Understand the fudge parameter in the delta variance 

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#554]
Understand the fudge parameter in the delta variance

The current model for the variance is the following. It is composed of a not well physically motivated "fudge" term.
```
def variance(var,eta,var_lss,fudge):
    return eta*var + var_lss + fudge/var
```
It works very well, in the first plot for data and mocks in the Lya forest, with `lRF in [1040, 1200] A`, where the pixels are with different rebining {`--rebin 1`, `--rebin 3`, `--rebin 10`}, and all with `order=1` continuum. The plot shows a range in lambda_Obs. The second plot gives the evolution of this fudge parameter as a function of observed wavelength.

It is not clear what is causing this issue yet:
1. ~~the effect of the non-Gaussian PDF at high SNR~~ (Not because also there when no Lya in mocks)
2. Contribution in rest-frame of the variance on the continuum
3. ~~Contribution in rest-frame of the quasar redshift errors~~ (No because still there when no redshift error)
4. Systematic difference of continuum as a function of SNR, i.e. as a function of luminosity?
5. ...?

![example_fudge_parameter_lya](https://user-images.githubusercontent.com/3166436/52595727-c23ff480-2e0b-11e9-8dc7-92602a9d1a3f.png)

![evolution_fudge](https://user-images.githubusercontent.com/3166436/52595728-c23ff480-2e0b-11e9-8e1a-17b04402f70b.png)

**Comment by londumas** [comment]
Idea of tests:
- smaller rest-frame wavelength range
- `--order 0`, `--order 2` continuum
- remove redshift errors in mocks
- remove quasar continuum in mocks

**Comment by londumas** [comment]
Here is a comparison between the MgII(11) forest and the Lya forest. This effect is not there in the former.

![data_mgii11_lya](https://user-images.githubusercontent.com/3166436/52599956-58c5e300-2e17-11e9-9cad-372d51d27217.png)

**Comment by londumas** [comment]
Here is the difference between using `--order 0` and `--order 1`: No effect.

![effect_of_order](https://user-images.githubusercontent.com/3166436/52600144-e73a6480-2e17-11e9-98b8-6716de0e0fb9.png)

**Comment by londumas** [comment]
Here is the difference between using smaller rest-frame wavelegth band: `--lambda-rest-min 1040.0 --lambda-rest-max 1200.0` and using `--lambda-rest-min 1095.0 --lambda-rest-max 1165.0`: None.

![smallerlrf](https://user-images.githubusercontent.com/3166436/52602404-c6760d00-2e1f-11e9-9bec-6f4bf99717f2.png)

**Comment by londumas** [comment]
Here is the result when setting all weights to 1 when fitting for the quasar continuum: None.

![weights_1_cont_fit](https://user-images.githubusercontent.com/3166436/52607373-3f329480-2e33-11e9-91c3-c15cd6271f8b.png)

**Comment by londumas** [comment]
Here is the different results using different set of mocks:
- Std
- noFOG, noRedshiftError
- noFOG, noRedshiftError, noLya
Even without Lyman-alpha, we observe a non zero fudge parameter.

![mocks](https://user-images.githubusercontent.com/3166436/52651328-354b7880-2ea9-11e9-9eee-d0a23961a9c6.png)

![mocks_sigmavarlss](https://user-images.githubusercontent.com/3166436/52651599-b276ed80-2ea9-11e9-815a-ff87fe3448e4.png)

![mocks_fudge_parameter](https://user-images.githubusercontent.com/3166436/52651602-b276ed80-2ea9-11e9-8157-96c7418175ba.png)

**Comment by londumas** [comment]
Using `desisim.QSO` instead of `desisim.SIMQSO` does not fix the issue.

![adding_desisim_qso](https://user-images.githubusercontent.com/3166436/52728787-29c58380-2f75-11e9-8fe9-c6acb30c8cf2.png)

**Comment by iprafols** [comment]
We are not using fudge factors anymore
