### ISSUE TITLE
`--metal-alpha` is not a parameter of `picca_metal_xdmat.py`

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#560]
`--metal-alpha` is not a parameter of picca_metal_xdmat.py, when it is for `picca_metal_dmat.py`. @vserret, do you think it should also be added?

**Comment by londumas** [comment]
@vserret, thanks for looking into this. Could you tell me why did you close that?

**Comment by vserret** [comment]
I am working on it

**Comment by londumas** [comment]
@vserret, very good, thanks. Then let's close the ticket once the code is merged.

**Comment by iprafols** [comment]
@vserret , was this ever merged?
