### ISSUE TITLE
Strange behavior when using DLA catalog in CIV forest

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#563]
Strange behavior when using DLA catalog in CIV forest.
@WTSHDY, please describe the feature here.

**Comment by WTSHDY** [comment]
### There is a problem of running do_deltas.py by using '--dla-vac'.

I run two times do_deltas.py within CIII absorbers (1600-1878.7 Angstrom), one is adding  '--dla-vac' to mask the DLAs of the spectra of QSOs, and the other one doesn't add  '--dla-vac' .
Then I run two times do_xcf1d.py for two delta fields.
Finally, There is big difference result between those two in the cross correlation plots ([DLA_CIII_mask.pdf](https://github.com/igmhub/picca/files/2849752/DLA_CIII_mask.pdf)
[DLA_CIII_no-mask.pdf](https://github.com/igmhub/picca/files/2849755/DLA_CIII_no-mask.pdf)).

I just pick one QSO's(thing_id 242548124; plate 5138; mjd 55830; fiberid 20) spectra to plot the continuum flux from two delta fields( delta_***.fits.gz). There is a peak in QSOs continuum flux of the masked DLAs, the corresponding rest frame wavelength is close to peak in the cross correlation plot.
[Thing_ID-242548124-CIII-mask-cont.pdf](https://github.com/igmhub/picca/files/2849781/Thing_ID-242548124-CIII-mask-cont.pdf)
[Thing_ID-242548124-CIII-no-mask-cont.pdf](https://github.com/igmhub/picca/files/2849780/Thing_ID-242548124-CIII-no-mask-cont.pdf)

We know that there should be no big difference between delta field of CIII absorbers with masking DLAs and without masking DLAs. Does anyone know what is going on ?
****
I calculate delta field of CIII absorbers with masking DLAs
-->$HOME/Run_Programs/do_deltas_mask/cat_absorber/CIII/lambda_max/deltas/ 
`do_deltas.py 
 --in-dir $HOME/sdss/ebosswork/eboss/spectro/redux/v5_11_0/ 
--mode spplate 
--out-dir $HOME/Run_Programs/do_deltas_mask/cat_absorber/CIII/lambda_max/deltas/ 
--drq $HOME/sdss/ebosswork/eboss/qso/DR14Q/DR14Q_v3_1.fits 
--dla-vac $HOME/Data/Catalogs/dr14dlasv2/DLA_DR14_v2b.dat 
--flux-calib $HOME/Programs/picca/bin/more_option_do_deltas.py/flux-calib.fits.gz 
--ivar-calib $HOME/Programs/picca/bin/more_option_do_deltas.py/ivar-calib.fits.gz 
--mask-file $HOME/Programs/picca/bin/more_option_do_deltas.py/veto-lines.txt 
--lambda-rest-min 1600.0 
--lambda-rest-max  1878.7 
--lambda-max 11000.0 
--nit 10 
--bi-max 0. 
--vlss-max 1.0 
--eta-min 0.999 
--eta-max 1.001`  

I calculate delta field of CIII absorbers without masking DLAs
-->$HOME/Run_Programs/do_deltas_mask/cat_absorber/CIII/lambda_max/deltas/ 
`do_deltas.py  
 --in-dir $HOME/sdss/ebosswork/eboss/spectro/redux/v5_11_0/ 
--mode spplate 
--out-dir $HOME/Run_Programs/do_deltas_no-mask/cat_absorber/CIII/lambda_max/deltas/ 
--drq $HOME/sdss/ebosswork/eboss/qso/DR14Q/DR14Q_v3_1.fits 
--flux-calib $HOME/Programs/picca/bin/more_option_do_deltas.py/flux-calib.fits.gz 
--ivar-calib $HOME/Programs/picca/bin/more_option_do_deltas.py/ivar-calib.fits.gz 
--mask-file $HOME/Programs/picca/bin/more_option_do_deltas.py/veto-lines.txt 
--lambda-rest-min 1600.0 
--lambda-rest-max  1878.7 
--lambda-max 11000.0 
--nit 10 
--bi-max 0. 
--vlss-max 1.0 
--eta-min 0.999 
--eta-max 1.001  `

I calculate cross correlation of QSO and CIII CIII absorbers with masking DLAs
--> $HOME/Run_Programs/do_xcf1d/cat_DLA/full_obs/full_wr/mask/xcf1d_CIII_nm5000_0.7-3.0.fits.gz  
`do_xcf1d.py
--in-dir $HOME/Run_Programs/do_deltas_mask/delta_fields/full_obs/CIII/deltas/  
--out $HOME/Run_Programs/do_xcf1d/cat_DLA/full_obs/full_wr/mask/xcf1d_CIII_nm5000_0.7-3.0.fits.gz  
--drq $HOME/sdss/ebosswork/eboss/qso/DR14Q/DR14Q_v3_1.fits 
--np 5000  
--wr-min 0.7  
--wr-max `

I calculate cross correlation of QSO and CIII CIII absorbers without masking DLAs
-->$HOME/Run_Programs/do_xcf1d/cat_DLA/full_obs/full_wr/no-mask/xcf1d_CIII_nm5000_0.7-3.0.fits.gz
`do_xcf1d.py
--in-dir $HOME/Run_Programs/do_deltas_mask/delta_fields/full_obs/CIII/deltas/  
--out $HOME/Run_Programs/do_xcf1d/cat_DLA/full_obs/full_wr/mask/xcf1d_CIII_nm5000_0.7-3.0.fits.gz  
--drq $HOME/sdss/ebosswork/eboss/qso/DR14Q/DR14Q_v3_1.fits 
--np 5000  
--wr-min 0.7  
--wr-max 3.0 `

**Comment by londumas** [comment]
@WTSHDY, Thanks for the bug report. Could you plot the mean continuum from do_deltas for the maskand no-mask case? It is in one of the log files.

**Comment by WTSHDY** [comment]
It is not caused by using '--dla-vac' or not. It actually due to using '--use-ivar-as-weight' or not. (Sorry, I forget to put the '--use-ivar-as-weight' into do_deltas.py with masked DLA, actually I done it when I run do_deltas.py).  So the problem is due to using '--use-ivar-as-weight' to cause the difference. It's my mistake that used a wrong input parameter when running do_deltas.py.
