### ISSUE TITLE
read DLA catalog from a fits file

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#571]
In order to read DLA catalogs from DESI, let's only read this catalog from fits file, and add a conversion function in `py/picca/utils.py` to convert the ASCII files to a fits file. I think we should aim for the following header. Would that sound reasonable @alxogm and @solenechabanier?

for data
```
extname = DLACAT
data = RA, DEC, Z, ZQSO, NHI, THING_ID, DLAID, PLATE, MJD, FIBERID 
```

for mocks
```
extname = DLACAT
data = RA, DEC, Z_QSO_NO_RSD, Z_QSO_RSD, Z_DLA_NO_RSD, Z_DLA_RSD,
N_HI_DLA, MOCKID, DLAID
```

**Comment by alxogm** [comment]
Hi @londumas will you use explicitly Z_QSO_NO_RSD, Z_QSO_RSD, Z_DLA_NO_RSD, Z_DLA_RSD at the picca level? The question  is if you need to distinguish between mock and data... I would've think this distinction is only at previous steps, before running picca on mocks, so there is  one DLACAT header that doesn't  know about being mock or data...

**Comment by solenechabanier** [comment]
Yes that's ok for me !

**Comment by londumas** [comment]
fixed
