### ISSUE TITLE
Switch to a linear lambda grid for DESI

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#575]
Swith to a linear lambda grid for DESI.
The fact that we use loglam grid currently has bins effects. See here for example the
evolution of the total variance with observed wavelength. 

![var_LYA](https://user-images.githubusercontent.com/3166436/54609682-134d9480-4a19-11e9-82b3-92dcb32a37eb.png)

**Comment by iprafols** [comment]
This was addressed in the delta_extraction module
