### ISSUE TITLE
Cannot have abs_igm2 if there is no abs_igm in picca_metal_dmat.py

### ISSUE THREAD

**Issue by Andrea-MG** [igmhub/picca#582]
When computing picca_metal_dmat.py for Lya(Lya)xLyb(Lyb) with OVI as abs_igm_2 and none as abs_igm, I get an error in line 133 - Looks like I can't have an absorber in the second forest if there is none in the first.
I lost the exact error message when I lost connection - sorry!

**Comment by londumas** [comment]
@Andrea-MG, could you give here the command line that reproduce the error?

**Comment by Andrea-MG** [comment]
Of course, @londumas 
The command line that I sent is 
`picca_metal_dmat.py --in-dir /global/cscratch1/sd/andreamg/v6/quick-0.1/Picca/Delta_LYA/Delta/ --in-dir2 /global/cscratch1/sd/andreamg/v6/quick-0.1/Picca/Delta_LYB/Delta/ --lambda-abs LYA  --lambda-abs2 LYB --out /global/cscratch1/sd/andreamg/v6/quick-0.1/Picca/Correlations/metal_dmat_LYALYA_LYBLYB.fits.gz --unfold-cf  --np 100 --rp-min -200.0  --rej 0.99 --abs-igm2 OVI\(1038\) OVI\(1032\)`

**Comment by londumas** [comment]
Here is the error message:
```
Traceback (most recent call last):
  File "/global/homes/h/hdumasde/Programs//igmhub/picca/bin/picca_metal_dmat.py", line 133, in <module>
    for m in args.abs_igm:
TypeError: 'NoneType' object is not iterable

```

**Comment by londumas** [comment]
fixed in PR https://github.com/igmhub/picca/pull/585
