### ISSUE TITLE
speed of light is 3e8 for DLA

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#584]
The parameters of the model of DLA absorption are hard codded. For example `c = 3e8 ## speed of light m/s`. This has to be changed in a coherent manner between data catalog, mock catalog and picca.

**Comment by londumas** [comment]
It would be nice to have the dimension and the significance of each parameters going into the computation of DLA. For example what is `b` https://github.com/igmhub/picca/blob/7c1f6c529fc50837c10e21a92f72cc5feac87f30/py/picca/dla.py#L24 Is it the speed of light in decameter/sec as I have been told?

**Comment by WTSHDY** [comment]
I think the dimension in picca/py/picca/dla.py
Line 24 :  b = 30000  <--  m/s 
Line 31 :  b/=1000  <-- km/s
At redshift ~3 observations show the Doppler parameters b to be distributed according to a Gaussian with a mean b between 25 and 30 km/s.

**Comment by iprafols** [comment]
This was fixed aat some point, we are now using `scipy.constants.speed_of_light`
