### ISSUE TITLE
Remove the effect of the grid with finner distortion matrix

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#589]
Remove the effect of the grid with finer distortion matrix

Effect of bin size (Helion): "finer model than data, i.e., rectangular distortion matrix" 
The idea is to estimate the model on bins smaller, maybe 1 Mpc/h is small enough. The development is then to modify the distortion matrix from a matrix 4 Mpc/h x 4 Mpc/h to 4 Mpc/h x 1 Mpc/h
This was done at the code level in PR https://github.com/igmhub/picca/pull/528, but it still need to be understood at the analysis level and computer memory level.

**Comment by Waelthus** [comment]
this can be done in Vega now
