### ISSUE TITLE
Keeping z per healpy pixel

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#59]
The code stores only:
```
    rp = (rps*wes).sum(axis=0)/wes.sum(axis=0)
    rt = (rts*wes).sum(axis=0)/wes.sum(axis=0)
    z = (zs*wes).sum(axis=0)/wes.sum(axis=0)
```

If we were storing these measures as we are for 'WE' and 'DA' we could
easily get the subsampling error for z for example.
This is useful to get the z_eff and its error.

**Comment by londumas** [comment]
fixed in fix_issue_59

**Comment by londumas** [comment]
I would keep all 'RP','RT','Z','NB','WE','DA'
as they are (i.e. one result per healpy pixel)
and then add a general code like prepare_for_fit.py to change this into a .data, .cov, .grid, .dmat
for the fitter.

**Comment by ngbusca** [comment]
The output is fitter ready. Do you mean to baofit format? I have a py to baofit exporter, I can include it in pylya if you think it's useful

**Comment by londumas** [comment]
I don't think it is fitter ready, there is not the distortion matrix and the covariance matrix:
https://gitlab.in2p3.fr/ngbusca/pyLyA/blob/master/fit/py/data.py

I don't mean for baofit.
I just mean that it could be useful to keep all the information of  'RP','RT','Z','NB','WE','DA',
for example for the error on z_eff.
but if we do then we have to convert this file for the fitter.

**Comment by londumas** [comment]
obviously I don't say it is esential to have the error of z_eff, but it can be useful

**Comment by ngbusca** [comment]
The export script calculates the covariance and produces a files with the data, the distorsion, etc. that can be fed to the fitter.

N

**Comment by londumas** [comment]
ok. for that.
but do you agree that we can't get the error on the z_eff ?
We could save both "zs" and "z" and then it is ok.

**Comment by ngbusca** [comment]
You have the error on z_eff from the histogram already. In any case, not that z_eff is not a well defined number, so it's not very meaningful to try to assign it a very precise error (it will be easier to discuss this offline)

**Comment by londumas** [comment]
ok for offline

**Comment by ngbusca** [comment]
@londumas can we close this issue?

**Comment by londumas** [comment]
Why not keep z per healpy pixel? It would help get the error correctly.
