### ISSUE TITLE
Add option to fit (ap,at) on the fulll shape of the correlation

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#598]
Add option to fit (ap,at) on the fulll shape of the correlation

**Comment by londumas** [comment]
Done in the following branch: https://github.com/igmhub/picca/tree/full-shape
I don't think we want to merge this, however it is useful to test how biased the BAO parameters can be in a full shape measurement, how correlated with other parameters and how better the error could be.

```
noMet+noHCD model
 ||                      || \alpha_{\parallel}   || \alpha_{\perp}        || 
 || cf-z-0-10            || 1.015 +/- 0.023      || 0.981 +/- 0.035       || 1838.41 / (1590-6),  p = 8.2e-0600 || 
 || cf-z-0-10+fullShape  || 0.788 +/- 0.024      || 0.750 +/- 0.022       || 1765.75 / (1590-6),  p = 0.00089 ||
 || xcf-z-0-10           || 1.067 +/- 0.035      || 0.927 +/- 0.041       || 3208.73 / (3180-6),  p = 0.33 || 
 || xcf-z-0-10+fullShape || 1.016 +/- 0.021      || 1.018 +/- 0.026       || 3212.05 / (3180-6),  p = 0.31 ||


Full model
||                      || \alpha_{\parallel}   || \alpha_{\perp}       ||  ||
|| cf-z-0-10            || 1.024 +/- 0.027      || 0.972 +/- 0.036      || 1604.02 / (1590-13),  p = 0.31 || 
|| cf-z-0-10+fullShape  || 0.993 +/- 0.016      || 1.003 +/- 0.021      || 1604.68 / (1590-13),  p = 0.31 || 
|| xcf-z-0-10           || 1.070 +/- 0.035      || 0.924 +/- 0.041      || 3189.16 / (3180-10),  p = 0.40 || 
|| xcf-z-0-10+fullShape || 1.014 +/- 0.021      || 1.032 +/- 0.027      || 3192.10 / (3180-10),  p = 0.39 ||
```

![cf_z_0_10_w0_0 95_w1_1 0](https://user-images.githubusercontent.com/3166436/55643098-8aac5380-578f-11e9-971c-21f60c4b098a.png)
![cf_z_0_10_w0_0 8_w1_0 95](https://user-images.githubusercontent.com/3166436/55643099-8aac5380-578f-11e9-8102-1db0769f1ba3.png)
![cf_z_0_10_w0_0 5_w1_0 8](https://user-images.githubusercontent.com/3166436/55643100-8b44ea00-578f-11e9-85de-7d3c08e12c5a.png)
![cf_z_0_10_w0_0 0_w1_0 5](https://user-images.githubusercontent.com/3166436/55643101-8b44ea00-578f-11e9-91aa-36189ac9c53b.png)

![xcf_z_0_10_w0_0 95_w1_1 0](https://user-images.githubusercontent.com/3166436/55643102-8b44ea00-578f-11e9-924c-bcc57373435b.png)
![xcf_z_0_10_w0_0 8_w1_0 95](https://user-images.githubusercontent.com/3166436/55643103-8b44ea00-578f-11e9-8aef-e96200dc81f4.png)
![xcf_z_0_10_w0_0 5_w1_0 8](https://user-images.githubusercontent.com/3166436/55643104-8b44ea00-578f-11e9-8fc6-9a91138ac2e6.png)
![xcf_z_0_10_w0_0 0_w1_0 5](https://user-images.githubusercontent.com/3166436/55643105-8b44ea00-578f-11e9-8987-3411c3e690fc.png)

**Comment by slosar** [comment]
This is extremely useful, thanks a ton.
But what is the difference between the first set of numbers and the second set of numbers? Is one of those on the mocks?

**Comment by londumas** [comment]
It is auto, cf, and cross, xcf

Le lun. 8 avr. 2019 à 06:38, Anže Slosar <notifications@github.com> a
écrit :

**Comment by ngbusca** [comment]
Hi guys, this looks great! I'm not sure though about what the alphas are for full shape. For BAO it's clear they are DH/rs and DM/rs, but for for full shape?

**Comment by slosar** [comment]
Nico, I think that if you let Omega_m and ns (to main parameters that control the shape of linear matter ps) vary, then for fullshale+nobao it would be just DH and DM. Because if you assume your model is right, then only the correct scaling will allow you to explain the observed data. I think it is pretty interesting as there is lots of information in the broadband and our model seem to be good enough to explaining (despite Jim Rich keeping on harping about easy vs hard on the eye)

**Comment by ngbusca** [comment]
@slosar (I'm not arguing against at all!) I just worry that people would just add `--full-shape` and forget that the interpretation of the `alphas` is totally different `;^)`
(these threads are Jim-safe: it is easier for a camel will go through a needle's eye than for Rich to enter the kingdom of github)

**Comment by londumas** [comment]
As I said at the top, I don't think we should merge this branch. It is to
dangerous for beginners. The cosmology wrap up paper guys told me to see
the effect of full shape analysis, so I did.

Le lun. 8 avr. 2019 à 22:17, Nicolas Busca <notifications@github.com> a
écrit :

**Comment by ngbusca** [comment]
@londumas do you need to be that extreme? At the same time, the option might become useful in the future... what about printing a warning message on the screen (`WARNING!!!: you are fitting ap,at on the full shape, remember that they won't give you DH/rs and DM/rs, you'd better know what you are doing!`)
Up to you...

**Comment by londumas** [comment]
@ngbusca, ok works for me. What about the following?
```
WARNING!!!: Sailor you are reaching unexplored territories, it is at your own risk.
```

**Comment by ngbusca** [comment]
@londumas that's really good!! I'd add a phrase reminding why though `;-)`

**Comment by londumas** [comment]
@ngbusca, Yes I wrote that:
`print('WARNING!!!: Using full-shape fit to the correlation function. Sailor you are reaching unexplored territories, precede at your own risk.')`

**Comment by slosar** [comment]
Well done! :)

**Comment by londumas** [comment]
Fixed in PR https://github.com/igmhub/picca/pull/602
