### ISSUE TITLE
New covariance smoother

### ISSUE THREAD

**Issue by vserret** [igmhub/picca#600]
We had two problems with the old covariance smoother : 
- The smoothed correlation matrix depended on rp 
- The cov for lya(lya)xlya(lyb) was not > 0 
Jim has found a new way of doing the smoothing which involves the Wick T123 covariance matrix. 
This should be implemented as an option in export.py.

**Comment by londumas** [comment]
Fixed in https://github.com/igmhub/picca/pull/604

**Comment by londumas** [comment]
Can be fixed by using a wider definition of the Lyb region. For example [86,102], testing with [92,102].

**Comment by londumas** [comment]
merged and fixed.
