### ISSUE TITLE
all energy in computation of distance

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#605]
The comoving distance from PICCA and from CAMB, using the DR12 config file are a bit different, as high as `ratio(z=3) = 0.0002`, `difference(z=3) = -0.9 Mpc/h`. This can be linked to the other energy component: radiation, neutrino, ...
It is not an issue at our level of precision but might be important at some point when DESI comes.

![dist_comoving](https://user-images.githubusercontent.com/3166436/56003118-6fa37d00-5c82-11e9-87a9-6cc34341bcf3.png)

![minus](https://user-images.githubusercontent.com/3166436/56003116-6fa37d00-5c82-11e9-9642-5f6b261ec86b.png)

![ratio](https://user-images.githubusercontent.com/3166436/56003117-6fa37d00-5c82-11e9-826c-61573ba5c153.png)

```
def test_compute_distance():

    h = 0.6731
    om = 0.314569514863487

    pars = camb.read_ini(os.path.expandvars('$HOME/Programs/igmhub/picca/py/picca/fitter2/models/PlanckDR16/PlanckDR16.ini'))
    results = camb.get_background(pars)

    z = sp.linspace(0.,4.,100)
    r1 = results.comoving_radial_distance(z)*h
    cosmo = picca.constants.cosmo(om)
    r2 = cosmo.r_comoving(z)

    plt.plot(z,r1,label='CAMB')
    plt.plot(z,r2,label='picca')
    plt.xlabel('z')
    plt.ylabel('r [Mpc/h]')
    plt.legend()
    plt.grid()
    plt.show()

    plt.plot(z,r1/r2,label='CAMB/picca')
    plt.xlabel('z')
    plt.ylabel('r [Mpc/h]')
    plt.legend()
    plt.grid()
    plt.show()

    plt.plot(z,r1-r2,label='CAMB-picca')
    plt.xlabel('z')
    plt.ylabel('r [Mpc/h]')
    plt.legend()
    plt.grid()
    plt.show()

    return
```

**Comment by ngbusca** [comment]
I think most comes from radiation, which is not inclided in picca's formulae. But remember that what matters is not the distance but distance differences. The effect on distance differences should be much smaller.

**Comment by londumas** [comment]
Fixed in PR https://github.com/igmhub/picca/pull/603

![devide](https://user-images.githubusercontent.com/3166436/56304484-6e97a300-60fb-11e9-8d94-70bbe29dc87e.png)
![minus](https://user-images.githubusercontent.com/3166436/56304483-6e97a300-60fb-11e9-87bf-d72d7018a750.png)

**Comment by londumas** [comment]
Fixed in https://github.com/igmhub/picca/pull/603
