### ISSUE TITLE
DLA implemtentation is different than in Rutten 2003

### ISSUE THREAD

**Issue by echaussidon** [igmhub/picca#607]
** I think there is a mistake in py/picca/dla.py line 28 : `u = (c/b)*(lam_lya/lrf-1)` should be replaced by `u = (c/b)*(lrf/lam_lya-1)` according to Rutten 2003 3.3.3 ([http://www.staff.science.uu.nl/~rutte101/rrweb/rjr-edu/coursenotes/rutten_rtsa_notes_2003.pdf](url)). 

** Moreover I don't really understand the calculation of the Voigt function in the same file which looks like a Lorentz function --> why we didn't use a real Voigt fonction which exist in Scipy ?  

I propose : 

```
from scipy.special import wofz

def voigt(x, sigma, gamma):
    return np.real(wofz((x + 1j*gamma)/(sigma*np.sqrt(2))))

def tau(lamb, z, N_hi):
    lamb_rf = lamb/(1+z)
    e = 1.6021e-19 #C
    epsilon0 = 8.8541e-12 #C^2.s^2.kg^-1.m^-3
    f = 0.4164
    mp = 1.6726e-27 #kg
    me = 9.109e-31 #kg
    c = 2.9979e8 #m.s^-1
    k = 1.3806e-23 #m^2.kg.s^-2.K-1
    T = 1e4 #K
    gamma = 6.265e8 #s^-1
    lamb_alpha = 1215.67 #A
    Deltat_lamb = lamb_alpha/c*np.sqrt(2*k*T/mp) #A

    a = gamma/(4*np.pi*Deltat_lamb)*lamb_alpha**2/c*1e-10 #il faut etre sans unite
    u = (lamb_rf - lamb_alpha)/Deltat_lamb
    H = voigt(u, np.sqrt(1/2), a)

    absorb = np.sqrt(np.pi)*e**2*f*lamb_alpha**2*1e-10/(4*np.pi*epsilon0*me*c**2*Deltat_lamb)*H
    #10^N_hi en cm^-2 et absorb en m^2
    return 10**N_hi*1e4*absorb
```

[rutten_rtsa_notes_2003 (glissé(e)s).pdf](https://github.com/igmhub/picca/files/3095711/rutten_rtsa_notes_2003.glisse.e.s.pdf)

**Comment by londumas** [comment]
@echaussidon, could you plot the difference between the current code and your new implementation for the lya and Lyb absorption by the DLA? The plot you send me this morning would do to start.

**Comment by londumas** [comment]
Related in a way to issue https://github.com/igmhub/picca/issues/584

**Comment by echaussidon** [comment]
![symmetry](https://user-images.githubusercontent.com/47702632/56393374-16d76580-61e9-11e9-84bc-81c975170ce0.png)
![comparaison_la](https://user-images.githubusercontent.com/47702632/56393375-16d76580-61e9-11e9-9533-5955d8f7bdd6.png)
![comparaison_lb](https://user-images.githubusercontent.com/47702632/56393377-16d76580-61e9-11e9-8386-1a420cb0c3fd.png)
![Comparaison_Moi_picca](https://user-images.githubusercontent.com/47702632/56393378-16d76580-61e9-11e9-8b8a-29b52a72df2f.png)

**Comment by londumas** [comment]
@echaussidon, could you give a description of each of your plots?

**Comment by echaussidon** [comment]
So picca code produce a non-symmetric function is due to the line 28 : 
![Figure_1](https://user-images.githubusercontent.com/47702632/56393434-42f2e680-61e9-11e9-94f9-ec4ecc0f5c4a.png)

the orange curve is the current line and the blue curve is mine

**Comment by londumas** [comment]
@echaussidon, thanks for that. Could you add x axis and y axis or describe what they are?

**Comment by echaussidon** [comment]
yes sure I put the wrong figure ..

**Comment by echaussidon** [comment]
and I describe my figure below

**Comment by echaussidon** [comment]
So : 

	** figure 1 : test of symmetry : we plot the transmittance for lyman_alpha minus its symmetric relative to the expected central value 

	**figure 2 : transmittance for the two codes for lyman_alpha : my code in blue and picca in orange 

	**figure 3 : transmittance for the two codes for lyman_beta : my code in blue and picca in orange 

	**figure 4 : 2+3
 
	**figure 5 : the reason of the non-symmetry —> due to line 28, we plot in orange : `u = (c/b)*(lam_lya/lrf-1)` and in blue :  `u = (c/b)*(lrf/lam_lya-1)`

**Comment by echaussidon** [comment]
Edit figure 5: 

![Figure_1](https://user-images.githubusercontent.com/47702632/56394273-a1b95f80-61eb-11e9-88bc-ad4000deab86.png)

**Comment by londumas** [comment]
@echaussidon, thank you for all the work. Could you:
 - look at how it is done in desisim: https://github.com/desihub/desisim/blob/master/py/desisim/dla.py ?
 - plot for a high SNR data and mock the flux and the computed transmission in picca and in your code?
I think you can also prepare a branch with your changes, and we can test their effect. Anyway it does not seem to be drastic. Maybe it will have an effect on computing time using the new Voight function, but it should be minor.

**Comment by ngbusca** [comment]
@londumas @echaussidon If you look at [this line]( 

* https://github.com/igmhub/picca/blob/7c1f6c529fc50837c10e21a92f72cc5feac87f30/py/picca/dla.py#L60) you will see that the profile is exactly a voigt profile (recall that `y` is gaussianly distributed).
* this function has to match what was used for the DLA finder. I recall seeing a difference between Rutten et al and Pasquier implementation, and it made sense at the time. I think Rutten shifts the DLA to the rest frame while we want it in observed frame (or something like that).

**Comment by julienguy** [comment]
I think the issue is whether the random variable u is propto a frequency or a wavelength.
 - the master version of picca uses frequency: https://github.com/igmhub/picca/blob/7c1f6c529fc50837c10e21a92f72cc5feac87f30/py/picca/dla.py#L28
 - same for desisim https://github.com/desihub/desisim/blob/38edac4da5dab7f05cd7fd44cb0737a35cf9019d/py/desisim/dla.py#L144
( in rutten_rtsa_notes_2003.pdf eq. 3.68-3.70 , he suggest both u proto frequency and u propto wavelength , which I find surprising ...
 - physically, I would think the distribution should be symmetric in velocities dv/c so the distribution should by symmetric in wavelength, not frequency.

**Comment by ngbusca** [comment]
@julienguy do you agree that we should use whatever it was used for the DLA finder?

**Comment by echaussidon** [comment]
@ngbusca I agree with the calculation of the void function line 60!
But I don't understand why it is more robust or efficient than the Scipy version because we need to simulate 1000 random number against use a tabulation value on the other way.

Otherwise, I compare the implementation with Pasquier code that @londumas transferred me, here it's implementation  : 

`a = double( lambdao*1.d-10 *gamma/(4*!pi*b) )
u = double( c/b*(lambda/lambdao-1.0d) )
H = double(voigt(a,u))`

where lambdao = lam_alpha and lambda = lrf in our case, which is not like in picca.

**Comment by ngbusca** [comment]
@echaussidon 

> But I don't understand why it is more robust or efficient than the Scipy version because we need to simulate 1000 random number against use a tabulation value on the other way.

I didn't say more efficient, I said more robust. The implementation of `wofz` switches algorithms depending on the absolute value of the argument, `picca`'s implementation doesn't have this limitation. It might be slower, but it's faaaaar from being a bottleneck.

Regarding the more important issue, I *think* the difference is between switching to the dla rest frame or to the observed frame. But it's worth going over this.

**Comment by Waelthus** [comment]
this is fixed using scipy.constants in #1055
