### ISSUE TITLE
picca_cf.py z-cut options could be made more clear

### ISSUE THREAD

**Issue by jfarr03** [igmhub/picca#629]
The names of the options when running `picca_cf.py` to make a redshift cut `--z-cut-min` and `--z-cut-max` are not particularly clear at the moment. Equally, the help description could be more clear:

> Use only pairs of forest x object with the mean of the last absorber redshift and the object redshift larger than z-cut-min

If I understand correctly from when @londumas explained to me, these options cut **only** on the redshifts of the QSOs, not at all on the redshift of the pixels in the skewers. 

This could cause confusion as, if I was naively running an autocorrelation with options `--z-cut-min 2.3 --z-cut-max 2.5` without knowing exactly how the options work, I would assume that my `z_eff` would be around 2.4, whereas it is actually much lower than this (~2.05 in my experience).

As such, would renaming the options to `--z-qso-cut-min` and `--z-qso-cut-max` make more sense? Other names could also work of course, but to make sure that the code is as easy as possible for future users to understand, I feel like the current names are not optimal.

**Comment by londumas** [comment]
@jfarr03, I would prefer not to change the name `--z-cut-min` because we would have to change it in a lot of places. Do you want to do a PR with a more proper English explanation of the parameter?
