### ISSUE TITLE
fitter2 cannot save results

### ISSUE THREAD

**Issue by jfarr03** [igmhub/picca#638]
When running fitter2, I get the following error:

```
Traceback (most recent call last):
  File "/global/homes/j/jfarr/Programs/picca/bin/picca_fitter2.py", line 23, in <module>
    chi.export()
  File "/global/homes/j/jfarr/Programs/picca/py/picca/fitter2/chi2.py", line 309, in export
    for item, value in dic_fmin.items():
AttributeError: 'Struct' object has no attribute 'items'
```

This refers to a line in the final stages of the fitter:

```
for item, value in dic_fmin.items():
            g.attrs[item] = value
```

This seems to be fixed by changing the line to:

```
for item, value in dic_fmin.__dict__.items():
            g.attrs[item] = value
``` 

@londumas does this issue occur for you?

**Comment by londumas** [comment]
@jfarr03, I bet it is a iminuit version issue. Are you using the one in the requirements.txt?
You can see that using `pip show iminuit`

**Comment by jfarr03** [comment]
@londumas Yup you're right that seems to be the issue - thanks!
