### ISSUE TITLE
DLA correction for all the Lyman serie

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#64]
We could not only correct for the Lya line but also for the Lyb for the DLA.

Pasquier answered my question and said (in French):

> C'est de la physique atomique de base. La raie depend de N et b ainsi
> que des parametres atomiques (force d'oscillateur, constante de damping
> qui sont fixés.). Rien d'autre. Ta seule inconnue ici en principe serait
> b. Sauf que si N est large, b n'a aucune influence. D'ailleurs, pour
> Lya, a NHI>~19, cela n'a aucune influence (la raie est dampée).
> 
> b depend en principe de temperature et turbulences, mais ici, ce sera
> domine par les turbulences donc si tu prends genre b=50 km/s, c'est ok.
> De toute facon, tu ne verrais une legere difference que pour les petits
> NHI. Sinon, tout est fixé.
> 
> Et bien sur que si vous utiliser la foret Ly-b, faut corriger!
> 
> lambda    fosc      gamma
> 1215.6701 0.416400  6.265E8
> 1025.7223 0.079120  1.897E8
(ref : https://arxiv.org/pdf/1409.6321.pdf , page 6 )

**Comment by londumas** [comment]
Here are articles to start with:
    - eq 1.1 from Irsic et al. 2013 (https://arxiv.org/pdf/1307.3403.pdf) gives the oscillator strength
for all the series
    - other info here: https://arxiv.org/pdf/1306.0181.pdf

**Comment by londumas** [comment]
Maybe more info in Morton 2003 (http://iopscience.iop.org/article/10.1086/377639/pdf)
in table 2.

**Comment by londumas** [comment]
and in table 2 of another Morton et al 2003
(http://cdsads.u-strasbg.fr/cgi-bin/nph-iarticle_query?1991ApJS...77..119M&amp;data_type=PDF_HIGH&amp;whole_paper=YES&amp;type=PRINTER&amp;filetype=.pdf)

**Comment by ngbusca** [comment]
I think here we need input from people doing the lyman-beta analysis @vserret @julienguy

**Comment by londumas** [comment]
Already start doing so, second comment is from an answer from @vserret .

**Comment by vserret** [comment]
I can deal with that

**Comment by londumas** [comment]
@vserret , were are you on that ?
Is it done ?

**Comment by vserret** [comment]
This is done
