### ISSUE TITLE
shuffle_distrib_forests not rearranging pixel objects

### ISSUE THREAD

**Issue by joselotl** [igmhub/picca#651]
The function shuffle_distrib_forests in utils.py, shuffles the angles of the quasars but doesn't move them from their current healpix pixel assignation. As the functions to compute the correlations only search for objects in the corresponding neighboring pixels, this results in the correlations computed using this function having less pairs than they should have.

Here I include  a possible fix, although I suppose there are more elegant solutions.

Josue De Santiago

```

def shuffle_distrib_forests(obj,seed):
    '''Shuffle the distribution of forests by assiging the angular
        positions from another forest

    Args:
        obj (dic): Catalog of forests
        seed (int): seed for the given realization of the shuffle

    Returns:
        obj (dic): Catalog of forest
    '''

    print('INFO: Shuffling the forests angular position with seed {}'.format(seed))

    dic = {}
    lst_p = ['ra','dec','xcart','ycart','zcart','cosdec','thid']
    dic['pix'] = []
    for p in lst_p:
        dic[p] = []

    for pix, oss in obj.items():
        for o in oss:
            dic['pix'].append(pix)
            for p in lst_p:
                dic[p].append(getattr(o, p))

    sp.random.seed(seed)
    idx = sp.arange(len(dic['ra']))
    sp.random.shuffle(idx)

    i = 0
    data_shuffled = {}
    for oss in obj.values():
        for o in oss:
            for p in lst_p:
                setattr(o,p,dic[p][idx[i]])
            if not dic['pix'][idx[i]] in data_shuffled:
                data_shuffled[dic['pix'][idx[i]]]=[]
            data_shuffled[dic['pix'][idx[i]]].append(o)
            i += 1

    return data_shuffled
```

**Comment by londumas** [comment]
@joselotl, nice catch! Sorry I made that bug, let me correct it.

**Comment by londumas** [comment]
@joselotl, I think the simplest way is to reassign delta, weight, ... instead of the angular distribution. Would you agree?

**Comment by londumas** [comment]
@joselotl, fixed in https://github.com/igmhub/picca/pull/652. Could you test it and tell me if it is ok?

**Comment by joselotl** [comment]
It now works for me. Thank you! I didn't consider reassigning the deltas, I agree that it would have been easier

**Comment by londumas** [comment]
Let's close it once the PR is merged. THanks for the work.

**Comment by joselotl** [comment]
Ok, sorry. Should I comment in the fix?

**Comment by londumas** [comment]
@joselotl, I just added you to igmhub, can you tell me when you received the invite? Once it is done, I will ask you to do a review of the PR.

**Comment by joselotl** [comment]
I already recieved it

**Comment by londumas** [comment]
@joselotl, thanks for catching this issue.
