### ISSUE TITLE
NB binning is not correct in CO

### ISSUE THREAD

**Issue by TEtourneau** [igmhub/picca#656]
I think that the binning of the field 'NB' in exported co is not correct.
Here is 2 plots showing the correlation function (DA) and the number of pairs (NB) vs (rt, rp):
![Screen Shot 2019-07-01 at 3 14 00 PM](https://user-images.githubusercontent.com/36950825/60439709-8d460a00-9c13-11e9-94fd-7e82a8001eee.png)
![Screen Shot 2019-07-01 at 3 18 41 PM](https://user-images.githubusercontent.com/36950825/60439710-8d460a00-9c13-11e9-8b78-38d2dd1cd66e.png)

The axis show the bin number (4 Mpc/h wide).
The plots are done using this file:
/global/cscratch1/sd/tetourne/Out/v4.5.0_6/CO/Correlations/e_co_QSO.fits 

As we can see, the maximum of the correlation function is at r = 0.
But the maximum of number of pairs is not for the largest r but for rp = 0 and rt = 200 Mpc/h.

I think it is just an issue of bin order.

**Comment by londumas** [comment]
@TEtourneau, could you give the different code you ran o export and do the plots?

**Comment by TEtourneau** [comment]
Here are the commands I used to produce the correlation function of QSO:
`Running do_co.py
DD:
picca_co.py --drq Out/v4.5.0_6/CO/Catalog/QSO_D_850000.fits --out Out/v4.5.0_6/CO/Correlations/QSO_DD.fits.gz --type-corr DD --rp-max 200 --rt-max 200 --rp-min 0 --nt 50 --np 50 --z-cut-min 2.1 --z-cut-
max 2.5 --nproc 64 --z-ref 2.27
RR:
picca_co.py --drq Out/v4.5.0_6/CO/Catalog/QSO_R_850000.fits --out Out/v4.5.0_6/CO/Correlations/QSO_RR.fits.gz --type-corr RR --rp-max 200 --rt-max 200 --rp-min 0 --nt 50 --np 50 --z-cut-min 2.1 --z-cut-
max 2.5 --nproc 64 --z-ref 2.27
DR:
picca_co.py --drq Out/v4.5.0_6/CO/Catalog/QSO_D_850000.fits --drq2 Out/v4.5.0_6/CO/Catalog/QSO_R_850000.fits --out Out/v4.5.0_6/CO/Correlations/QSO_DR.fits.gz --type-corr DR --rp-max 200 --rt-max 200 --
rp-min 0 --nt 50 --np 50 --z-cut-min 2.1 --z-cut-max 2.5 --nproc 64 --z-ref 2.27
RD:
picca_co.py --drq Out/v4.5.0_6/CO/Catalog/QSO_R_850000.fits --drq2 Out/v4.5.0_6/CO/Catalog/QSO_D_850000.fits --out Out/v4.5.0_6/CO/Correlations/QSO_RD.fits.gz --type-corr DR --rp-max 200 --rt-max 200 --
rp-min 0 --nt 50 --np 50 --z-cut-min 2.1 --z-cut-max 2.5 --nproc 64 --z-ref 2.27
Done. 3746 s

Running export.py
picca_export_co.py --DD-file Out/v4.5.0_6/CO/Correlations/QSO_DD.fits.gz --RR-file Out/v4.5.0_6/CO/Correlations/QSO_RR.fits.gz --RD-file Out/v4.5.0_6/CO/Correlations/QSO_RD.fits.gz --DR-file Out/v4.5.0_
6/CO/Correlations/QSO_DR.fits.gz --out Out/v4.5.0_6/CO/Correlations/e_co_QSO.fits
Done. 3765 s
`

For the plotting, I just do:
'co = fitsio.FITS('Out/v4.5.0_6/CO/Correlations/e_co_QSO.fits')
plt.imshow(co[1].read()['DA'])
plt.imshow(co[1].read()['NB'])

**Comment by londumas** [comment]
@TEtourneau, It is totally normal, the maximum number of pairs is at large scales: both for DD and RR.
However, at large scales DD=RR, when at small scales RR(xi+1) = DD.

**Comment by TEtourneau** [comment]
I'm not sure I understood.
Why is the number of pairs greater at (rt=0, rp=200) than at (200, 200) ?

**Comment by londumas** [comment]
@TEtourneau, could do some plots in 1d: nb(bin index), da(bin index)? Your 2d plots are hard to read: no labels, x and y are in pixels and not mpc/h, the 0 is not at the bottom left...

**Comment by TEtourneau** [comment]
Sorry I did that really quickly.
Here are some more detailed plots:
![Screen Shot 2019-07-02 at 10 10 30 AM](https://user-images.githubusercontent.com/36950825/60495965-2592cc00-9cb2-11e9-8d61-d478013a9e5c.png)
![Screen Shot 2019-07-02 at 10 13 02 AM](https://user-images.githubusercontent.com/36950825/60495966-2592cc00-9cb2-11e9-9057-24c52ae1e189.png)
![Screen Shot 2019-07-02 at 10 18 27 AM](https://user-images.githubusercontent.com/36950825/60496270-c4b7c380-9cb2-11e9-9e16-7b6d5584c891.png)

As you can see, the pair number does not increase with rp.

**Comment by londumas** [comment]
@TEtourneau, why should t increase with rp? See section 4.2.5.5 of my thesis: https://tel.archives-ouvertes.fr/tel-01587743/document
