### ISSUE TITLE
Gaussian smearing term in fitter2 should be squared

### ISSUE THREAD

**Issue by jmarclegoff** [igmhub/picca#657]
In `picca/py/picca/fitter2/pk.py` the Gaussian smearing term is `exp( - k^2 sigma^2 / 2)`. But this is the smearing applied to the field, and I believe that for P(k) this term should be squared, or equivalently, we should remove the division by 2.
In Saclay mocks the Gaussian smearing has `sigma=2.19`, but with the current state of the code, we expect the fit to return `2.19 * sqrt(2) = 3.10 Mpc/h`, which is closer to what we get.

**Comment by londumas** [comment]
@jmarclegoff, thank you for the explanation. @jfarr03 what is the smearing in LyaCoLoRe?

**Comment by londumas** [comment]
@jmarclegoff, could you explain what you mean by "the smearing applied to the field"? Do you apply manually a smeering, or is it applied by the fact the grid is fixed of bin size `2.19 Mpc/h`?

**Comment by jmarclegoff** [comment]
@londumas, the size of the voxel of the Gaussian-random-field boxes is indeed (2.19 Mpc/h)^3 but in addition, when we compute a skewer we make an average over the surrounding 7^3 voxels (i.e. up to +- 3 sigmas) with a Gaussian kernel of the same sigma = 2.19 Mpc/h. So, in principle, we should have both the Gaussian smearing term, exp( - k^2 sigma^2 ), and the sinc^2(k sigma/2) term. But I believe the second term is negligible.

**Comment by londumas** [comment]
@TEtourneau and @jvstermer could you give the best fit results of these two parameters for `eboss-0.0` and `eboss-raw`?

**Comment by jfarr03** [comment]
@londumas CoLoRe has a gaussian smoothing with scale of 2Mpc/h, and then when we add small scale power in LyaCoLoRe there is a Gaussian smoothing of 25km/s (at redshift 0, so equivalent to 2.5Mpc/h I believe), and a top hat sinc smoothing of size 0.25Mpc/h (the size of our small cells)

**Comment by jmarclegoff** [comment]
@jfarr03 I am surprised. If you apply a Gaussian smoothing at the small scale power you are not going to obtain the required amount of small scales, are you?
Or maybe I misunderstood what you meant.

**Comment by jfarr03** [comment]
@jmarclegoff Sorry the gaussian smoothing we apply to the small scale power is with scale 0.25Mpc/h, rather than 2.5Mpc/h, so the same scale as our small cell size. I don't think it makes much difference as we don't tune using those scales

**Comment by julianbautista** [comment]
I guess this was solved by @TEtourneau ?

**Comment by TEtourneau** [comment]
Yes, it was solved in the branch correct_gauss_smoothing

**Comment by julianbautista** [comment]
Cool, closing this.
