### ISSUE TITLE
desi_convert_transmission_to_delta_files cannot read transmission*.fits.gz

### ISSUE THREAD

**Issue by TEtourneau** [igmhub/picca#659]
line 482: gather all transmission files (either .fits or .fits.gz)
but at line 489, the list of files "fi" are transmission*.fits files

**Comment by londumas** [comment]
@TEtourneau, thanks for finding this. Can you do a PR?

**Comment by TEtourneau** [comment]
I'm not sure how to do it to have something compatible both for .fits and .fits.gz

**Comment by londumas** [comment]
fixed in PR https://github.com/igmhub/picca/pull/660, thank you @TEtourneau ?
