### ISSUE TITLE
(bias_eta, beta) are very correlated

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#667]
Currently we fit for `(bias_eta, beta)` for each tracer. These parameters are very correlated. The following plot shows the first ~50 mocks, and the correlation is `~ -0.97`. This impacts the time performances of the fitter, and thus also of our ability to draw enough fastMC and get the likelihood on a fine enough grid. picca devs have to think of reverting to the previous definition of `bias*(1+beta)`. The question is then what do we do for Boolean tracers like quasars.
![bias_vs_beta](https://user-images.githubusercontent.com/3166436/63803581-7ac61500-c8d2-11e9-8364-798371f9ecc1.png)

**Comment by iprafols** [comment]
fixed in vega
