### ISSUE TITLE
Using None with carfullness

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#676]
I learned few weeks ago that the following code is very bad practice in Python.
It is used everywhere in picca. We test if a value is None simply by asking `if variable_name:`.
This is bad because if we have a boolean that is set to None, then the user or the code
can set it to False or True at some point, then the behavior would depend on the value of the now set variable.
The solution is simply to change these tests by `if not variable_name is None`. 
https://github.com/igmhub/picca/blob/74db2871e2a9b1d1eb19b6a48e5edaae148c4189/bin/picca_dmat.py#L144

**Comment by andreufont** [comment]
Thanks Helion, I'll take a look at it.

**Comment by iprafols** [comment]
We have addressed this in the delta_extraction branch, but this still needs to be checked for the cross-correlation

**Comment by iprafols** [comment]
We will be fiixing this in lya2pt
