### ISSUE TITLE
 Mistakes in py/picca/dla.py line 46/47 

### ISSUE THREAD

**Issue by WTSHDY** [igmhub/picca#677]
1) I think there is a mistake in py/picca/dla.py line 46/47 (https://github.com/igmhub/picca/blob/master/py/picca/dla.py): gamma = 0.079  f = 1.897e8 for LyBeta should be replaced by gamma = 1.897e8  f = 0.079 .

2) By the way, gamma and f value maybe different from the website below:
According to  
https://physics.nist.gov/PhysRefData/ASD/lines_form.html
Atomic information for Lyman-alpha :
https://physics.nist.gov/cgi-bin/ASD/lines1.pl?spectra=H+I+&limits_type=0&low_w=1215&upp_w=1216&unit=0&de=0&format=0&line_out=0&en_unit=0&output=0&bibrefs=1&page_size=15&show_obs_wl=1&show_calc_wl=1&unc_out=1&order_out=0&max_low_enrg=&show_av=2&max_upp_enrg=&tsb_value=0&min_str=&A_out=0&f_out=on&loggf_out=on&intens_out=on&max_str=&allowed_out=1&forbid_out=1&min_accur=&min_intens=&conf_out=on&term_out=on&enrg_out=on&J_out=on&g_out=on&submit=Retrieve+Data
for Lya:        f = 4.1641e-01
                    gamma = 4.6986e+08

Atomic information for Lyman-beta :
https://physics.nist.gov/cgi-bin/ASD/lines1.pl?spectra=H+I&limits_type=0&low_w=1025&upp_w=1027&unit=0&de=0&format=0&line_out=0&en_unit=0&output=0&bibrefs=1&page_size=15&show_obs_wl=1&show_calc_wl=1&unc_out=1&order_out=0&max_low_enrg=&show_av=2&max_upp_enrg=&tsb_value=0&min_str=&A_out=0&f_out=on&loggf_out=on&intens_out=on&max_str=&allowed_out=1&forbid_out=1&min_accur=&min_intens=&conf_out=on&term_out=on&enrg_out=on&J_out=on&g_out=on&submit=Retrieve+Data
for Lyb:     f = 7.9142e-02
                  gamma = 5.5751e+07

Cheers!
Li

**Comment by londumas** [comment]
@WTSHDY, thank you for the message. However, I know that @echaussidon and @julienguy worked a lot on being sure that the DLA models were ok, and they concluded that it was. They are even able to reproduce perfectly the absorption added in mocks.
