### ISSUE TITLE
Add example config for FastMC

### ISSUE THREAD

**Issue by andreufont** [igmhub/picca#679]
@alxogm pointed out that the instructions for running FastMC can be more clear. We could add a specific notebook showing how to run it, and use it also to show how to use the forecast option.

**Comment by andreufont** [comment]
We might be able to close this one already, or wait until we add a bit more on the tutorial for the fitter.

**Comment by andreicuceu** [comment]
There is an example chi2 file with FastMC here: https://github.com/igmhub/picca/blob/master/tutorials/fitter2/chi2_example.ini. Also, the fitter2 tutorial (https://github.com/andreicuceu/fitter2_tutorial) contains some example runs with FastMC. More will be added once fitter3 is ready.
