### ISSUE TITLE
Fix warning in forecast of fitter2 

### ISSUE THREAD

**Issue by andreufont** [igmhub/picca#685]
When I run fitter2 I get the following warning: 

```
/global/homes/f/font/.conda/envs/picca_plots/lib/python3.8/site-packages/picca-4.0-py3.8.egg/picca/fitter2/chi2.py:51:
SyntaxWarning: "is not" with a literal. Did you mean "!="?
```

It's seems trivial to fix, but since I know that @andreicuceu is working on this, I thought it was better to leave it for now.

**Comment by londumas** [comment]
Indeed this line has little sense. `!=` would be better.
https://github.com/igmhub/picca/blob/58ab96090a2ca90b851276ad1fbacc3622c82f2b/py/picca/fitter2/chi2.py#L51

**Comment by andreufont** [comment]
Definitely, but I'll leave @andreicuceu implement the change.

**Comment by andreufont** [comment]
@andreicuceu - we can close this issue, right?

Are there other branches / issues that we can also remove? It would be good to do a bit of tidying up.

**Comment by andreufont** [comment]
Hi @andreicuceu - this was fixed, right?

**Comment by andreicuceu** [comment]
This was fixed
