### ISSUE TITLE
Drop support for python2?

### ISSUE THREAD

**Issue by andreufont** [igmhub/picca#688]
Now that python2 is officially abandoned by python, we should stop supporting it in Picca. Do we know of anyone still using Picca from python2?

It is just annoying to keep using "future" functions instead of going full-on python3.

**Comment by iprafols** [comment]
I agree that we should go full-on python 3

**Comment by andreufont** [comment]
@londumas - any reason to keep support for python2? 

Otherwise, after the DR16 paper is accepted, we can drop support for python2. We will have to do it sooner or later!

**Comment by londumas** [comment]
@andreufont, is there a way to just remove the `future` imports and have the code still be both python 2 and python 3 compatible ?

**Comment by andreufont** [comment]
I don't think so... But also, why do we want to keep that compatibility? Do we know of anyone using Picca with python2?
