### ISSUE TITLE
mean_snr in forest always uses Lya line

### ISSUE THREAD

**Issue by iprafols** [igmhub/picca#692]
in file data.py, at the end of __init__ and __add__ functions the mean redshfit of the forest is computed using Lyman alpha line. The usage of Lya is hard-coded so it might produce unexpected measurements for the mean redshift if other absorption lines are used

**Comment by londumas** [comment]
@iprafols, could you give the reference to the line? Are you talking about that one?
https://github.com/igmhub/picca/blob/bd2b51b27957da687ab4d27cfcae6bca7a2d674c/py/picca/data.py#L200
If it is the case, then this is only used by the Pk1D people, I think.
But you are rigth this is unstable programming.

**Comment by iprafols** [comment]
Yes, that one and also a similar occurence at line 243.

**Comment by iprafols** [comment]
This issue will be fixed in the new version of the continuum fitting on branch delta_extraction
