### ISSUE TITLE
adding of a desiminisv mode to compute deltas on miniSV DESI data

### ISSUE THREAD

**Issue by corentinravoux** [igmhub/picca#699]
Change of the io.py routine : adding of a desiminisv mode which gets "coadd-*" spectra sorted by tile and spectrograph number. This is used to generate deltas with the minisv data release.
Change of the picca_deltas.py routine : adding of an argument which controls the minimal cut in SNR when the mode --use-constant-weight is used.

**Comment by andreufont** [comment]
I think this would be very useful @corentinravoux - do you know if the rest of SV will have the same format?

**Comment by londumas** [comment]
@corentinravoux, sound a very good idea.
However, I think a SNR cut is more appropriate at the catalog level, I would rather limit the addition to yet another option to picca_deltas. It is not a lot of work to do this cut in the catalog, or is it?

**Comment by andreufont** [comment]
Hi @corentinravoux , @londumas - I thought I had replied to this, but now I don't see the message? 

My comment was that in my opinion in depends on what catalog are we now using for DESI data. Are you using an "official" DESI project, something provided by the pipeline team with a standard format? Basically, the equivalent to spAll in SDSS. If so, I think it is valuable to keep the code working with that official catalog, and add the SNR cut in Picca just like we do other cuts (BALnicity, redshift range).

However, if the input file is already a home-made catalog, then it makes sense to make the cuts in the code that you use to create your own catalog.

**Comment by corentinravoux** [comment]
Hi all, I removed the SNR cut argument in the picca_deltas.py file. Only the io.py changes are staying.

**Comment by corentinravoux** [comment]
However, a quick comment, the SNR cut is automatically done in the picca_deltas.py routine to a value of 1.0 which is hardcoded. I wanted more low SNR data, that is why I changed this parameter. If the SNR cut is done on the QSO catalog, is it not appropriate to remove this hardcoded cut ?

**Comment by londumas** [comment]
> he SNR cut is automatically done in the picca_deltas.py routine to a value of 1.0 which is hardcoded. 

Could you point us to that piece of code? This should not be the case for BAO extraction. maybe for Pk1d, where things differ by a lot of hardcoded parameters.

**Comment by andreufont** [comment]
Hi @corentinravoux - I believe that code (the one that does not use any weighting) is only used by those using P1D, so I'd encourage you to discuss this with them (Michael / Christophe / Nathalie, I guess). 

I believe that in the short term it might be better to have an option than a hard-coded value, but in the long term the solution might be to have parallel codes to use when ignoring the weighting...

**Comment by corentinravoux** [comment]
Yes it is for the Pk1D analysis Hélion. Yes, ok I will see it with them. For now we can keep it without adding any new option.

**Comment by andreufont** [comment]
Hi @corentinravoux , what is the status of this? Where you able to implement the changes to read mini-sv?

**Comment by Waelthus** [comment]
Added some changes to make this branch Andes compatible, necessary due to switch from coadds between all arms in the files (minisv) compared to not coadding between arms and storing them individually (andes)

**Comment by andreufont** [comment]
That's great, thanks @Waelthus - Do you think we are ready for a pull request? I believe Corentin already started a PR, but it was stoped at some point. If there are problems, we could discuss it at the telecon next week.

**Comment by Waelthus** [comment]
There's now the option of running directly on a list of zbest files instead of a drq (at least for the sake of deltas, not sure if parts of the non-Pk1d analysis still need one). Assuming one wants to only run on ZWARN==0 QSOs currently.
Both features are announced on picca, lets see if somebody encounters problems before a merge.
