### ISSUE TITLE
chi2 table combined_stdFit.ap.at.scan.dat - not recovering readme plot.

### ISSUE THREAD

**Issue by aferte** [igmhub/picca#704]
Hello, 

I am adding the eboss dr14 likelihoods to cosmosis, using the chi2 table combined_stdFit.ap.at.scan.dat in data/Blomqvistetal2019/combined_stdFit. If I understood correctly, first column is alpha_perp, the second is alpha_parallel. As a check I am plotting the chi2 contours from this table and get a plot (see below) with axis switched compared to the plot shown in data/readme.md. Are the axis of the chi2 table inverted or the plot in the readme? 
![chi2_lyacombined](https://user-images.githubusercontent.com/12816116/81112747-fa7d9800-8ed3-11ea-87ae-0ffabfecc747.png)

**Comment by aferte** [comment]
Or I mis-interpreted the column's labels?

**Comment by andreufont** [comment]
Hi @andreicuceu , could you take a look at this? 

@aferte - note that we also have CosmoMC and MontePython modules with the DR14 results, in case that is useful.

**Comment by andreicuceu** [comment]
Hi @aferte, looking at the numbers it looks like the first column is indeed alpha parallel (ap) and the second column is alpha transverse (at). So I think everything should work fine.

**Comment by aferte** [comment]
OK, that makes more sense. Thanks!
