### ISSUE TITLE
Components of correlation function model

### ISSUE THREAD

**Issue by julianbautista** [igmhub/picca#710]
Following a request by Jim Rich, we would like to be able to adapt the fitter so the user is able to study the different components of the model when possible (metals, distortion matrix, etc).

This could be an
- option in picca_fitter2 that would write these components to the h5 file, or
- a modification of fitter2 such that users could use it interactively, and producing plots.

**Comment by julianbautista** [comment]
hi @andreicuceu ! If I understood correctly, this will be part of fitter3 right? 

Do we still want this for fitter2 @iprafols @andreufont ? 
If fitter3 is coming with this feature, I would rather not spend time with this in fitter2.

**Comment by iprafols** [comment]
I guess that depends on how close we are to releasing the fitter3. If we won't have it until a year or so, it might be useful to work on this now. But if we will have it only in a few weeks/months, then I'm not sure it's worth it

**Comment by andreicuceu** [comment]
Fitter3 is a few weeks away max (and can do this already), so I don't think it's worth doing it in fitter2.

**Comment by iprafols** [comment]
I'd  then say we don't include this in fitter 2

**Comment by julianbautista** [comment]
This issue has been addressed by Vega : https://github.com/andreicuceu/Vega
Thanks Andrei!
