### ISSUE TITLE
Turn the pre-release v4.alpha into a formal release v4.dr16

### ISSUE THREAD

**Issue by andreufont** [igmhub/picca#715]
Right now we only have a pre-release for the code used in DR16. Should we wait for the paper to be accepted, before we make it a final release? What would be the benefit of waiting? 
I guess if we were asked to do changes in the paper, and these included re-running something, would we modify v4.alpha instead of working with the master branch, and that's why we don't want to make that a final release yet, just in case? 
If we were to make changes to v4.alpha, how would one do that? It does not show up as a branch, so I'm not quite sure how to branch from it to add new changes...

**Comment by andreufont** [comment]
Hi @londumas , what are your thoughts here? Was your plan to wait for the paper to be accepted, before making it an official release?

**Comment by andreufont** [comment]
More on this discussion, from a conversation with Helion. 

In July 2019, Helion created a tag for Picca, Theodebert-DR16-alpha (also known as v4.alpha), that was supposed to be the stable version of Picca to reproduce the DR16 results. However, this was a "pre-release", not a full release (not sure what the differences are). And more importantly, the README and the data to use the DR16 results are now in the master branch, but not in that release that you created last year.

So how should we proceed?
 - A) Should we tag the current master as the DR16 official release of Picca? Several things have changed in Picca during the last year, but I recently checked that indeed we recover the DR16 results.
 - B) Should we instead make that pre-release (v4.alpha) the official DR16 release? In that case, we should document well that even though the v4 is the official release to reproduce the DR16 results, the actual data files from DR16 are not in that release.

I think we should go with A) and tag the current master as the DR16 official release.

**Comment by andreufont** [comment]
@julianbautista , @iprafols - Note the discussion above. Helion has added the DR16 files to Picca, with a README to reproduce some of the plots. I accepted the PR and merged to master, and I think we are now ready to make the master branch the official DR16 release. 

There are a couple of remaining PRs that could be addressed and merged before making the DR16 release, but I don't think that's necessary. They are not related to DR16, and they should be easily merged with the new master after doing the standardisation merge.

**Comment by londumas** [comment]
> Hi @londumas , what are your thoughts here? Was your plan to wait for the paper to be accepted, before making it an official release?

I had no big plan in mind, I think we can do the release. Do you want me to take care of it ? It is very simple for me to do it.

**Comment by andreufont** [comment]
Yes, it would be great if you could take care of making the DR16 official release from the master branch.

However, do you mind if we wait a couple of days, to see if there is any comment from the others?

**Comment by londumas** [comment]
@andreufont , no problem. I will wait.

**Comment by iprafols** [comment]
We can make a release now with the DR16 and also use it as the tag before standardisation

**Comment by andreufont** [comment]
Great. @londumas , please go ahead and tag the master branch as the final DR16 release. Feel free to choose a French king if you wanted :-p

**Comment by londumas** [comment]
Done: https://github.com/igmhub/picca/releases
