### ISSUE TITLE
Can we simplify the metal matrix?

### ISSUE THREAD

**Issue by andreufont** [igmhub/picca#719]
The computation of the metal matrices are one of the slowest parts of the analysis.

I was always surprised that we needed to be so careful with the metal contaminants, since I would have thought that a much simpler approach would be valid. 

The description of the metal contaminants was described in section 5 of Font-Ribera & Miralda-Escudé (2012, arxiv.org/abs/1205.2018). My understanding is that we need the metal matrix only to take into account that we want predictions for correlation function *bins*, of finite width (both in rt, rp and z). If we had inifinitely fine binning (also in z), then it would be trivial to make a prediction for the metal contamination without the need of the metal matrices. 

The metal matrices that we computed are very simple, mostly zeros except for a diagonal band (sometimes with an offset). This suggests that indeed the reasoning above is true, and a much simpler treatment of the metals should be possible. 

Anyway, food for thought for a future hack session.

**Comment by andreufont** [comment]
@iprafols , @Waelthus - could we ask for a volunteer at the next Picca task force? The metal matrices from all DESI mocks are just ridiculously slow, we should really speed this up.

**Comment by andreufont** [comment]
@calumgordon - just pointing you to this issue in Picca, in case you wanted to tackle this.

**Comment by iprafols** [comment]
This was done in #1040
