### ISSUE TITLE
Update README file

### ISSUE THREAD

**Issue by andreufont** [igmhub/picca#727]
The README file is quite outdated, it still says that it requires python 2.7

**Comment by julianbautista** [comment]
I've updated it. I removed the requirements list because it is under requirements.txt and the installation instructions are clear.
I've added some description as well.

**Comment by iprafols** [comment]
We should merge this to master then

**Comment by julianbautista** [comment]
I modified master directly

**Comment by iprafols** [comment]
ah, ok
