### ISSUE TITLE
picca not compatible with python3.8 in MacOS

### ISSUE THREAD

**Issue by julianbautista** [igmhub/picca#737]
After updating my python version in my mac, picca stopped working. 
The reason is that Python 3.8 on MacOS by default now uses "spawn" instead of "fork" as start method for new processes in multiprocessing. 
Adding `multiprocessing.set_start_method("fork")` in the first line below each `if __name__ == "__main__"` makes it work.
I don't think we need to solve this for MacOS users because most people use unix based systems to run picca, but we better have this documented here.

**Comment by iprafols** [comment]
Does this fix work also for unix? If so, then I would add these changes to master

**Comment by julianbautista** [comment]
unix doesn't need this fix because multiprocessing is implemented differently. But I haven't tested though.

**Comment by andreufont** [comment]
Hi @julianbautista - Some might use picca on a laptop to debug stuff, or run small tests. If it is easy to fix, and it doesn't have any bad side effect, it might still be worth it. Maybe we can ask at the picca telecon, or in an email, whether anyone is using Picca on MacOS.

**Comment by iprafols** [comment]
Note that this is also happening in NERSC with the new version of python

**Comment by iprafols** [comment]
The fix proposed by Julian doesn't seem to work. When running the tests, the subprocess module is used to run the different codes. For the first code, the fix works perfectly. However, for the second code, the system thinks the multiprocessing.set_start_method has already been called, and the code crashes as this function can only be called once. However, if a try/except block is used, then the second code runs with the 'spawn' starting method and therefore crashes. 

I will look at other possible fixes

For some reason, when running the tests the multiprocessing thinks that it has already set the start method for the runs after picca_deltas, and it doesn't do so, resulting in a failure of the successive tests.

**Comment by iprafols** [comment]
I fixed the problem by requiring a specific context for the multiprocessing in each of the files. This should work irrespective of the default context in the different OS.

**Comment by iprafols** [comment]
@julianbautista I belive this is not an issue anymore. Unless you complain shortly, I will close the issue
