### ISSUE TITLE
Rename THING_ID from the DLA catalogue format

### ISSUE THREAD

**Issue by andreufont** [igmhub/picca#738]
When we run picca_deltas, we can provide a DLA catalog to mask them. This file is read in io.read_dlas, and it requires the existance of THING_ID to identify the quasar containing DLAs. 

THING_ID was the SDSS name used to identify quasars, but DESI will use TARGET_ID. We could have our own naming, say PICCA_ID, or QSO_ID, and use that in our input catalogs. An alternative is to have try / except statements in our functions to read files, given that we only expect to have 2/3 surveys, this would not be too much of a hassle.

**Comment by julianbautista** [comment]
I'm doing some changes to picca to be less SDSS dependent. 
Do you want to be able to use, say, and SDSS DLA catalog to mask DESI data? I think the answer is yes for now but not in the future (when we have DLA detectors ran on DESI spectra). Is this right?

**Comment by andreufont** [comment]
I don't think we want to mix SDSS and DESI data, at least at this point. It would be confusing in terms of THING_ID / TEMPLATE_ID, and probably others. 

For now, I'd assume that users will be either doing SDSS analyses, or DESI analyses. 

We can have different functions to read DLA catalogs from SDSS, and functions to read DLA catalogs from DESI (if needed), but after reading the catalog the code shouldn't need to know about where the DLA came from.

**Comment by iprafols** [comment]
This is no longer an issue in the new `picca_delta_extraction.py`. @andreufont unless you complain I will close this issue shortly
