### ISSUE TITLE
Update format of input quasar catalog to be able to work with DESI and SDSS data

### ISSUE THREAD

**Issue by andreufont** [igmhub/picca#739]
The input quasar catalog is read in io.read_drq, and is currently expected to have THING_ID, PLATE, MJD, and other SDSS-based keywords. 

We should modify the code to be able to work with SDSS catalogs (like DR16Q) but also DESI catalogs, that will have different keywords.

**Comment by andreufont** [comment]
Hi @iprafols - could you summarise how this was solved? What are the key changes in input data model?

**Comment by iprafols** [comment]
Hi @andreufont ,
Basically the reading function was modified to have an if statement by which we can read using targetid instead of thing_id. However in the data model we are still using thingid. We have not changed that yet. @Waelthus can correct me if this is not accurate enough
