### ISSUE TITLE
Clarify separation between continuum fitting from correlation function 

### ISSUE THREAD

**Issue by julianbautista** [igmhub/picca#747]
The current situation:
- In the continuum fitting process, spectra are read from different type of files, creates Forest objects which are extensions of the QSO class. Only the metadata in QSO is barely used and none of its functions. 
- In the correlation function process, deltas are read with the Delta class, which extend the Forest class and the QSO class. The metadata and the function get_angle_between() from QSO are used. However, none of the Forest functions are used. 

My suggestion: 
Simplify io.py and data.py in order to make the continuum fitting independent of the correlation function.
- In io.py we can keep all functions that read spectral data from different types of files (spplate, spec, desi, etc).
- In data.py we can have: 
  - one Forest class with its own metadata dictionary, no dependency on QSO class. This would be uniquely used for continuum fitting. There could be a new class Continuum which would implement different continuum models. 
  - one QSO class (or PointSource because it could be DLAs or other discrete tracers) and the read_objects function from io.py. 
  - one Delta class that extends the QSO class (not the Forest one), with the read_deltas() from io.py

**Comment by iprafols** [comment]
I agree we can have the class Forest not extending QSO. I would, however, create also an independent Mask class. Classes inheriting from Mask would have a function `apply_mask`. I would also create another class called ForestCorrection with a method `apply_correction` to implement the different corrections. 

I would also create a class Data and have the different reading modes load and format the data from extending classes 

Here is the proposed class diagram for the continuum fitting bit (i.e. not including the measurement of the correlation function)
![class_diagram](https://user-images.githubusercontent.com/9192975/94679533-8fb87780-0320-11eb-80dc-d6f2fd4987bd.png)

**Comment by iprafols** [comment]
This issue is being addressed by the new continuum fitting version in branch delta_extraction

**Comment by iprafols** [comment]
Update: The delta extraction code has been merged in master for a while now. Before we can fully close this issue, we should refactorize the correlation function computation

**Comment by iprafols** [comment]
will be fully fixed in lya2pt
