### ISSUE TITLE
picca_export_coadd_zint potential issue with finding dmat

### ISSUE THREAD

**Issue by jfarr03** [igmhub/picca#759]
Currently, `picca_export_coadd_zint` finds the distortion matrix for a given input correlation by simply replacing the sub-string "cf" in the path to the correlation with "dmat" (line 51): 

https://github.com/igmhub/picca/blob/53828dc007b580c91504be22b922cc3dcabfabf7/bin/picca_export_coadd_zint.py#L51

This has worked well in the past, but runs into issues when using absolute paths with the new-ish NERSC community file system as its directory is named "cfs". Thus `/global/cfs/cdirs/desi/science/lya/picca_on_mocks/london/v9.0/v9.0.0/eboss-0.0/cf_z_0_10.fits` becomes `/global/dmats/cdirs/desi/science/lya/picca_on_mocks/london/v9.0/v9.0.0/eboss-0.0/dmat_z_0_10.fits`.

This could easily be fixed by separating off the filename before carrying out the replacement, but I wonder whether a more robust system of finding the distortion matrix file might be preferable? 

Also, in #758, I raised the question of whether it is useful to have two scripts -  `picca_export` and `picca_export_coadd_zint` - that have overlapping functionality. If we decide to do away with `picca_export_coadd_zint` then this issue may not be relevant any more.

**Comment by iprafols** [comment]
This was addressed some time ago (too lazy to look for the commit, sorry), but now we don't have the script `picca_export_coadd_zint` anymore.
