### ISSUE TITLE
Weights when coadding distortion matrices

### ISSUE THREAD

**Issue by jfarr03** [igmhub/picca#764]
When coadding correlations and associated distortion matrices from several redshift bins, the distortion matrices are combined in a weighted sum where the weights are taken from the associated correlation:

https://github.com/igmhub/picca/blob/53828dc007b580c91504be22b922cc3dcabfabf7/bin/picca_export_coadd_zint.py#L93

Is there a particular reason for doing this rather than using the weights from the distortion matrix calculation itself? 

I'm currently updating this script as discussed at the telecon on 2nd December, and so can switch to using the dmat weights instead if we would like to.

**Comment by iprafols** [comment]
They should be the same, shouldn't they? If they are the same, then doing it this way optimizes the code. That said, since this is a very fast bit of the code, I guess you can change it to using the dmat weights for more readability

**Comment by jfarr03** [comment]
Statistically yes I guess they should but I don't know if they'd be literally identical? I noticed that there's a comment a few lines below this which seems to be to do with weights (though I'm not sure _exactly_ what it means or where it came from):

https://github.com/igmhub/picca/blob/53828dc007b580c91504be22b922cc3dcabfabf7/bin/picca_export_coadd_zint.py#L95

At any rate, we need to open up both the correlation and dmat files so I think the speed difference would be negligible really?

**Comment by iprafols** [comment]
In that case I'd say to change it to improve readability (but I'd double check that the speed difference is indeed negligible)

**Comment by jfarr03** [comment]
Sure I'm just writing the changes into a branch now and will run some tests to check both that the output is the same and that the speed difference is negligible
