### ISSUE TITLE
args.nspec acts on healpix pixels and not on spec

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#81]
In the code, args.nspec acts on each pixels and not on each spectrum.
So, when args.nspec is low,  the number of spectrum is basically given by:
nb_of_spectrum_in_first_pix

Now that we have nside=8, there is a lot of spectra in pixels and thus args.nspec is kind of bypased

**Comment by ngbusca** [comment]
When you set nspec then the input stops whenever you read more than nspec. So if you had only one input healpix file it will read everything. I don't think it's a problem since nspec is mostly for debugging.

**Comment by londumas** [comment]
It is not a big problem, obviously
indeed nspec is for debuging, so it need to be fast.

**Comment by londumas** [comment]
and for example for do_cf or do_xdmat, the number of nspec is important for the debugging.
