### ISSUE TITLE
iminuit issue

### ISSUE THREAD

**Issue by julienguy** [igmhub/picca#810]
Hi I get the following error when running picca_deltas.py  with picca master.

```
Traceback (most recent call last):
  File "/global/common/software/desi/users/jguy/igmhub/picca/bin/picca_deltas.py", line 1018, in <module>
    main(cmdargs)
  File "/global/common/software/desi/users/jguy/igmhub/picca/bin/picca_deltas.py", line 710, in main
    error_var_lss, error_fudge) = prep_del.compute_var_stats(
  File "/global/common/software/desi/users/jguy/igmhub/picca/py/picca/prep_del.py", line 232, in compute_var_stats
    minimizer = iminuit.Minuit(chi2,
  File "src/iminuit/_libiminuit.pyx", line 568, in iminuit._libiminuit.Minuit.__init__
  File "src/iminuit/_libiminuit.pyx", line 83, in iminuit._libiminuit.check_extra_args
RuntimeError: Cannot understand keyword name. May be a typo?
The parameters are ['eta', 'var_lss', 'fudge']
```

It's certainly due to incompatible versions of iminuit.
I'm able to run simply by commenting out the line `name=("eta", "var_lss", "fudge"),` in the iminuit.Minuit call in `picca/py/picca/prep_del.py`:

```
minimizer = iminuit.Minuit(chi2,
                                   #name=("eta", "var_lss", "fudge"),
                                   eta=1.,
                                   var_lss=0.1,
                                   fudge=1.,
                                   error_eta=0.05,
                                   error_var_lss=0.05,
                                   error_fudge=0.05,
                                   errordef=1.,
                                   print_level=0,
                                   limit_eta=limit_eta,
                                   limit_var_lss=limit_var_lss,
                                   limit_fudge=(0, None))
```

I checked the code still gets the correct outputs with this line commented out:
```
minimizer.values= <ValueView of Minuit at 555556d05a10>
  eta: 1.1046818900327127
  var_lss: 0.017747381456786598
  fudge: 127.07644548684993
 3.561e+00 1.10e+00 1.77e-02 1.27e-05 4.61e+00 8461 
```

**Comment by julienguy** [comment]
I have installed iminuit 1.4.2

**Comment by Waelthus** [comment]
It might be that `name` was only introduced with 1.4.3 (from their changelog: Deprecated    keyword forced_parameters in Minuit.__init__ is deprecated, use name), but only introducing the keyword when the old way becomes deprecated sounds weird (especially for a bugfix release).
On 1.4.9 this should definitely work, 1.5.x were withdrawn from iminuit people due to bugs, and 2.x need picca code changes due to breaks in backward compatibility (which I agree with Andreu we should just do).

**Comment by andreufont** [comment]
Will we have a task force telecon on Wednesday? If so, we could discuss. We could create an Everest tag with the current master (requiring iminuit 1.4.9), and then try to do all the changes that we have been pausing for a while (new continuum code, move iminuit to 2.x, and so on).

**Comment by iprafols** [comment]
After PR #825 abd te everest tag, we moved to using iminuit 2
