### ISSUE TITLE
Parallelise code to read DESI data

### ISSUE THREAD

**Issue by andreufont** [igmhub/picca#812]
Right now it takes over 40 minutes to read the spectra in Everest (100k quasars), but it should be very easy to parallelise the function to read data (read_desi_data in io.py).

**Comment by Waelthus** [comment]
Will be dealt with in PR #799

**Comment by andreufont** [comment]
@Waelthus , @iprafols - should we ask for volunteers for this type of tasks?

**Comment by iprafols** [comment]
Yes, we should ask for some vounteers in the next picca telecon
