### ISSUE TITLE
Clarify the rejection of spectra in continuum fitting (new delta extraction)

### ISSUE THREAD

**Issue by andreufont** [igmhub/picca#826]
There are printed warnings about "rejected forest" that are caused by "forest too short", and these cause the spectra to be dropped from the list of forests. 

Others happen later, like those with "negative continuum", but these are not dropped from the list of forest. It looks like they are their continuum are not fitted (see populate_los_ids function in py/picca/delta_extraction/expected_fluxes/dr16_expected_flux.py), but they are not deleted from the list of forests. 

Why are some rejected forests dropped sometimes, but not always? It would be good to clarify and document.

**Comment by iprafols** [comment]
Hi @andreufont ,

These are identified in the continuum fitting procedure and after this the list of forests is no longer used. I figured there was no need to remove them from the list, we simply skip them in the saving. But then, I could modify the filtering function (`fitler_forests` from `data.py`) and have it run also after the continuum fitting is run. Do you think this is necessary?

**Comment by andreufont** [comment]
I'm not sure we need to do any changes to the code itself, at least not yet. However, I'd try to add a bit of documentation / clarification in the code, and maybe also in the print messages.

**Comment by iprafols** [comment]
What do you mean? What would you like to be added to the print messages? 

A small correction to my message above: they are not skipped in saving but are saved with an array of 0 for delta (or delta_blind), weights and continuum. I guess this could be easily fixed using what I described above and would make the code simpler to follow

**Comment by andreufont** [comment]
One way or the other, it should be easy to follow which quasars were not included and why. I found confusing that some "rejected" quasars were dropped, but others were not. Dropping the latter (and not write empty files) might be enough. Long term, writing specific files with information about the objects drop, with extra information, would be quite useful. For instance, what is the redshift distribution of the quasars that were dropped due to the "forest too short"? What is the magnitude distribution of quasars that were dropped due to "negative continuum"?

**Comment by Waelthus** [comment]
Additionally, in case of issues also info like what TILE/NIGHT/PETAL/FIBER dropped QSOs have been on might be useful and could potentially be used to find problems further upstream.

**Comment by andreufont** [comment]
Agreed!

**Comment by iprafols** [comment]
Hi @andreufont , @Waelthus 

I have added a rejections log where the objects are listed. In this log there is the information from the forest header, i.e. RA, DEC, Z (quasar redshift),  and also TILE ,NIGHT, ... or THING_ID, PLATE, ... if they are available. It also contains the number of pixels in the forest and the rejection status (accepted, shortforest, ...)

Check the commit 2d90c8f8db152e00fb0bcab6a85f8f780eba65c5 

Let me know if this closes the issue

**Comment by andreufont** [comment]
This sounds useful for debugging cases like the one we have now with the new / old branch.

**Comment by iprafols** [comment]
My reasoning exactly, that's why I did it now
