### ISSUE TITLE
delta_extraction branch is blinding sv data

### ISSUE THREAD

**Issue by andreufont** [igmhub/picca#828]
I see column names = DELTA_BLIND even though I'm just using SV data.

**Comment by iprafols** [comment]
@andreufont This should have been addressed in the latest commits on branch delta extraction. Commits starting from b9d06af3879b9526383d23ccfd6c1503d6895d2b should have this fixed.

**Comment by andreufont** [comment]
I've been trying to browse the long list of commits, but I couldn't find it. Could you specify exactly where this was fixed?

**Comment by iprafols** [comment]
This was updated on 35eda96a071e2a6d433aa41941a1355f25ae378a, but there were also some bugs there. The first one I think works is the one I posted above

**Comment by andreufont** [comment]
Thanks. I won't be able to take a look at it until late next week, unfortunately. By the way, why are the DESI catalogs (from real data) used ZtruthCatalogue?

**Comment by iprafols** [comment]
No particular reason, it's just that I was using z_truth catalogues when I first coded it. I should probably rename it to DesiQuasarCatalogue

**Comment by iprafols** [comment]
Hi @andreufont I think this was already fixed. Maybe @calumgordon  can confirm it. If so we can close this issue

**Comment by andreufont** [comment]
@calumgordon - it would be great if you could confirm that when you are running analysis on *SV* data alone (no main survey data) the output delta files are not being blinded.

**Comment by calumgordon** [comment]
@andreufont @iprafols I can confirm that the sv deltas aren't being blinded, whether you chose blinding or not in the config

**Comment by iprafols** [comment]
Let's close this issue then
