### ISSUE TITLE
remove mean_delta vs. lambda_obs

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#88]
Since by definition the mean delta vs. lambda_obs is not zero, the cross-correlation function doesn't go to zero depending on the quasar distribution.
Also the projection of delta amplifies the effect.
 The solution is to remove the mean_delta by bins of lambda_obs before calculating the cross-correlation function.

Mean delta vs. lambda_obs for the LYA forest with a veto of sky emission lines and a correction for
errors in multiplicative flux calibration.

![capture du 2017-03-28 14-15-47](https://cloud.githubusercontent.com/assets/3166436/24404292/24f3a304-13c1-11e7-91a0-d7949cc2de2a.png)

**Comment by londumas** [comment]
It could be done the same way as it is done for the projection : i.e. with a command line like "--no-project" and using stack in prep_del.py

**Comment by ngbusca** [comment]
I'm not convinced that this is a problem and if it is, that that's the best solution. We should discuss this in person...

**Comment by londumas** [comment]
Ok, let's talk about that face to face.
I put some plots to show the problem when going to the Lyb+lya forest

the mean delta vs lambda_obs
![capture du 2017-03-28 14-53-01](https://cloud.githubusercontent.com/assets/3166436/24405740/42126ab0-13c6-11e7-8bdf-e7c04909bdec.png)

the wedge comparing the LYAxQSO and the LYBandLYAxQSO:
![capture du 2017-03-28 14-57-47](https://cloud.githubusercontent.com/assets/3166436/24405961/f4c64eec-13c6-11e7-8118-ea9d7ca50060.png)
![capture du 2017-03-28 14-57-01](https://cloud.githubusercontent.com/assets/3166436/24405959/f4c29d7e-13c6-11e7-8451-1a18176c4ac8.png)
![capture du 2017-03-28 14-56-41](https://cloud.githubusercontent.com/assets/3166436/24405960/f4c32fbe-13c6-11e7-8b5a-446bb73ab69d.png)
![capture du 2017-03-28 14-56-19](https://cloud.githubusercontent.com/assets/3166436/24405958/f4c27574-13c6-11e7-9e8e-e33ccefc0673.png)

**Comment by londumas** [comment]
In the code, looking at the stack of delta after the procjection, we get for the LYBandLYA forest:

![capture du 2017-03-28 16-41-54](https://cloud.githubusercontent.com/assets/3166436/24411227/ab5da598-13d5-11e7-941a-53967b500b64.png)

**Comment by ngbusca** [comment]
Could you do this plot for the 100 mocks?

**Comment by londumas** [comment]
@ngbusca Good idea, it must be smaller for the LYA only forest.
The previous was for the LYA+LYB to exaggerate the effect.

**Comment by londumas** [comment]
Here is the comparison between the cross correlation QSO x LYBandLYA forest for two cases:
     - projection of delta only (blue)
     - projection of delta then removing the mean delta per lambda_obs bins. (red)

Obviously the second case correct the effect.

![capture du 2017-03-28 17-36-01](https://cloud.githubusercontent.com/assets/3166436/24413941/37ef0964-13dd-11e7-9a4b-2ec23fef1158.png)
![capture du 2017-03-28 17-35-49](https://cloud.githubusercontent.com/assets/3166436/24413944/37f5a918-13dd-11e7-9f03-56fd051d4b14.png)
![capture du 2017-03-28 17-35-40](https://cloud.githubusercontent.com/assets/3166436/24413942/37f15d5e-13dd-11e7-8265-841b9a4b0921.png)
![capture du 2017-03-28 17-35-32](https://cloud.githubusercontent.com/assets/3166436/24413943/37f4202a-13dd-11e7-9f27-d5c8176ec155.png)

**Comment by ngbusca** [comment]
Do you have the same plots for lyman-alpha forest only?

**Comment by londumas** [comment]
yes, for the stack of mean delta we get the following, way smaller than for the LYBadnLYA.
![capture du 2017-03-28 17-03-42](https://cloud.githubusercontent.com/assets/3166436/24415327/6b626aa8-13e1-11e7-87c1-7fb0bc913db0.png)

I will get the LYA only and post it when I get it.

**Comment by ngbusca** [comment]
To me, these plots suggest that we should calculate the lyman alpha and lyman beta forests independently...

**Comment by londumas** [comment]
I disagree, this shows that this effect has to be present in the LYAalone x QSO, but weaker.

Here is the plot comparing the LYA x QSO and the LYAinLYBonly x QSO, we can see that even when dealing with the lybForest alone, we get this effect.

![capture du 2017-03-28 18-15-57](https://cloud.githubusercontent.com/assets/3166436/24415770/dd473698-13e2-11e7-88a7-b23bf7034f71.png)

**Comment by andreufont** [comment]
I'm not sure if I'm adding noise here, but what I would do is create a model that has all the components, and fit them in iteration. Something like:

flux = continuum * mean_flux_alpha * (1+delta_alpha) * mean_flux_beta * (1+delta_beta) * calibration_correction + noise

where calibration_correction would model things like Balmer lines or galactic absorption lines. It would be equal to one if there were no "systematics". 

You have three multiplicative global functions of lambda_obs, but not all pixels contribute to all of them, and this allows you to break the degeneracies. 

Is this what you are doing?

**Comment by andreufont** [comment]
And even when doing this, after the iterative process has converged, you still have stacks of delta_alpha(obs) or delta_beta(obs) that are not consistent with zero?

**Comment by ngbusca** [comment]
@londumas I don't really expect that fitting the entire lyman-alpha + lyman-beta interval works, you show that it doesn't. Then you show that with the lyman-alpha forest only data then no subtraction is needed. 

What I would do is to look at mocks with both ways of treating the data and look at the differences on the stack of 100 mocks. I don't see any other way to decide what's better.

**Comment by londumas** [comment]
yes, but I am not sure we have an donne this exactly :
> this allows you to break the degeneracies

**Comment by ngbusca** [comment]
@andreufont Of course it's perfectly flat by construction. The problem is when you apply the projection operator and look at the stack of projected deltas.

**Comment by londumas** [comment]
> Then you show that with the lyman-alpha forest only data then no subtraction is needed.

I have not showed that, I said that the correction is smaller (compare the two plots giving the stack of delta)

But I still need to post the wedges of cross comparing with and without subtraction the meanDelta.

**Comment by andreufont** [comment]
@ngbusca I see. I haven't thought much about continuum fitting + projection. I will shut up, sorry for adding noise :-)

**Comment by londumas** [comment]
Here is a comparison for the mean projected delta versus lambda_obs:
    - blue: gives one simulation
    - green gives the mean over the 100 simulations
    - red gives for the data: LYA only in DR12

The simulations are closer to 0 than the data, but they are very similar.

![capture du 2017-03-29 08-43-37](https://cloud.githubusercontent.com/assets/3166436/24441873/d1373500-145b-11e7-91b3-2da80bb4ea62.png)

**Comment by londumas** [comment]
Here is the comparison for the cross-correlation DR14: LYA x QSO:
    - in blue, no removing the mean delta
    - in red, removing the mean delta

The differences are small, and nearly limitted at mu~0

![capture du 2017-03-29 09-09-59](https://cloud.githubusercontent.com/assets/3166436/24442736/cac33918-145f-11e7-9f15-a9c91fce0a89.png)
![capture du 2017-03-29 09-09-42](https://cloud.githubusercontent.com/assets/3166436/24442738/cac5d2d6-145f-11e7-912c-4f2a2e69dda7.png)
![capture du 2017-03-29 09-09-29](https://cloud.githubusercontent.com/assets/3166436/24442735/cac1e6d0-145f-11e7-8150-fb866317a4f7.png)
![capture du 2017-03-29 09-09-17](https://cloud.githubusercontent.com/assets/3166436/24442737/cac4b0b8-145f-11e7-9539-3246e159af3e.png)

**Comment by andreufont** [comment]
Helion, can you show the BAO errors that you get in both cases, and the
overall chi^2?

**Comment by londumas** [comment]
no removing:
ap  = 1.077 \pm 0.033
at   = 0.929 \pm 0.040
chi2 = 2498.41 / (2504-15), p=0.44

removing:
ap = 1.077  \pm 0.033
at  = 0.923  \pm 0.039
chi2 = 2461.83 / (2504-15), p=0.65

**Comment by londumas** [comment]
so doesn't really affect the alpha_*

**Comment by ngbusca** [comment]
@londumas it would be great to see all these plots for the analysis with exact continuum

**Comment by londumas** [comment]
fixed in fix_issue_88

**Comment by ngbusca** [comment]
I'm reopening this issue to make sure we apply the following fix:

* modify the stack function to use only the "we" field
* compute the we field for the forest and delta before calling the stack
* add a few lines of code to calculate the mean forest and divide each forest by the mean
* add a few lines of code to calculate the mean delta and subtract the mean

**Comment by londumas** [comment]
ok, I will take care of this.

**Comment by ngbusca** [comment]
@londumas is this done now?

**Comment by londumas** [comment]
For now, we have something that works.
But you requested some changes not made I think.

> I'm reopening this issue to make sure we apply the following fix:

>  modify the stack function to use only the "we" field
>    compute the we field for the forest and delta before calling the stack
>     add a few lines of code to calculate the mean forest and divide each forest by the mean
>     add a few lines of code to calculate the mean delta and subtract the mean
