### ISSUE TITLE
deltas data format

### ISSUE THREAD

**Issue by cramirezpe** [igmhub/picca#920]
Moving here the discussion started in yesterday's telecon. 

Now that we are going to release a delta catalog for early-3d data, it might be a good time to think about changes in how deltas are stored.

The current format stores deltas creating one HDU card for each of the forests. This might not be optimal for efficiently reading deltas.

The option that seems more reasonable (as pointed out by Julien), is to store all the deltas in a single 2D array: this means one row for each quasar, having delta values for all wavelengths (even if they are just zeroes). There will be a similar array for weights. The information of each of the quasars (ID, RA, DEC, ....) will be included in a different card.

This scheme is indeed the one followed by James Farr for storing Lyman alpha fluxes in LyaCoLoRe mocks. The file structure can be seen under:
/global/project/projectdirs/desi/mocks/lya_forest/london/v9.0/v9.0.0

Once we agree on the scheme we consider to be ideal, we could think about how we want to implement it in picca, backwards compatibility, etc...

**Comment by p-slash** [comment]
I want to push back against these changes. I do not think we are limited by io at this point. We have 5yr DESI with no problem in reading data.

If we were to change how spectra are stored (with empty pixels) within picca, that will create a lot changes throughout the code. It is a lot of work (see PR #919 ). Also we then break some assumptions in correlation function estimators and p1d estimators.

As for just writing a post-processing script, we can write a small python script to re-organize data to make that public and not touch how picca works.

**Comment by Waelthus** [comment]
I agree that it wouldn't be great to change the internal data formats for the analysis at the present time as it might lead to side effects for people's EDR or early DR1 analyses. The post-processing script to re-organize the format for the public release sounds like a good compromise. It's definitely good to have potential data format changes on our radar.
A good time for an actual change in how picca_delta_extraction stores its outputs might be during the re-write of the continuum function analysis (as then it would be simpler to change the delta_extraction output routines and correlation input routines consistently). For Pk1d, I think, the read-in is overall simpler and might be changed at the same time (that is for the picca_Pk1d, not sure about your oqe code @p-slash). 
It might be good to decide on if and how we'd want to restructure rather sooner than later such that a post-processing script can be created and the existing Pk1d/correlation/delta_extraction scripts can be modified to be able to use the new version as an alternative data format (without removing the current one). When everything runs fine on that we can make the new format the new default and at some point remove the old one (for easier maintainability).

**Comment by iprafols** [comment]
After PR #919  was merged, it was substantially easier to change the format. This issue was addressed by PR #936. @cramirezpe  can you confirm that this is the case so that we can close the issue?

**Comment by cramirezpe** [comment]
Yes, this can be closed.
