### ISSUE TITLE
Bug when running picca v6 with y1 blinding

### ISSUE THREAD

**Issue by julienguy** [igmhub/picca#959]
I am running at NERSC in  `/global/cfs/cdirs/desi/users/jguy/lya/himalayas/`.

Successful run of
```
picca_delta_extraction.py picca-v6.0/deltas/delta_lya.ini
```
But crash at the next step
```
picca_cf.py --in-dir picca-v6.0/deltas/lya/Delta --out picca-v6.0/correlations/lya_x_lya/cf_lya_x_lya.fits --nside 16
ATTENTION: Analysis is blinded with strategy desi_y1
Om=0.315, Or=0.0, wl=-1.0, H0=100.0
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/conda/lib/python3.9/site-packages/fitsio/hdu/table.py", line 1745, in _extract_colnum
    colnum = self._colnames_lower.index(colstr.lower())
ValueError: 'delta_blind' is not in list
...
```

**Comment by julienguy** [comment]
The code is not ready the deltas with the correct format, so either I am missing some option or there is an inconsistency.

**Comment by julienguy** [comment]
Ah. I needed the option '--from-image'.
We should add a test in the code with an error message that explains when the format is not the expected one.

**Comment by iprafols** [comment]
As discussed on slack, it's probably a better option for the code to figure out the format on its own. @cramirezpe is working on that and we will release version 6.1 when we finish reviewing it
