### ISSUE TITLE
picca_xcf.py failing with new deltas

### ISSUE THREAD

**Issue by julienguy** [igmhub/picca#961]
picca_xcf.py --new-image failing with new delta format.

It's reading the deltas with the old format despite the use of option '--new-image '. Maybe I don't understand correctly how this should be run. I tried:
```
cd /global/cfs/cdirs/desi/users/jguy/lya/himalayas/

picca_xcf.py --in-dir picca-v6.0/deltas/lya/Delta --drq catalogs/QSO_catalog_dark_healpix_lastnight_lya.fits --in-dir picca-v6.0/deltas/lya/Delta --out picca-v6.0/correlations/lya_x_qso/cf_lya_x_qso.fits --nside 16 --from-image --mode desi_healpix
```

**Comment by iprafols** [comment]
presumably this should have the same origin as #959 and #960
