### ISSUE TITLE
remove empty bins when exporting for fits

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#97]
In some -obviously- rare case some bins are empty, they should be removed from the correlation function
in the export.py script.
For now we produce nan:
mda = (da*we).sum(axis=0)/we.sum(axis=0) in utils.py
da = (da*we).sum(axis=0)/we.sum(axis=0) in export.py

a simple cut on the sum of weight should be sufficient

**Comment by ngbusca** [comment]
fixed in master
